### ISSUE TITLE
RuntimeException when running AndroidInstrument Sample

### ISSUE THREAD

**Issue by eulerhm** [soot-oss/soot#1198]
Hi,

I am a new user of Soot. I have tried to run the AndroidInstrument sample (https://github.com/Sable/soot/wiki/Instrumenting-Android-Apps-with-Soot). 

I am using the following command line options:

java AndroidInstrument -android-jars /Users/eulerhm/Documents/workspaceTemp/Soot/android-platforms/ -process-dir bookcatalogue.apk

However, an exception occur:

java.lang.RuntimeException: None of the basic classes could be loaded! Check your Soot class path!
	at soot.Scene.loadBasicClasses(Scene.java:1684)
	at soot.Scene.loadNecessaryClasses(Scene.java:1769)
	at soot.Main.run(Main.java:241)
	at soot.Main.main(Main.java:141)
	at AndroidInstrument.main(AndroidInstrument.java:81)

Thanks for any help!

**Comment by lscoon** [comment]
Facing same problem
