### ISSUE TITLE
soot.SootResolver$SootClassNotFoundException when ...

### ISSUE THREAD

**Issue by 0range228** [soot-oss/soot#1348]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: <pre>trunk</pre>

Command line:
<pre>-cp . -pp TriangleClass.Triangle</pre>

Max Memory:
<pre>3641MB</pre>

Stack trace:
<pre>soot.SootResolver$SootClassNotFoundException: couldn&#39;t find class: TriangleClass.Triangle (is your soot-class-path set properly?)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:245)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:221)
	at soot.SootResolver.bringToSignatures(SootResolver.java:292)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:179)
	at soot.SootResolver.resolveClass(SootResolver.java:141)
	at soot.Scene.loadClass(Scene.java:1067)
	at soot.Scene.loadClassAndSupport(Scene.java:1052)
	at soot.Scene.loadNecessaryClass(Scene.java:1834)
	at soot.Scene.loadNecessaryClasses(Scene.java:1846)
	at soot.Main.run(Main.java:241)
	at soot.Main.main(Main.java:141)
</pre>

**Comment by linghuiluo** [comment]
The message tells you that the class TriangleClass.Triangle is not in your classpath (cp). You set the cp to . which is your current working directory. You should check if that class is there.
