### ISSUE TITLE
Soot 4.1 failed to convert bytecode of Kotlin suspend functions

### ISSUE THREAD

**Issue by yijunwu** [soot-oss/soot#1381]
When I use Soot 4.1 in a Kotlin project, it failed to convert class file that contains Kotlin suspend functions. (Suspend function is special functions that can be suspended and resumed, which is achieved by the Kotlin compiler adding additional Continuation object as last parameter to record and pass state of last suspension point). The error message is attached as below. BTW, I'm not 100% sure it's because of suspend funtion, just highly suspect.

```
Exception in thread "main" java.lang.RuntimeException: Failed to convert  
<com.alibaba.intl.trade.delivery.biz.service.impl.ByShipmentCenterDeliveryStatusChecker: java.lang.Object  
getShipmentTime$suspendImpl(com.alibaba.intl.trade.delivery.biz.service.impl.ByShipmentCenterDeliveryStatusChecker,  
com.alibaba.intl.logistics.toc.open.api.shipping.domain.ShippingOrder,kotlin.coroutines.Continuation)>  
at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:2163)  
at soot.SootMethod.retrieveActiveBody(SootMethod.java:402)  
at soot.jimple.toolkits.annotation.LineNumberAdder.internalTransform(LineNumberAdder.java:64)   
at soot.PackManager.runPacksNormally(PackManager.java:491)  
at soot.PackManager.runPacks(PackManager.java:419)  
at com.alibaba.intl.dftracker.LaunchSoot.run(LaunchSoot.java:128)   
at com.alibaba.intl.dftracker.LaunchSoot.main(LaunchSoot.java:76)   
Caused by: java.lang.AssertionError: Multiple un-equal stacks!   
at soot.asm.AsmMethodSource.addEdges(AsmMethodSource.java:1830)   
at soot.asm.AsmMethodSource.convert(AsmMethodSource.java:1895)   
at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:2161)   
... 6 more
```

**Comment by yijunwu** [comment]
And I just tried 4.0.0, the same error

**Comment by 9ayhub** [comment]
你好！！！请问你可以用soot处理其他kotlin项目吗？我想用soot生成一些kotlin项目的控制流图，希望能跟你交流一下呀~~~

**Comment by linghuiluo** [comment]
can you provide a test case for reproducing the error?
