### ISSUE TITLE
java.lang.RuntimeException when ...

### ISSUE THREAD

**Issue by pikuit** [soot-oss/soot#1407]
Steps to reproduce:
1.) ..Run the below code with jdk 8 in eclipse 2019-12 with soot-4.2.1-jar-with-dependencies.jar

Files used to reproduce: 
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import soot.MethodOrMethodContext;
import soot.PackManager;
import soot.Scene;
import soot.SceneTransformer;
import soot.SootClass;
import soot.SootMethod;
import soot.Transform;
import soot.jimple.toolkits.callgraph.CHATransformer;
import soot.jimple.toolkits.callgraph.CallGraph;
import soot.jimple.toolkits.callgraph.Targets;
public class MySootTest {
	
	
	public static void main(String args[]) {
		List<String> argsList = new ArrayList<String>(Arrays.asList(args));
		   argsList.addAll(Arrays.asList(new String[]{
				   "-w",
				   "-main-class",
				   "test.CallGraphs",//main-class
				   "test.CallGraphs",//argument classes
				   "test.A"			//
		   }));
		

		   PackManager.v().getPack("wjtp").add(new Transform("wjtp.myTrans", new SceneTransformer() {

			@Override
			protected void internalTransform(String phaseName, Map<String, String> options) {
			       CHATransformer.v().transform();
	                       SootClass a = Scene.v().getSootClass("testers.A");

			       SootMethod src = Scene.v().getMainClass().getMethodByName("doStuff");
			       CallGraph cg = Scene.v().getCallGraph();

			       Iterator<MethodOrMethodContext> targets = new Targets(cg.edgesOutOf(src));
			       while (targets.hasNext()) {
			           SootMethod tgt = (SootMethod)targets.next();
			           System.out.println(src + " may call " + tgt);
			       }
			}

						
			   
		   }));

	           args = argsList.toArray(new String[0]);
	           
	           soot.Main.main(args);
	}

}

Soot version: <pre>soot-4.2.1-jar-with-dependencies.jar from https://github.com/soot-oss/soot#how-do-i-obtain-the-nightly-builds</pre>

Command line:
<pre>-cp lib\soot-4.2.1-jar-with-dependencies.jar;. soot.Main -w -main-class test.CallGraphs test.CallGraphs test.A</pre>

Max Memory:
<pre>1797MB</pre>

Stack trace:
<pre>java.lang.RuntimeException: None of the basic classes could be loaded! Check your Soot class path!
	at soot.Scene.loadBasicClasses(Scene.java:1755)
	at soot.Scene.loadNecessaryClasses(Scene.java:1845)
	at soot.Main.run(Main.java:241)
	at soot.Main.main(Main.java:141)
	at MySootTest.main(MySootTest.java:54)
</pre>

**Comment by anddann** [comment]
Okay, the error is telling us that soot did not find the `rt.jar `.
Can you please provide the output of  `System.getProperty("java.home")`

**Comment by pikuit** [comment]
Remediated the soot classpath runtime exception by setting the below options to execute the soot and run callgraph.

 Options.v().set_verbose(false);
	        Options.v().set_keep_line_number(true);
	        Options.v().set_src_prec(Options.src_prec_class);
	        //Options.v().set_soot_classpath(classpath);
	        Options.v().set_prepend_classpath(true);
	        Options.v().set_soot_classpath(classpath);


But facing issue with callgraph as Soot is unable to run with main method in spring mvc code .  kindly assist how to do a callgraph in spring-mvc

**Comment by anddann** [comment]
Super, that the RuntimeException is fixed!
Can you give more details concerning the issue? Does not soot find the main method?

**Comment by pikuit** [comment]
Any update on how to achieve callgraph on spring-mvc application

**Comment by harshita19244** [comment]
@pikuit In the options you set to resolve the runtime exception, what did you set as classpath?

**Comment by MarcMil** [comment]
This is not a bug in Soot, the classpath is inconsistent and would not work on the original application.
In spring-asm-3.1.4.RELEASE.jar (https://repo1.maven.org/maven2/org/springframework/spring-asm/3.1.4.RELEASE/spring-asm-3.1.4.RELEASE.jar), ```org.springframework.asm.MethodVisitor``` is an interface.

```org.springframework.asm.commons.AnalyzerAdapter``` (part of spring-core-3.2.2.RELEASE.jar https://repo1.maven.org/maven2/org/springframework/spring-core/3.2.2.RELEASE/spring-core-3.2.2.RELEASE.jar) calls a method of a ```MethodVisitor``` as if it was an abstract class. This is because the very same JAR contains the same class ```org.springframework.asm.MethodVisitor```, but as an abstract class instead of an interface. Due to the order of the classes in the class path, soot loads the version from spring-asm-3.1.4.RELEASE.jar.

Make sure to have a coherent class path, i.e. utilize the same class path that would be used if you would run the application.
