### ISSUE TITLE
Semantic Error: duplicate member B in compilation unit

### ISSUE THREAD

**Issue by gdevanla** [soot-oss/soot#141]
Here is the stack trace. Description follows below:

Exception in thread "main" soot.CompilationDeathException: there were errors during parsing and/or type checking (JastAdd frontend)
    at soot.JastAddInitialResolver.formAst(JastAddInitialResolver.java:63)
    at soot.JavaClassSource.resolve(JavaClassSource.java:54)
    at soot.SootResolver.bringToHierarchy(SootResolver.java:226)
    at soot.SootResolver.bringToSignatures(SootResolver.java:250)
    at soot.SootResolver.bringToBodies(SootResolver.java:291)
    at soot.SootResolver.processResolveWorklist(SootResolver.java:161)
    at soot.SootResolver.resolveClass(SootResolver.java:127)
    at soot.Scene.loadClass(Scene.java:610)
    at soot.Scene.loadClassAndSupport(Scene.java:595)
    at soot.Scene.loadNecessaryClass(Scene.java:1221)
    at soot.Scene.loadNecessaryClasses(Scene.java:1235)
    at soot.Main.run(Main.java:167)
    at soot.Main.main(Main.java:141)

I see this error is the develop branch of soot. The same command runs successfully for 2.5 version of Soot.

Here are the steps to reproduce:
1. Create folder /tmp/src/package1
2. Create A.java under package1

```
package package1;

public class A {

    public static void main(String[] args){
        B b = new B();
        b.callFunInB();
    }
}
```
1. Create B.java under package 1

```
package package1;
public class B {

    public void callFunInB() {
        System.out.println("B called");
    }
}
```
1. Run the following command:

```
$JAVA_EXE -cp $SOOT_JAR_CP soot.Main -f J -x "java." -w -cp $RT_JAR:$APP_CLASSPATH package1.A
```

where 

```
JAVA_EXE = java 
SOOT_JAR_CP = the soot-version.jar
SOOT_JAR_CP=$SOOT_JAR:<Other jar files needed to run soot>
RT_JAR=/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/classes.jar:/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/lib/jce.jar
APP_CLASSPATH=/tmp/src/
```

**Comment by esherman77** [comment]
I have this issue right now again. I use soot-trunk.jar provided in https://ssebuild.cased.de/nightly/soot/lib/
