### ISSUE TITLE
NullpointerException for most larger programs with 4.2.1

### ISSUE THREAD

**Issue by martinschaef** [soot-oss/soot#1413]
I tried the version 4.2.1 from Maven Central with 
https://github.com/Morgan-Stanley/SilverKing
and
https://github.com/usgs/nshmp-haz

and I get the NullpointerException below. 

I remember having this problem with some of the soot releases floating around the internet. I did not have it with https://github.com/soot-oss/soot/releases/tag/4.1.0 and some of the release in https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-snapshot/. Looks like an issue with the bundled heros version.

```
Successfully started process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/bin/java''
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "Thread-4" java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:890)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3850)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3875)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4800)
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4806)
        at soot.jimple.toolkits.ide.icfg.AbstractJimpleBasedICFG.getOrCreateUnitGraph(AbstractJimpleBasedICFG.java:126)
        at soot.jimple.toolkits.ide.icfg.AbstractJimpleBasedICFG.isExitStmt(AbstractJimpleBasedICFG.java:149)
        at soot.jimple.toolkits.ide.icfg.AbstractJimpleBasedICFG.isExitStmt(AbstractJimpleBasedICFG.java:52)
        at heros.solver.IDESolver$PathEdgeProcessingTask.run(IDESolver.java:897)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
java.util.concurrent.RejectedExecutionException: Task heros.solver.IDESolver$PathEdgeProcessingTask@403552e6 rejected from heros.solver.CountingThreadPoolExecutor@7a78da04[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 4]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
        at heros.solver.CountingThreadPoolExecutor.execute(CountingThreadPoolExecutor.java:51)
        at heros.solver.IDESolver.scheduleEdgeProcessing(IDESolver.java:286)
        at heros.solver.IDESolver.propagate(IDESolver.java:651)
        at heros.solver.IDESolver.submitInitialSeeds(IDESolver.java:228)
        at heros.solver.IDESolver.solve(IDESolver.java:215)
```

**Comment by martinschaef** [comment]
nvm ... was something with the entry points. Still can't tell what went wrong. This is the code to set the entry points
```
        // use all public methods in application classes as entry points.
        final List<SootMethod> entryPoints = Scene.v()
                                                  .getApplicationClasses()
                                                  .stream()
                                                  .map(SootClass::getMethods)
                                                  .flatMap(List::stream)
                                                  .filter(SootMethod::isPublic)
                                                  .filter(SootMethod::isConcrete)
                                                  .collect(Collectors.toList());
        Scene.v().setEntryPoints(entryPoints);
        // Runs the actual Soot analysis.
        log.info(String.format("Starting analysis with %d entry points.", entryPoints.size()));
        PackManager.v().runPacks();
```
The log before the exception is:
```
2020-08-08 12:42:49,771 INFO - Starting analysis with 2136 entry points.
```
If I remove the `.filter(SootMethod::isPublic)`, the exception goes away. And the log looks as follows:
```
2020-08-08 12:43:57,200 INFO - Starting analysis with 4271 entry points.
```
Any idea why?
