### ISSUE TITLE
weird heros exception

### ISSUE THREAD

**Issue by Jacoppy** [soot-oss/soot#1464]
Hello,
I am simply reading and then write back an apk and I obtain the following series of errors :
`[Thread-16] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: DynamicInvokeExpr not supported: dynamicinvoke "makeConcatWithConstants" <java.lang.String (boolean,boolean,boolean,boolean,boolean,boolean)>(z0, z1, z2, z3, z4, z5) <java.lang.invoke.StringConcatFactory: java.lang.invoke.CallSite makeConcatWithConstants(java.lang.invoke.MethodHandles$Lookup,java.lang.String,java.lang.invoke.MethodType,java.lang.String,java.lang.Object[])>("javax.xml.datatype.Duration#getXMLSchemaType(): this Duration does not match one of the XML Schema date/time datatypes: year set = \u0001 month set = \u0001 day set = \u0001 hour set = \u0001 minute set = \u0001 second set = \u0001")
java.lang.Error: DynamicInvokeExpr not supported: dynamicinvoke "makeConcatWithConstants" <java.lang.String (boolean,boolean,boolean,boolean,boolean,boolean)>(z0, z1, z2, z3, z4, z5) <java.lang.invoke.StringConcatFactory: java.lang.invoke.CallSite makeConcatWithConstants(java.lang.invoke.MethodHandles$Lookup,java.lang.String,java.lang.invoke.MethodType,java.lang.String,java.lang.Object[])>("javax.xml.datatype.Duration#getXMLSchemaType(): this Duration does not match one of the XML Schema date/time datatypes: year set = \u0001 month set = \u0001 day set = \u0001 hour set = \u0001 minute set = \u0001 second set = \u0001")
	at soot.toDex.ExprVisitor.caseDynamicInvokeExpr(ExprVisitor.java:155)
	at soot.jimple.internal.JDynamicInvokeExpr.apply(JDynamicInvokeExpr.java:220)
	at soot.toDex.StmtVisitor.caseAssignStmt(StmtVisitor.java:497)
	at soot.jimple.internal.JAssignStmt.apply(JAssignStmt.java:242)
	at soot.toDex.DexPrinter.toInstructions(DexPrinter.java:1543)
	at soot.toDex.DexPrinter.toMethodImplementation(DexPrinter.java:1206)
	at soot.toDex.DexPrinter.toMethods(DexPrinter.java:1093)
	at soot.toDex.DexPrinter.addAsClassDefItem(DexPrinter.java:666)
	at soot.toDex.DexPrinter.add(DexPrinter.java:1677)
	at soot.PackManager.writeClass(PackManager.java:1096)
	at soot.PackManager.lambda$writeOutput$1(PackManager.java:699)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "Thread-16" java.lang.Error: DynamicInvokeExpr not supported: dynamicinvoke "makeConcatWithConstants" <java.lang.String (boolean,boolean,boolean,boolean,boolean,boolean)>(z0, z1, z2, z3, z4, z5) <java.lang.invoke.StringConcatFactory: java.lang.invoke.CallSite makeConcatWithConstants(java.lang.invoke.MethodHandles$Lookup,java.lang.String,java.lang.invoke.MethodType,java.lang.String,java.lang.Object[])>("javax.xml.datatype.Duration#getXMLSchemaType(): this Duration does not match one of the XML Schema date/time datatypes: year set = \u0001 month set = \u0001 day set = \u0001 hour set = \u0001 minute set = \u0001 second set = \u0001")
	at soot.toDex.ExprVisitor.caseDynamicInvokeExpr(ExprVisitor.java:155)
	at soot.jimple.internal.JDynamicInvokeExpr.apply(JDynamicInvokeExpr.java:220)
	at soot.toDex.StmtVisitor.caseAssignStmt(StmtVisitor.java:497)
	at soot.jimple.internal.JAssignStmt.apply(JAssignStmt.java:242)
	at soot.toDex.DexPrinter.toInstructions(DexPrinter.java:1543)
	at soot.toDex.DexPrinter.toMethodImplementation(DexPrinter.java:1206)
	at soot.toDex.DexPrinter.toMethods(DexPrinter.java:1093)
	at soot.toDex.DexPrinter.addAsClassDefItem(DexPrinter.java:666)
	at soot.toDex.DexPrinter.add(DexPrinter.java:1677)
	at soot.PackManager.writeClass(PackManager.java:1096)
	at soot.PackManager.lambda$writeOutput$1(PackManager.java:699)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "main" java.lang.RuntimeException: java.lang.Error: DynamicInvokeExpr not supported: dynamicinvoke "makeConcatWithConstants" <java.lang.String (boolean,boolean,boolean,boolean,boolean,boolean)>(z0, z1, z2, z3, z4, z5) <java.lang.invoke.StringConcatFactory: java.lang.invoke.CallSite makeConcatWithConstants(java.lang.invoke.MethodHandles$Lookup,java.lang.String,java.lang.invoke.MethodType,java.lang.String,java.lang.Object[])>("javax.xml.datatype.Duration#getXMLSchemaType(): this Duration does not match one of the XML Schema date/time datatypes: year set = \u0001 month set = \u0001 day set = \u0001 hour set = \u0001 minute set = \u0001 second set = \u0001")
	at soot.PackManager.writeOutput(PackManager.java:716)
	at soot.PackManager.writeDexOutput(PackManager.java:584)
	at soot.PackManager.writeOutput(PackManager.java:567)
	at Instrumenter.main(Instrumenter.java:299)
Caused by: java.lang.Error: DynamicInvokeExpr not supported: dynamicinvoke "makeConcatWithConstants" <java.lang.String (boolean,boolean,boolean,boolean,boolean,boolean)>(z0, z1, z2, z3, z4, z5) <java.lang.invoke.StringConcatFactory: java.lang.invoke.CallSite makeConcatWithConstants(java.lang.invoke.MethodHandles$Lookup,java.lang.String,java.lang.invoke.MethodType,java.lang.String,java.lang.Object[])>("javax.xml.datatype.Duration#getXMLSchemaType(): this Duration does not match one of the XML Schema date/time datatypes: year set = \u0001 month set = \u0001 day set = \u0001 hour set = \u0001 minute set = \u0001 second set = \u0001")
	at soot.toDex.ExprVisitor.caseDynamicInvokeExpr(ExprVisitor.java:155)
	at soot.jimple.internal.JDynamicInvokeExpr.apply(JDynamicInvokeExpr.java:220)
	at soot.toDex.StmtVisitor.caseAssignStmt(StmtVisitor.java:497)
	at soot.jimple.internal.JAssignStmt.apply(JAssignStmt.java:242)
	at soot.toDex.DexPrinter.toInstructions(DexPrinter.java:1543)
	at soot.toDex.DexPrinter.toMethodImplementation(DexPrinter.java:1206)
	at soot.toDex.DexPrinter.toMethods(DexPrinter.java:1093)
	at soot.toDex.DexPrinter.addAsClassDefItem(DexPrinter.java:666)
	at soot.toDex.DexPrinter.add(DexPrinter.java:1677)
	at soot.PackManager.writeClass(PackManager.java:1096)
	at soot.PackManager.lambda$writeOutput$1(PackManager.java:699)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
`

For writing the apk back I am using `            PackManager.v().writeOutput(); //writes the final apk
`
Any idea why it happens?

**Comment by Jacoppy** [comment]
I found a solution to this. Apparently using Java 8 fixes it. I am using the last release of flowdroid libraries that can be found here : https://github.com/secure-software-engineering/FlowDroid/releases. Is flowdroid not aligned with the last version of soot by any chance? Thank you
