### ISSUE TITLE
Bad use of class type

### ISSUE THREAD

**Issue by Killuaa27** [soot-oss/soot#1474]
I am working on Android app transformation.

After correctly setting the initial parameters for working with Android APK (such as _set_process_multiple_dex_, _set_output_format_ etc.) we create an **ApplicationTransformer** class which extends **BodyTransformer** . The code inside the _internalTransformer_ method could be anything, for example:
```
@Override
protected void internalTransform(final Body b, String phaseName, Map<String, String> map){
        return;
}
``` 

We add our **ApplicationTransformer**  with `PackManager.v().getPack("jtp").add(transform);` and run `PackManager.v().runPacks();`

During the execution _of runPack_ method we get the following message:

```
Warning: Bad use of class type at $r26 = $r12 in <com.fasterxml.jackson.databind.deser.BasicDeserializerFactory: void _addDeserializerFactoryMethods(com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.BeanDescription,com.fasterxml.jackson.databind.introspect.VisibilityChecker,com.fasterxml.jackson.databind.AnnotationIntrospector,com.fasterxml.jackson.databind.deser.impl.CreatorCollector,java.util.Map)> in <com.fasterxml.jackson.databind.deser.BasicDeserializerFactory: void _addDeserializerFactoryMethods(com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.BeanDescription,com.fasterxml.jackson.databind.introspect.VisibilityChecker,com.fasterxml.jackson.databind.AnnotationIntrospector,com.fasterxml.jackson.databind.deser.impl.CreatorCollector,java.util.Map)>
Bad use of class type at $r26 = $r12 in <com.fasterxml.jackson.databind.deser.BasicDeserializerFactory: void _addDeserializerFactoryMethods(com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.BeanDescription,com.fasterxml.jackson.databind.introspect.VisibilityChecker,com.fasterxml.jackson.databind.AnnotationIntrospector,com.fasterxml.jackson.databind.deser.impl.CreatorCollector,java.util.Map)> in <com.fasterxml.jackson.databind.deser.BasicDeserializerFactory: void _addDeserializerFactoryMethods(com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.BeanDescription,com.fasterxml.jackson.databind.introspect.VisibilityChecker,com.fasterxml.jackson.databind.AnnotationIntrospector,com.fasterxml.jackson.databind.deser.impl.CreatorCollector,java.util.Map)>

	at soot.validation.CheckTypesValidator.checkCopy(CheckTypesValidator.java:164)
	at soot.validation.CheckTypesValidator.validate(CheckTypesValidator.java:65)
	at soot.Body.validate(Body.java:253)
	at soot.jimple.JimpleBody.validate(JimpleBody.java:112)
	at soot.jimple.JimpleBody.validate(JimpleBody.java:98)
	at soot.PackManager.runBodyPacks(PackManager.java:1007)
	at soot.PackManager.lambda$runBodyPacks$0(PackManager.java:660)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Where `$r26` is a `com.fasterxml.jackson.databind.introspect.AnnotatedParameter` and `$r12` is a `java.lang.Object`.

This warning raise a **ValidationException** which leads to Execution failed error. Is there a solution for this situation? 

The problem could be replicated over several applications, with different variable types. For instance, in our example, we used [this one](https://f-droid.org/it/packages/openfoodfacts.github.scrachx.openfood/).

**Comment by humblepoti** [comment]
+1 I'm also facing the same exact issue with transformations on Android APK.
