### ISSUE TITLE
Java JDK class analysis attempts to resolve Android specific class resulting in RuntimeException

### ISSUE THREAD

**Issue by knewbury01** [soot-oss/soot#1499]
Im not entirely sure this is an error, but to me the behaviour is unexpected.

## Replication details:
  * build: Using the 0080486332d4d0aff423e6ec4b31c15e04b5f4ff latest (at time of issue) develop
  * command line: 
```
java -cp /root/sootclasses-trunk-jar-with-dependencies.jar:<path to rt.jar> soot.Main -cp <path to rt.jar> -p cg all-reachable:true -w -allow-phantom-refs -f jimple sun.misc.ExtensionDependency
```
  * using an openjdk-8 jvm - therefore rt.jar is from there
  * the exact loc from the analysed class that causes the failure is [this](http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/tip/src/share/classes/sun/misc/ExtensionDependency.java#l466)

## Failure stack trace:
```
Found 55 instanceinvoke , 4 staticinvoke edge descriptions
java.lang.RuntimeException: This operation requires resolving level HIERARCHY but android.os.Handler is at resolving level DANGLING
If you are extending Soot, try to add the following call before calling soot.Main.main(..):
Scene.v().addBasicClass(android.os.Handler,HIERARCHY);
Otherwise, try whole-program mode (-w).
	at soot.SootClass.checkLevelIgnoreResolving(SootClass.java:198)
	at soot.SootClass.checkLevel(SootClass.java:180)
	at soot.FastHierarchy.canStoreClass(FastHierarchy.java:358)
	at soot.FastHierarchy.canStoreType(FastHierarchy.java:307)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.skipSite(OnFlyCallGraphBuilder.java:676)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.addType(OnFlyCallGraphBuilder.java:594)
	at soot.jimple.toolkits.callgraph.CallGraphBuilder.processReceivers(CallGraphBuilder.java:211)
	at soot.jimple.toolkits.callgraph.CallGraphBuilder.process(CallGraphBuilder.java:131)
	at soot.jimple.toolkits.callgraph.CallGraphBuilder.build(CallGraphBuilder.java:117)
	at soot.jimple.toolkits.callgraph.CHATransformer.internalTransform(CHATransformer.java:51)
	at soot.SceneTransformer.transform(SceneTransformer.java:36)
	at soot.Transform.apply(Transform.java:102)
	at soot.RadioScenePack.internalApply(RadioScenePack.java:68)
	at soot.jimple.toolkits.callgraph.CallGraphPack.internalApply(CallGraphPack.java:58)
	at soot.Pack.apply(Pack.java:117)
	at soot.PackManager.runWholeProgramPacks(PackManager.java:611)
	at soot.PackManager.runPacksNormally(PackManager.java:495)
	at soot.PackManager.runPacks(PackManager.java:419)
	at soot.Main.run(Main.java:291)
	at soot.Main.main(Main.java:140
```
## Bug details:
  * as we can see from the stack trace, [this](https://github.com/soot-oss/soot/blob/develop/src/main/java/soot/jimple/toolkits/callgraph/OnFlyCallGraphBuilder.java#L676) check in Soot is the one that causes the failure. 
  * I believe this bug was introduced in commit: 1687e2c0d93ac0d1d58aa1cd7647efc5a63f33cd
   

## Reasons why I think this is a bug:
  * I think when analyzing a Java class, from a JDK, one would not expect to have `android.os.Handler` available to the analysis environment. That doesn't really make sense, and one should not have to go get that class to perform something that is simply Java (not Android) analysis

## What I am unsure about:
  * I am not sure why [this](http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/tip/src/share/classes/sun/misc/ExtensionDependency.java#l466) might seem to be able to resolve to the Handler kind... based on [this](https://github.com/soot-oss/soot/blob/develop/src/main/java/soot/Kind.java#L59) inline documentation, I think it cannot? But this is the part that I am not sure about.
  * if its not a bug, please justify why it makes sense to require `android.os.Handler` to be on the classpath for this specific case! Thanks!

**Comment by testguru2020** [comment]
your cg option doesn't look right for me.

**Comment by linghuiluo** [comment]
Your cg option doesn’t look right for me

**Comment by testguru2020** [comment]
you can ignore the resolution level with -ignore-resolving-levels

**Comment by linghuiluo** [comment]
You can ignore the resolution error with -ignore-resolving-Levels

**Comment by knewbury01** [comment]
The error still occurs even with the cg option omitted (I admit its a bit weird, but its for a bit of an odd use case).

But ! The `-ignore-resolving-levels ` option definitely fixes it, thanks! I was not aware of that option, I only tried `-ire` previously. Thanks!
