### ISSUE TITLE
java.lang.NullPointerException when ...

### ISSUE THREAD

**Issue by shanmugasundharamselvadurai** [soot-oss/soot#1509]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: trunk

Command line:
-force-android-jar /Users/shanmugasundharam/Library/Android/sdk/platforms/android-18/android.jar -process-dir /Users/shanmugasundharam/Desktop/Deepintent/DeepIntent/example/benign//19682615_com.apporder.myLivermore.apk -ire -pp -keep-line-number -allow-phantom-refs -src-prec apk -w -d testspace/19682615_com.apporder.myLivermore.apk

Max Memory:
24000MB

Stack trace:
java.lang.NullPointerException
	at soot.JastAddJ.Program.initPaths(Program.java:350)
	at soot.SootResolver.<init>(SootResolver.java:89)
	at soot.Singletons.soot_SootResolver(Singletons.java:802)
	at soot.SootResolver.v(SootResolver.java:92)
	at soot.Scene.tryLoadClass(Scene.java:661)
	at soot.Scene.loadBasicClasses(Scene.java:1258)
	at soot.Scene.loadNecessaryClasses(Scene.java:1337)
	at soot.Main.run(Main.java:214)
	at soot.Main.main(Main.java:152)
	at RetargetedApp.main(RetargetedApp.java:24)

**Comment by jpstotz** [comment]
Are you sure you are using unmodified version from master, because line [350 in `soot.JastAddJ.Program`](https://github.com/soot-oss/soot/blob/master/src/main/generated/jastadd/soot/JastAddJ/Program.java#L350) is nothing that could throw a NullPointerException.

May be you should post the `initPaths` source code of your version up to the line that causes the NullPointerException.
