### ISSUE TITLE
Runtime Exception: could not load classfile: java.io.ObjectInputStrem

### ISSUE THREAD

**Issue by fang19911030** [soot-oss/soot#1514]
### Java info: 

-   openjdk version "1.8.0_275"
-   OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
-   OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode
-  JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64

### Error command:
java -cp sootclasses-2.3.0.jar:jasminclasses-2.3.0.jar:polyglotclasses-1.3.5.jar soot.Main -cp .:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar Foo

java -cp sootclasses-2.3.0.jar:jasminclasses-2.3.0.jar:polyglotclasses-1.3.5.jar soot.Main -cp . -pp Foo

### Error info

Soot started on Wed Dec 30 21:57:15 EST 2020
Unknown tag in constant pool: 18 at entry 350
Exception in thread "main" java.lang.RuntimeException: Could not load classfile: java.io.ObjectInputStream
	at soot.coffi.Util.resolveFromClassFile(Util.java:75)
	at soot.CoffiClassSource.resolve(CoffiClassSource.java:39)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:184)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:140)
	at soot.SootResolver.resolveClass(SootResolver.java:124)
	at soot.Scene.tryLoadClass(Scene.java:359)
	at soot.Scene.loadBasicClasses(Scene.java:917)
	at soot.Scene.loadNecessaryClasses(Scene.java:937)
	at soot.Main.run(Main.java:169)
	at soot.Main.main(Main.java:145)

**Comment by fang19911030** [comment]
This issue does not exist for version: soot-4.2.1.
