### ISSUE TITLE
java.lang.StackOverflowError for emitUnits

### ISSUE THREAD

**Issue by HTQianqian** [soot-oss/soot#1549]
Hi, 
When I try to generate the jimple files from .class,  the StackOverflowError exception happens:

Exception in thread "Thread-0" Exception in thread "main" java.lang.StackOverflowError
	at soot.asm.AsmMethodSource.emitUnits(AsmMethodSource.java:1938)
	at soot.asm.AsmMethodSource.emitUnits(AsmMethodSource.java:1938)
	at soot.asm.AsmMethodSource.emitUnits(AsmMethodSource.java:1938)
	at soot.asm.AsmMethodSource.emitUnits(AsmMethodSource.java:1938)
	at soot.asm.AsmMethodSource.emitUnits(AsmMethodSource.java:1938)
----------------------------------------------------------------------------------------------
The commands: 
`Options.v().set_no_bodies_for_excluded(true);
Options.v().set_allow_phantom_refs(true);
Options.v().set_output_format(Options.output_format_jimple);

Options.v().set_process_dir(Collections.singletonList("D:\\classes"));
Options.v().set_src_prec(Options.src_prec_only_class);

Options.v().set_keep_line_number(true);

Scene.v().loadNecessaryClasses();

PackManager.v().writeOutput();`

calsses files:
[classes.zip](https://github.com/soot-oss/soot/files/5938108/classes.zip)

**Comment by zhangziqiang1** [comment]
In version 4.0.0, I got the same problem.
