### ISSUE TITLE
Soot fails due to not found super class 

### ISSUE THREAD

**Issue by piskachev** [soot-oss/soot#1562]
While Jimple is constructed there is a case where Soot fails at [this point](https://github.com/soot-oss/soot/blob/59931576784b910a7d38f81910b7313aa2feafea/src/main/java/soot/SootClass.java#L892).

The example trace is below. What is happening is that some classes get generated and we are missing them on the classpath so Soot does not find them. Even though the phantom option is enabled some of them as you see are not phantom and this exception occurs. 

How can we handle such cases? Is it possible to relax the condition when super class is not found? 
It is better to have incomplete hierarchy as long as Soot does not crashes.  

------------------------------------------------------
Caused by: java.lang.RuntimeException: Failed to apply jb to <some.Mod: java.util.List getAuthorizers(java.lang.String,java.lang.String)>
    at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:2191) 
    at soot.SootMethod.retrieveActiveBody(SootMethod.java:402) 
    at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processNewMethod(OnFlyCallGraphBuilder.java:812) 
    at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processReachables(OnFlyCallGraphBuilder.java:286) 
    at soot.jimple.toolkits.callgraph.CallGraphBuilder.build(CallGraphBuilder.java:111) 
    at soot.jimple.toolkits.callgraph.CHATransformer.internalTransform(CHATransformer.java:51) 
    at soot.SceneTransformer.transform(SceneTransformer.java:36) 
    at soot.Transform.apply(Transform.java:102) 
    at soot.RadioScenePack.internalApply(RadioScenePack.java:68) 
    at soot.jimple.toolkits.callgraph.CallGraphPack.internalApply(CallGraphPack.java:58) 
    at soot.Pack.apply(Pack.java:117) 
    at utils.SootRunner.run(SootRunner.java:137) 
    at some.Runner.runTransforms(Runner.java:111) 
    ... 6 more
Caused by: java.lang.RuntimeException: no superclass for some.Interface
    at soot.SootClass.getSuperclass(SootClass.java:897) 
    at soot.jimple.toolkits.typing.fast.BytecodeHierarchy.buildAncestryTree(BytecodeHierarchy.java:76) 
    at soot.jimple.toolkits.typing.fast.BytecodeHierarchy.lcas_(BytecodeHierarchy.java:174) 
    at soot.jimple.toolkits.typing.fast.BytecodeHierarchy.lcas(BytecodeHierarchy.java:292) 
    at soot.jimple.toolkits.typing.fast.TypeResolver.applyAssignmentConstraints(TypeResolver.java:544) 
    at soot.jimple.toolkits.typing.fast.TypeResolver.inferTypes(TypeResolver.java:148) 
    at soot.jimple.toolkits.typing.TypeAssigner.internalTransform(TypeAssigner.java:121) 
    at soot.BodyTransformer.transform(BodyTransformer.java:51) 
    at soot.Transform.apply(Transform.java:120) 
    at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:73) 
    at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:105) 
    at soot.Pack.apply(Pack.java:125) 
    at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:2189) 
    at soot.SootMethod.retrieveActiveBody(SootMethod.java:402) 
    at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processNewMethod(OnFlyCallGraphBuilder.java:812) 
    at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processReachables(OnFlyCallGraphBuilder.java:286) 
    at soot.jimple.toolkits.callgraph.CallGraphBuilder.build(CallGraphBuilder.java:111) 
    at soot.jimple.toolkits.callgraph.CHATransformer.internalTransform(CHATransformer.java:51) 
    at soot.SceneTransformer.transform(SceneTransformer.java:36) 
    at soot.Transform.apply(Transform.java:102) 
    at soot.RadioScenePack.internalApply(RadioScenePack.java:68) 
    at soot.jimple.toolkits.callgraph.CallGraphPack.internalApply(CallGraphPack.java:58) 
    at soot.Pack.apply(Pack.java:117)
    at utils.SootRunner.run(SootRunner.java:137) 
    at x.y.Z.runTransforms(Runner.java:111) 
    ... 6 more

**Comment by ericbodden** [comment]
Hi all. Goran does some.Interface actually have a superclass in the bytecode? Or is the bytecode broken?

**Comment by ericbodden** [comment]
@piskachev there is an option "-ignore-resolution-errors", I think. Did you try to enable this? If this still does not work, then we should guard the throw-Statement at at soot.SootClass.getSuperclass(SootClass.java:897) such that it silently ignores the error if and only if this option is enabled.

**Comment by piskachev** [comment]
Thanks for the hint, Eric! 
Indeed the option was not enabled. But still the guard is necessary as Soot will still fail at that point. I added this change and created the pull request.

**Comment by mbenz89** [comment]
This is a valid solution to the problem. I think in the long run, however, we should generate phantom superclasses for non-phantom classes for which we do not know the super class.

**Comment by ericbodden** [comment]
The pull request contains more changes than required, please check @piskachev

**Comment by piskachev** [comment]
This is now merged and works. Im closing the issue.
