### ISSUE TITLE
encounter java.lang.NullPointerException while using soot-2.5.0 processing .java file

### ISSUE THREAD

**Issue by Marlv** [soot-oss/soot#1563]
First time using soot, fail to processing .java files and here's my command
_[root@localhost soottest]# java -jar soot-2.5.0.jar -cp . -pp A B_
with trace
_Soot started on Fri Feb 26 23:43:32 PST 2021
Exception in thread "main" java.lang.NullPointerException
	at soot.JastAddInitialResolver.resolveFromJavaFile(JastAddInitialResolver.java:103)
	at soot.JavaClassSource.resolve(JavaClassSource.java:57)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:215)
	at soot.SootResolver.bringToSignatures(SootResolver.java:239)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:154)
	at soot.SootResolver.resolveClass(SootResolver.java:124)
	at soot.Scene.loadClass(Scene.java:448)
	at soot.Scene.loadClassAndSupport(Scene.java:433)
	at soot.Scene.loadNecessaryClass(Scene.java:1053)
	at soot.Scene.loadNecessaryClasses(Scene.java:1067)
	at soot.Main.run(Main.java:167)
	at soot.Main.main(Main.java:141)_
this directory has three files
_[root@localhost soottest]# ls
A.java  B.java  soot-2.5.0.jar_

**Comment by fade03** [comment]
Hi, have you found any solutions? Seems that I meet the same trouble #1848 .

**Comment by fade03** [comment]
#1848 I have solved this problem on my machine.

**Comment by Marlv** [comment]
搞半天搞不好之后我就换成用optaplanner去了（看了眼你的地区我就用中文了...


> #1848 I have solved this problem on my machine.
