### ISSUE TITLE
Nullpointer exception in LocalGenerator.java:145

### ISSUE THREAD

**Issue by martinschaef** [soot-oss/soot#1582]
For the following two classes I get a NullPointerException:
```java
import java.io.Serializable;

@SuppressWarnings("serial")
public abstract class Sub<T extends Serializable> {
    protected T value;

    public T getValue() {
        return value;
    }
}
```
and 
```java
import java.util.Comparator;
import java.util.Set;
import java.util.stream.Collectors;

public class SootCrash {

    private <T extends Sub<Long>> String buildFilterExpression(
        final Set<T> ids, String columnName, boolean include) {

        ids.stream()
           .sorted(Comparator.comparingLong(Sub::getValue));

        return null;
    }
}
```

The stack trace is as follows:
```
Caused by: java.lang.NullPointerException
	at soot.javaToJimple.LocalGenerator.generateLocal(LocalGenerator.java:145)
	at soot.LambdaMetaFactory$ThunkMethodSource.unbox(LambdaMetaFactory.java:697)
	at soot.LambdaMetaFactory$ThunkMethodSource.adapt(LambdaMetaFactory.java:646)
	at soot.LambdaMetaFactory$ThunkMethodSource.invokeImplMethod(LambdaMetaFactory.java:798)
	at soot.LambdaMetaFactory$ThunkMethodSource.getInvokeBody(LambdaMetaFactory.java:580)
	at soot.LambdaMetaFactory$ThunkMethodSource.getBody(LambdaMetaFactory.java:419)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:445)
	at soot.LambdaMetaFactory.makeLambdaHelper(LambdaMetaFactory.java:265)
	at soot.asm.AsmMethodSource.convertInvokeDynamicInsn(AsmMethodSource.java:1477)
	at soot.asm.AsmMethodSource.convert(AsmMethodSource.java:1874)
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:2121)
	... 17 more
```

**Comment by linghuiluo** [comment]
https://github.com/soot-oss/soot/pull/1595/files

**Comment by linghuiluo** [comment]
The problem is `Comparator.comparingLong(Sub::getValue)`  Here unboxing is happening from the return type of `Sub::getValue` which is `java.io.Serializable` to long. A cast from `java.io.Serializable` to the wrapper type `java.lang.Long` needs to added at first.
