### ISSUE TITLE
Problem with jimple body transform

### ISSUE THREAD

**Issue by anon721702** [soot-oss/soot#1626]
**Describe the bug**
Not able to produce jimple body due to following runtime exception: "Exception reference used other than as the first statement of an exception handler." I am Using whole program mode with wjtp pack. 

**To reproduce**
Pack wjtp = PackManager.v().getPack("jb");
wjtp.add(new Transform("jb.myTransform", new MyTransform()));
 soot.Main.main(args);

args are : -whole-program -allow-phantom-refs -process-dir pathToClassFiles

**Expected behavior**
Due to this exception method jimple body is not obtained for further analysis. Any option in soot to ignore such exception and produce jimple body in spark/CHA.

**Stacktrace**
Exception in thread "main" java.lang.RuntimeException: Exception reference used other than as the first statement of an exception handler.
	at soot.jimple.toolkits.typing.fast.AugEvalFunction.eval_(AugEvalFunction.java:162)
	at soot.jimple.toolkits.typing.fast.AugEvalFunction.eval(AugEvalFunction.java:41)
	at soot.jimple.toolkits.typing.fast.TypeResolver.applyAssignmentConstraints(TypeResolver.java:407)
	at soot.jimple.toolkits.typing.fast.TypeResolver.inferTypes(TypeResolver.java:113)
	at soot.jimple.toolkits.typing.TypeAssigner.internalTransform(TypeAssigner.java:101)
	at soot.BodyTransformer.transform(BodyTransformer.java:51)
	at soot.Transform.apply(Transform.java:104)
	at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:66)
	at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:89)
	at soot.Pack.apply(Pack.java:124)
	at soot.coffi.CoffiMethodSource.getBody(CoffiMethodSource.java:117)
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:89)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
	at soot.jimple.toolkits.annotation.LineNumberAdder.internalTransform(LineNumberAdder.java:44)
	at soot.PackManager.runPacks(PackManager.java:332)

**Input file**
 .class, .jar, .dex, .apk any file caused the issue.

**Additional context**
Ask for any further details required. Please guide on it. Soot mail-list doesn't work for asking any query.

**Comment by linghuiluo** [comment]
Can you provide the class caused the crash? Maybe try to disable the TypeAssigner to with `-p jb.tr off` to see if it is really a bug there?
