### ISSUE TITLE
java.lang.NullPointerException when trying to use Soot

### ISSUE THREAD

**Issue by aralyekta** [soot-oss/soot#1645]
Steps to reproduce:
1.) Type the following command to the terminal in the same directory as the soot file.
java -cp sootclasses-trunk-jar-with-dependencies.jar soot.tools.CFGViewer -cp . -pp -process-dir .
Using soot.Main instead of soot.tools.CFGViewer gives the same error.

Files used to reproduce: 
I am trying to run the abovementioned command in the main folder of the following repository, where I also added the soot file:
https://github.com/mockito/mockito

Soot version: <pre>4.1.0</pre>

Command line:
<pre>java -cp sootclasses-trunk-jar-with-dependencies.jar soot.tools.CFGViewer -cp . -pp -process-dir .</pre>

Max Memory:
<pre>1920MB</pre>

Stack trace:
<pre>java.lang.NullPointerException
	at soot.JastAddJ.Program.initPaths(Program.java:336)
	at soot.SootResolver.initializeProgram(SootResolver.java:91)
	at soot.SootResolver.getProgram(SootResolver.java:386)
	at soot.JastAddInitialResolver.formAst(JastAddInitialResolver.java:62)
	at soot.JavaClassSource.resolve(JavaClassSource.java:66)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:253)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:221)
	at soot.SootResolver.bringToSignatures(SootResolver.java:292)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:179)
	at soot.SootResolver.resolveClass(SootResolver.java:141)
	at soot.Scene.loadClass(Scene.java:1009)
	at soot.Scene.loadClassAndSupport(Scene.java:994)
	at soot.Scene.loadNecessaryClasses(Scene.java:1822)
	at soot.Main.run(Main.java:241)
	at soot.Main.main(Main.java:141)
	at soot.tools.CFGViewer.main(CFGViewer.java:101)
</pre>

**Comment by linghuiluo** [comment]
Hi, I see the error is from soot's source code front end. It is not maintained. Soot's bytecode front end is up-to-date. You can compile the source code to bytecode at first.
