### ISSUE TITLE
java.lang.IllegalArgumentException when ...

### ISSUE THREAD

**Issue by liangyixiki** [soot-oss/soot#1647]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: <pre>trunk</pre>

Command line:
<pre>-cp /Users/w/Desktop/test/MethodGraph/target/classes -pp -f J -W testers.CallGraphs</pre>

Max Memory:
<pre>1820MB</pre>

Stack trace:
<pre>java.lang.IllegalArgumentException: Attempt to create SootMethodRef with null returnType
	at soot.SootMethodRefImpl.&#60;init&#62;(SootMethodRefImpl.java:84)
	at soot.Scene.makeMethodRef(Scene.java:1917)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.addType(OnFlyCallGraphBuilder.java:649)
	at soot.jimple.toolkits.callgraph.CallGraphBuilder.processReceivers(CallGraphBuilder.java:201)
	at soot.jimple.toolkits.callgraph.CallGraphBuilder.process(CallGraphBuilder.java:128)
	at soot.jimple.toolkits.callgraph.CallGraphBuilder.build(CallGraphBuilder.java:114)
	at soot.jimple.toolkits.callgraph.CHATransformer.internalTransform(CHATransformer.java:54)
	at soot.SceneTransformer.transform(SceneTransformer.java:36)
	at soot.Transform.apply(Transform.java:105)
	at soot.RadioScenePack.internalApply(RadioScenePack.java:64)
	at soot.jimple.toolkits.callgraph.CallGraphPack.internalApply(CallGraphPack.java:61)
	at soot.Pack.apply(Pack.java:118)
	at soot.PackManager.runWholeProgramPacks(PackManager.java:619)
	at soot.PackManager.runPacksNormally(PackManager.java:500)
	at soot.PackManager.runPacks(PackManager.java:425)
	at soot.Main.run(Main.java:280)
	at soot.Main.main(Main.java:142)
</pre>

**Comment by liangyixiki** [comment]
I just want to use -w

**Comment by linghuiluo** [comment]
if you don't provide the class file for us to reproduce this issue, we cant help you.

**Comment by canliture** [comment]
The same problem, I gave the solution at #1697  #1696
