### ISSUE TITLE
java.lang.RuntimeException when ...

### ISSUE THREAD

**Issue by aralyekta** [soot-oss/soot#1671]
Steps to reproduce:
1.) Using "G.v().reset()" between two consecutive pack runs. Namely, running the below function more than once.

Files used to reproduce: 
```
	public static void getJimple(SootClass cls, SootMethod target, boolean recursive, boolean first)
	{
		if (!first)
		{
			G.v().reset();
			cls.setApplicationClass();
		}
			JimpleBody body = (JimpleBody) target.retrieveActiveBody();
			UnitPatchingChain units = body.getUnits();
			for (Unit unit:units)
			{	
				if (unit instanceof InvokeStmt)
				{
					Stmt stm = (Stmt) unit;
					System.out.println(unit.getJavaSourceStartLineNumber() + " " + target.toString() + " might call " + stm.getInvokeExpr());
				}
				else
				{
					System.out.println(unit.getJavaSourceStartLineNumber()+":"+unit.toString());
				}
			}	
			if (recursive)
			{
				for (Unit unit:units)
				{
					if (unit instanceof InvokeStmt)
					{
						Stmt stm = (Stmt) unit;
						InvokeExpr exp = stm.getInvokeExpr();
						String str = exp.toString();
						String subStr = parse(str);
						String className = subStr.split(": ")[0];
						String methodName = subStr.split(": ")[1];
						SootClass class2 = Scene.v().getSootClass(className);
						SootMethod method2 = class2.getMethod(methodName);
						System.out.println("***** : " + target.toString() + " may call " + exp.getMethod().toString());
						getJimple(class2, method2, true, false);
					}
				}
			}
	}
}
```
Soot version: <pre>trunk</pre>

Command line:
<pre>-w -keep-line-number -no-bodies-for-excluded org.apache.commons.jxpath.JXPathIntrospector</pre>

Max Memory:
<pre>1707MB</pre>

Stack trace:
<pre>java.lang.RuntimeException: Failed to convert &#60;org.apache.commons.jxpath.JXPathBasicBeanInfo: void &#60;init&#62;(java.lang.Class)&#62;
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:2163)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:402)
	at dk.brics.soot.callgraphs.CallGraphExample.getJimple(CallGraphExample.java:67)
	at dk.brics.soot.callgraphs.CallGraphExample.getJimple(CallGraphExample.java:104)
	at dk.brics.soot.callgraphs.CallGraphExample$1.internalTransform(CallGraphExample.java:234)
	at soot.SceneTransformer.transform(SceneTransformer.java:36)
	at soot.Transform.apply(Transform.java:102)
	at soot.ScenePack.internalApply(ScenePack.java:35)
	at soot.Pack.apply(Pack.java:117)
	at soot.PackManager.runWholeProgramPacks(PackManager.java:612)
	at soot.PackManager.runPacksNormally(PackManager.java:495)
	at soot.PackManager.runPacks(PackManager.java:419)
	at soot.Main.run(Main.java:269)
	at soot.Main.main(Main.java:141)
	at dk.brics.soot.callgraphs.CallGraphExample.main(CallGraphExample.java:239)
Caused by: java.lang.RuntimeException: java.lang.Object was not found on classpath.
	at soot.asm.AsmMethodSource.getClassFromScene(AsmMethodSource.java:374)
	at soot.asm.AsmMethodSource.convertMethodInsn(AsmMethodSource.java:1354)
	at soot.asm.AsmMethodSource.convert(AsmMethodSource.java:1907)
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:2161)
	... 14 more
</pre>

**Comment by linghuiluo** [comment]
Caused by: java.lang.RuntimeException: java.lang.Object was not found on classpath.

**Comment by MarcMil** [comment]
Why would you want to reset while Soot runs? Of course everything breaks. G.reset causes essentially the whole soot instance to disappear, including the scene with all the classes, etc.

Also, probably what you want to do is instead of check instanceof InvokeStmt is checking whether ```containsinvokeExpr``` returns true, because assignments with method invocations (method invocations where the return value is needed) are instanceof AssignStmt.

Besides, you might want to replace the recursive approach with a worklist. This would remove the first and recursive parameter as well, which does not seem clean to me.

Also, you might want to use a call graph, because in Java, virtual method invocations may actually invoke a lot of different methods potentially due to overridden methods in subclasses. You can ask an InvokeExpr for its referenced method, but this not guaranteed to be called due to this mechanism.
