### ISSUE TITLE
Can’t process files with “.” in the filename？

### ISSUE THREAD

**Issue by 9ayhub** [soot-oss/soot#1703]
The following command runs correctly:

`java -cp "D:\isoot\sootclasses-trunk-jar-with-dependencies.jar" soot.tools.CFGViewer -cp .  -pp  .\test-1\B
Soot started on Thu Jul 15 20:05:17 CST 2021
Soot finished on Thu Jul 15 20:05:18 CST 2021
Soot has run for 0 min. 0 sec.`

However, adding a "." to the filename will cause an error:

`java -cp "D:\isoot\sootclasses-trunk-jar-with-dependencies.jar" soot.tools.CFGViewer -cp .  -pp  .\test-1.1\B
Soot started on Thu Jul 15 20:05:33 CST 2021
soot.SootResolver$SootClassNotFoundException: couldn't find class: .\test-1.1\B (is your soot-class-path set properly?)
        at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:245)
        at soot.SootResolver.bringToHierarchy(SootResolver.java:221)
        at soot.SootResolver.bringToSignatures(SootResolver.java:292)
        at soot.SootResolver.processResolveWorklist(SootResolver.java:179)
        at soot.SootResolver.resolveClass(SootResolver.java:141)
        at soot.Scene.loadClass(Scene.java:1067)
        at soot.Scene.loadClassAndSupport(Scene.java:1052)
        at soot.Scene.loadNecessaryClass(Scene.java:1834)
        at soot.Scene.loadNecessaryClasses(Scene.java:1846)
        at soot.Main.run(Main.java:241)
        at soot.Main.main(Main.java:141)
        at soot.tools.CFGViewer.main(CFGViewer.java:101)

Ouuups... something went wrong! Sorry about that.
.............`

I don't know how to solve it, could you help me?

**Comment by 9ayhub** [comment]
By the way, I'm dealing with a lot of  similar files, so I can't just delete the ".”
