### ISSUE TITLE
java.lang.RuntimeException: Failed to apply jb to

### ISSUE THREAD

**Issue by angwli** [soot-oss/soot#1705]
I'm tryting to generate a call graph from a jar using soot 4.2.1, then I faced a bug as follows.
group id: guru.nidi
artifact id: code-assert
version: 0.9.15

Caused by: java.lang.RuntimeException: Failed to apply jb to <org.jetbrains.kotlin.resolve.scopes.GivenFunctionsMemberScope: java.util.List createFakeOverrides(java.util.List)>
        at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:2191)
        at soot.SootMethod.retrieveActiveBody(SootMethod.java:402)
        at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processNewMethod(OnFlyCallGraphBuilder.java:846)
        at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processReachables(OnFlyCallGraphBuilder.java:313)
        at soot.jimple.toolkits.callgraph.CallGraphBuilder.build(CallGraphBuilder.java:111)
        at soot.jimple.toolkits.callgraph.CHATransformer.internalTransform(CHATransformer.java:51)
        at soot.SceneTransformer.transform(SceneTransformer.java:36)
        at soot.SceneTransformer.transform(SceneTransformer.java:42)
        at soot.SceneTransformer.transform(SceneTransformer.java:46)

Caused by: java.lang.IllegalArgumentException: value may not be null
        at soot.AbstractValueBox.setValue(AbstractValueBox.java:37)
        at soot.toolkits.scalar.LocalPacker.internalTransform(LocalPacker.java:192)
        at soot.BodyTransformer.transform(BodyTransformer.java:51)
        at soot.Transform.apply(Transform.java:120)
        at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:80)
        at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:105)
        at soot.Pack.apply(Pack.java:125)
        at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:2189)

Here is the list of entry points:
[
guru.nidi.codeassert.checkstyle.StyleChecks.sun()
guru.nidi.codeassert.checkstyle.StyleChecks.google()
guru.nidi.codeassert.checkstyle.StyleChecks.Sun.maxLineLen(int)
guru.nidi.codeassert.junit.CodeAssertMatchers.hasNoCheckstyleIssues()
guru.nidi.codeassert.checkstyle.StyleChecks.Google.maxLineLen(int)
]

And my options are:
argsList.addAll(Arrays.asList("-p", "jb", "use-original-names:true"));
String[] args = (String[])argsList.toArray(new String[0]);
Options.v().parse(args);
Options.v().set_src_prec(4);
Options.v().set_whole_program(true);
Options.v().set_allow_phantom_refs(true);
Options.v().set_keep_line_number(true);
Options.v().set_verbose(true);
Options.v().set_keep_line_number(true);
Options.v().setPhaseOption("cg", "all-reachable:true");
Options.v().set_no_bodies_for_excluded(true);
Options.v().set_app(true);

Actually when I tried other jars, I didn't meet this. I check the code but I don't know what LocalToNewLocal means.
Thanks.

**Comment by MarcMil** [comment]
Works with the current nightly version.
