### ISSUE TITLE
[Thread-5] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed:

### ISSUE THREAD

**Issue by gspeiliu** [soot-oss/soot#1712]
I am trying to use soot on an Android dex file. It shows the error below:

[Thread-5] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: org.jf.dexlib2.dexbacked.instruction.DexBackedInstruction10x cannot be cast to org.jf.dexlib2.iface.instruction.formats.PackedSwitchPayload
java.lang.ClassCastException: org.jf.dexlib2.dexbacked.instruction.DexBackedInstruction10x cannot be cast to org.jf.dexlib2.iface.instruction.formats.PackedSwitchPayload
	at soot.dexpler.instructions.PackedSwitchInstruction.switchStatement(PackedSwitchInstruction.java:56)
	at soot.dexpler.instructions.SwitchInstruction.deferredJimplify(SwitchInstruction.java:66)
	at soot.dexpler.DexBody.jimplify(DexBody.java:645)
	at soot.dexpler.DexMethod$1.getBody(DexMethod.java:120)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:402)
	at soot.PackManager$1.run(PackManager.java:1279)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-5" java.lang.ClassCastException: org.jf.dexlib2.dexbacked.instruction.DexBackedInstruction10x cannot be cast to org.jf.dexlib2.iface.instruction.formats.PackedSwitchPayload
	at soot.dexpler.instructions.PackedSwitchInstruction.switchStatement(PackedSwitchInstruction.java:56)
	at soot.dexpler.instructions.SwitchInstruction.deferredJimplify(SwitchInstruction.java:66)
	at soot.dexpler.DexBody.jimplify(DexBody.java:645)
	at soot.dexpler.DexMethod$1.getBody(DexMethod.java:120)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:402)
	at soot.PackManager$1.run(PackManager.java:1279)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ClassCastException: org.jf.dexlib2.dexbacked.instruction.DexBackedInstruction10x cannot be cast to org.jf.dexlib2.iface.instruction.formats.PackedSwitchPayload
	at soot.dexpler.instructions.PackedSwitchInstruction.switchStatement(PackedSwitchInstruction.java:56)
	at soot.dexpler.instructions.SwitchInstruction.deferredJimplify(SwitchInstruction.java:66)
	at soot.dexpler.DexBody.jimplify(DexBody.java:645)
	at soot.dexpler.DexMethod$1.getBody(DexMethod.java:120)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:402)
	at soot.PackManager$1.run(PackManager.java:1279)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by gspeiliu** [comment]
The dex files are unzipped from framework.jar from pulled from the Android device. Does anyone know?
