### ISSUE TITLE
Problem analyzing a JAR file programmatically

### ISSUE THREAD

**Issue by prashast** [soot-oss/soot#1721]
**Describe the bug**
I am trying to analyze a JAR file programmatically using Soot. However, its facing issues while trying to load classes specifically that are in nested directories inside the JAR file. The error suggests I am not setting the classpath correctly but I have double-checked that it is indeed correct because when I use the CLI tool to analyze the same jar file no errors are raised. I tried setting the main class (commented out lines in the snippet) but that also did not help as well. I am using the following code snippet to analyze the JAR file programmatically. Could you let me know what am I doing incorrectly?
```
package gadget;

import soot.*;
import soot.options.Options;

import java.util.ArrayList;
import java.util.List;

public class Gadget{

    public static String jarFile =  System.getProperty("user.dir") + "/../../target/" + "clojure-1.8.0.jar";
    public static String sourceDirectory = System.getProperty("user.dir") + "/../../target";
    // public static String mainClass = "clojure.main";

    public static void main(String[] args) {
        G.reset();
        Options.v().set_soot_classpath(sourceDirectory);

        Options.v().set_prepend_classpath(true); //-pp
        List<String> processdirs = new ArrayList<>();
        processdirs.add(jarFile);
        Options.v().set_process_dir(processdirs);
        Options.v().set_whole_program(true); //-w

        System.out.println("Jar file:" + jarFile);
        System.out.println("Source Dir:" + sourceDirectory);

        // SootClass appClass = Scene.v().loadClassAndSupport(mainClass);
        // Scene.v().setMainClass(appClass);
        Scene.v().loadNecessaryClasses(); // <--- Soot errors out here

        // // Iterate through all classes
        for (SootClass clazz : Scene.v().getClasses()) {
            System.out.println("Class name: " + clazz.getName());
        }
    }
}
```
 The same issue of class loading raising an error does _not_ raise an issue if I use Soot as a CLI tool.

**Input file**
[soot_repro.zip](https://github.com/soot-oss/soot/files/6984896/soot_repro.zip)

**To reproduce**
The above repro package can be used to recreate my problem.
- Unzip the directory
- `cd soot_repro/src/static`
- `gradle run`

**Expected behavior**
While trying to load the classes from the jar no errors should be raised and it should be handle nested directories in the jar file.

**Stacktrace**
```
Exception in thread "main" soot.SootResolver$SootClassNotFoundException: couldn't find class: clojure.pprint (is your soot-class-path set properly?)
        at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:245)
        at soot.SootResolver.bringToHierarchy(SootResolver.java:221)
        at soot.SootResolver.bringToSignatures(SootResolver.java:292)
        at soot.SootResolver.bringToBodies(SootResolver.java:332)
        at soot.SootResolver.processResolveWorklist(SootResolver.java:171)
        at soot.SootResolver.resolveClass(SootResolver.java:141)
        at soot.Scene.loadClass(Scene.java:1069)
        at soot.Scene.loadClassAndSupport(Scene.java:1054)
        at soot.Scene.loadNecessaryClasses(Scene.java:1861)
        at gadget.Gadget.main(Gadget.java:30)
```

**Additional context**
Add any other context about the problem here, which might help us to understand or solve your problem better.

**Comment by canliture** [comment]
Maybe you can just set the option to solve it at the moment:
`Options.v().set_allow_phantom_refs(true);`

According to the `printStackTrace` you have provided, I have tried to debug your problem. Finally I found that Soot resolves the jar file 'clojure-1.8.0.jar' not so well.

When Soot resolves the class named `clojure.pprint$get_format_arg`, Soot will consider class name `clojure.pprint` as `clojure.pprint$get_format_arg` 's outer class. So soot will resolve the class named `clojure.pprint`. But actually, there is no class named `clojure.pprint` in your jar file.

Actually, It's unusual like this: class name contains `$` in user's code.

The code about `setting outer class` is here: https://github.com/soot-oss/soot/blob/24d676fcabeb2d76bb4bfb5ec3a0b7235bafd8e6/src/main/java/soot/asm/AsmClassSource.java#L71-L85

**Comment by prashast** [comment]
Thanks for looking into this! Yes, allowing `phantom_refs` would help me overcome this problem. However for this JAR file I am interested in analyzing all classes and I assume that won't be possible for phantom classes that are created, eg. `clojure.pprint$get_format_arg`.

Interestingly, if I use Soot as a standalone tool using the following command in the above repro package like so:
 ```
 cd soot_repro/target
 java -cp sootclasses-trunk-jar-with-dependencies.jar soot.Main -cp . -pp -process-dir clojure-1.8.0.jar
 ``` 
 Then Soot is able to process all classes correctly including `clojure.pprint$get_format_arg` without requiring me to turn on the `-allow-phantom-refs` switch. Do you have some insight as to why Soot being used as a CLI tool is able to process the JAR file correctly but not when its done programmatically? I have attached the soot jar file that I used for your reference below.

[sootjar.zip](https://github.com/soot-oss/soot/files/6995833/sootjar.zip)

**Comment by canliture** [comment]
For the JAR file `clojure-1.8.0.jar`, if you allow phantom_refs, Soot will actually analyze all classes.(setting the option just avoids crashing in this case)
Soot just 'incorrectly' (maybe could't simply say like this) consider `clojure.pprint` as the outer class of `clojure.pprint$get_format_arg`. So the class `clojure.pprint`, which not exists in your jar file, will be a phantom class.Other classes have no effect on this.

- - - - - 
I don't know what version your `sootclasses-trunk-jar-with-dependencies.jar` is. 

But your soot version has not handled outerclass in the class `AsmClassSource`(Decompiled code shows this).So you will not crash in command line. In programming way, I `use your soot jar as my soot dependency`, there is also no crashing problem(without allowing `phantom_refs`).
