### ISSUE TITLE
Soot java 9 version runtime error

### ISSUE THREAD

**Issue by harshita19244** [soot-oss/soot#1745]
Steps to reproduce:
1.) I am tryin to generate callgraphs using soot. I used this version of soot for it: https://soot-build.cs.upb.de/public/origin/java9/soot/soot-j9/build/. My code works with java 6 but fails with java 9. It would be helpful to know I am doing wrong. I am using Intellij and passing the arguments in the main method.
![image](https://user-images.githubusercontent.com/60603854/133054865-77603e55-2d51-4815-8ca6-498cd6b61767.png)

Files used to reproduce: 
...

Soot version: <pre>trunk</pre>

Command line:
<pre>-w -no-bodies-for-excluded -pp -soot-class-path -main-class testers.CallGraphs testers.A</pre>

Max Memory:
<pre>512MB</pre>

Stack trace:
<pre>java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.Exception: Error: The path &#39;C:\Users\USer\sootrun\-main-class&#39; does not exist.
	at soot.SourceLocator.getClassSourceType(SourceLocator.java:311)
	at soot.SourceLocator.lookupInClassPath(SourceLocator.java:612)
	at soot.asm.AsmClassProvider.find(AsmClassProvider.java:39)
	at soot.SourceLocator.getClassSource(SourceLocator.java:186)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:232)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:222)
	at soot.SootResolver.bringToSignatures(SootResolver.java:293)
	at soot.SootResolver.bringToBodies(SootResolver.java:333)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:172)
	at soot.SootResolver.resolveClass(SootResolver.java:142)
	at soot.Scene.loadClass(Scene.java:1001)
	at soot.Scene.loadClassAndSupport(Scene.java:986)
	at soot.Scene.loadNecessaryClass(Scene.java:1790)
	at soot.Scene.loadNecessaryClasses(Scene.java:1802)
	at soot.Main.run(Main.java:241)
	at soot.Main.main(Main.java:141)
	at CallGraphExample.main(CallGraphExample.java:61)
Caused by: java.util.concurrent.ExecutionException: java.lang.Exception: Error: The path &#39;C:\Users\USer\sootrun\-main-class&#39; does not exist.
	at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:137)
	at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2348)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2320)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at soot.SourceLocator.getClassSourceType(SourceLocator.java:309)
	... 16 more
Caused by: java.lang.Exception: Error: The path &#39;C:\Users\USer\sootrun\-main-class&#39; does not exist.
	at soot.SourceLocator$1.load(SourceLocator.java:72)
	at soot.SourceLocator$1.load(SourceLocator.java:67)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	... 22 more
</pre>

**Comment by harshita19244** [comment]
@anddann

**Comment by anddann** [comment]
the argument to `-soot-class-path` must be the directory that contains your classfiles, e.g. `.`.

Also the version you use is bit deprecated, just use the newest version from maven directly by including



```
  <dependency>
    <groupId>org.soot-oss</groupId>
    <artifactId>soot</artifactId>
    <version>4.2.1</version>
  </dependency>
```

in your pom.xml.  The soot version from maven already includes the java 9 features

**Comment by anddann** [comment]
@harshita19244 Can you shorty state how you solved the problem, such that people who find this ticket also know how to solve the problem? Than you!
