### ISSUE TITLE
java.lang.NullPointerException when ...

### ISSUE THREAD

**Issue by Michael-Lxpig** [soot-oss/soot#1747]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: <pre>trunk</pre>

Command line:
<pre>-pp -process-dir /Users/lxpig/Desktop/soot -src-prec class</pre>

Max Memory:
<pre>2048MB</pre>

Stack trace:
<pre>java.lang.NullPointerException
	at soot.JastAddJ.Program.initPaths(Program.java:336)
	at soot.SootResolver.initializeProgram(SootResolver.java:91)
	at soot.SootResolver.getProgram(SootResolver.java:386)
	at soot.JastAddInitialResolver.formAst(JastAddInitialResolver.java:62)
	at soot.JavaClassSource.resolve(JavaClassSource.java:66)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:253)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:221)
	at soot.SootResolver.bringToSignatures(SootResolver.java:292)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:179)
	at soot.SootResolver.resolveClass(SootResolver.java:141)
	at soot.Scene.loadClass(Scene.java:1009)
	at soot.Scene.loadClassAndSupport(Scene.java:994)
	at soot.Scene.loadNecessaryClasses(Scene.java:1822)
	at soot.Main.run(Main.java:241)
	at soot.Main.main(Main.java:141)
	at analysis.MainClass.main(MainClass.java:16)
</pre>

**Comment by linghuiluo** [comment]
are you using soot to analyze source code?

**Comment by Michael-Lxpig** [comment]
Yes and&nbsp; the problem has been solved, it was because the class file I was analyzing have something wrong and the problem can run properly after deleting the class file, thanks a lot




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Linghui ***@***.***&gt;; 
发送时间: 2021年9月17日(星期五) 下午4:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [soot-oss/soot] java.lang.NullPointerException when ... (#1747)





 
are you using soot to analyze source code?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
