### ISSUE TITLE
java.lang.RuntimeException when ...

### ISSUE THREAD

**Issue by hunie-son** [soot-oss/soot#1770]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: <pre>trunk</pre>

Command line:
<pre>soot.Main -cp . -w -android-jars /Users/seonghun/Library/Android/sdk/platforms -src-prec apk -f jimple -process-multiple-dex /Users/seonghun/Desktop/ISU/Project/2021 Fall/miniDroid/Twitter_v9.11.0-release.00_apkpure.com.apk</pre>

Max Memory:
<pre>4096MB</pre>

Stack trace:
<pre>java.lang.RuntimeException: None of the basic classes could be loaded! Check your Soot class path!
	at soot.Scene.loadBasicClasses(Scene.java:1755)
	at soot.Scene.loadNecessaryClasses(Scene.java:1845)
	at soot.Main.run(Main.java:241)
	at soot.Main.main(Main.java:141)
</pre>

**Comment by buriedpot** [comment]
Maybe add a "-pp" option before "-cp" can solve your problem.

**Comment by hunie-son** [comment]
> Maybe add a "-pp" option before "-cp" can solve your problem.

Hi thank you for your help. however. it gives more errors.
(base) seonghun@seonghun miniDroid % java -jar soot-4.2.1-jar-with-dependencies.jar soot.Main -pp -cp . -w -android-jars /Users/seonghun/Library/Android/sdk/platforms -src-prec apk -f jimple -process-multiple-dex /Users/seonghun/Desktop/ISU/Project/2021\ Fall/miniDroid/Instagram_v205.0.0.34.114_apkpure.com.apk
Soot started on Sun Oct 31 15:15:00 CDT 2021
java.lang.RuntimeException: no apk file given
	at soot.Scene.defaultAndroidClassPath(Scene.java:687)
	at soot.Scene.defaultClassPath(Scene.java:620)
	at soot.Scene.getSootClassPath(Scene.java:327)
	at soot.SourceLocator.getClassSource(SourceLocator.java:179)
	at soot.Scene.tryLoadClass(Scene.java:1030)
	at soot.Scene.loadBasicClasses(Scene.java:1744)
	at soot.Scene.loadNecessaryClasses(Scene.java:1845)
	at soot.Main.run(Main.java:241)
	at soot.Main.main(Main.java:141)

Can you please help me with this issues?
