### ISSUE TITLE
How can I process all .jimple file in some directories to generate a call graph?

### ISSUE THREAD

**Issue by buriedpot** [soot-oss/soot#1792]
I store many .jimple files in some directories. And I need to just read all the .jimple files to generate a call graph. Is this possible? I tried to execute soot.Main.main in the code, and the key parameters set as follows:

```cmd
-src-prec jimple
-process-dir jimpleDir1
-process-dir jimpleDir2
```
and jimpleDir* is where the .jimple files are stored:
![image](https://user-images.githubusercontent.com/38457801/141517331-3dbb36be-15bd-4f86-bd66-618bcfd7034d.png)

But two errors occur during execution:
![image](https://user-images.githubusercontent.com/38457801/141517390-939c7009-f8c6-42ac-857f-47b9b021b131.png)
```cmd
[INFO] use soot to output Jimple for groupA:A:1.0
Soot started on Sat Nov 13 02:33:28 CST 2021
soot.CompilationDeathException: Couldn't resolve classpath entry C:\Users\buriedpot\.m2\JimpleBuffer\groupA\A\1.0\JimpleBuf\;C:\env\Java\jdk1.8.0_144\jre\lib\rt.jar: java.io.IOException: 文件名、目录名或卷标语法不正确。
	at soot.SourceLocator.explodeClassPath(SourceLocator.java:168)
	at soot.SourceLocator.getClassSource(SourceLocator.java:179)
	at soot.Scene.tryLoadClass(Scene.java:1030)
	at soot.Scene.loadBasicClasses(Scene.java:1744)
	at soot.Scene.loadNecessaryClasses(Scene.java:1849)
	at soot.Main.run(Main.java:241)
	at soot.Main.main(Main.java:141)
	at neu.lab.conflict.soot.SootGenJimple.readJimple(SootGenJimple.java:64)
	at neu.lab.conflict.soot.SootGenJimple.inputJimples(SootGenJimple.java:80)
	at neu.lab.conflict.readJimpleTest.run(readJimpleTest.java:31)
	at neu.lab.conflict.ConflictMojo.execute(ConflictMojo.java:562)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)


Ouuups... something went wrong! Sorry about that.
Follow these steps to fix the problem:
1.) Are you sure you used the right command line?
    Click here to double-check:
    https://github.com/soot-oss/soot/wiki/Options-and-JavaDoc

2.) Not sure whether it's a bug? Feel free to discuss
    the issue on the Soot mailing list:
    https://github.com/soot-oss/soot/wiki/Getting-help

3.) Sure it's a bug? Click this link to report it.
    https://github.com/soot-oss/soot/issues/new?title=soot.CompilationDeathException+when+...&body=Steps+to+reproduce%3A%0A1.%29+...%0A%0AFiles+used+to+reproduce%3A+%0A...%0A%0ASoot+version%3A+%3Cpre%3Etrunk%3C%2Fpre%3E%0A%0ACommand+line%3A%0A%3Cpre%3E-src-prec+jimple+-ire+-allow-phantom-refs+-ignore-resolving-levels+-w+-p+wjpp+off+-p+wspp+off+-p+wstp+off+-p+wsop+off+-p+wjop+off+-p+wjap+off+-p+shimple+off+-p+stp+off+-p+sop+off+-p+jtp+off+-p+jop+off+-p+jap+off+-p+gb+off+-p+gop+off+-p+bb+off+-p+bop+off+-p+tag+off+-p+db+off+-f+n+-process-dir+C%3A%5CUsers%5Cburiedpot%5C.m2%5CJimpleBuffer%5CgroupA%5CA%5C1.0%5CJimpleBuf%5C%3C%2Fpre%3E%0A%0AMax+Memory%3A%0A%3Cpre%3E3611MB%3C%2Fpre%3E%0A%0AStack+trace%3A%0A%3Cpre%3Esoot.CompilationDeathException%3A+Couldn%26%2339%3Bt+resolve+classpath+entry+C%3A%5CUsers%5Cburiedpot%5C.m2%5CJimpleBuffer%5CgroupA%5CA%5C1.0%5CJimpleBuf%5C%3BC%3A%5Cenv%5CJava%5Cjdk1.8.0_144%5Cjre%5Clib%5Crt.jar%3A+java.io.IOException%3A+%E6%96%87%E4%BB%B6%E5%90%8D%E3%80%81%E7%9B%AE%E5%BD%95%E5%90%8D%E6%88%96%E5%8D%B7%E6%A0%87%E8%AF%AD%E6%B3%95%E4%B8%8D%E6%AD%A3%E7%A1%AE%E3%80%82%0D%0A%09at+soot.SourceLocator.explodeClassPath%28SourceLocator.java%3A168%29%0D%0A%09at+soot.SourceLocator.getClassSource%28SourceLocator.java%3A179%29%0D%0A%09at+soot.Scene.tryLoadClass%28Scene.java%3A1030%29%0D%0A%09at+soot.Scene.loadBasicClasses%28Scene.java%3A1744%29%0D%0A%09at+soot.Scene.loadNecessaryClasses%28Scene.java%3A1849%29%0D%0A%09at+soot.Main.run%28Main.java%3A241%29%0D%0A%09at+soot.Main.main%28Main.java%3A141%29%0D%0A%09at+neu.lab.conflict.soot.SootGenJimple.readJimple%28SootGenJimple.java%3A64%29%0D%0A%09at+neu.lab.conflict.soot.SootGenJimple.inputJimples%28SootGenJimple.java%3A80%29%0D%0A%09at+neu.lab.conflict.readJimpleTest.run%28readJimpleTest.java%3A31%29%0D%0A%09at+neu.lab.conflict.ConflictMojo.execute%28ConflictMojo.java%3A562%29%0D%0A%09at+org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo%28DefaultBuildPluginManager.java%3A137%29%0D%0A%09at+org.apache.maven.lifecycle.internal.MojoExecutor.execute%28MojoExecutor.java%3A210%29%0D%0A%09at+org.apache.maven.lifecycle.internal.MojoExecutor.execute%28MojoExecutor.java%3A156%29%0D%0A%09at+org.apache.maven.lifecycle.internal.MojoExecutor.execute%28MojoExecutor.java%3A148%29%0D%0A%09at+org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject%28LifecycleModuleBuilder.java%3A117%29%0D%0A%09at+org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject%28LifecycleModuleBuilder.java%3A81%29%0D%0A%09at+org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build%28SingleThreadedBuilder.java%3A56%29%0D%0A%09at+org.apache.maven.lifecycle.internal.LifecycleStarter.execute%28LifecycleStarter.java%3A128%29%0D%0A%09at+org.apache.maven.DefaultMaven.doExecute%28DefaultMaven.java%3A305%29%0D%0A%09at+org.apache.maven.DefaultMaven.doExecute%28DefaultMaven.java%3A192%29%0D%0A%09at+org.apache.maven.DefaultMaven.execute%28DefaultMaven.java%3A105%29%0D%0A%09at+org.apache.maven.cli.MavenCli.execute%28MavenCli.java%3A957%29%0D%0A%09at+org.apache.maven.cli.MavenCli.doMain%28MavenCli.java%3A289%29%0D%0A%09at+org.apache.maven.cli.MavenCli.main%28MavenCli.java%3A193%29%0D%0A%09at+sun.reflect.NativeMethodAccessorImpl.invoke0%28Native+Method%29%0D%0A%09at+sun.reflect.NativeMethodAccessorImpl.invoke%28NativeMethodAccessorImpl.java%3A62%29%0D%0A%09at+sun.reflect.DelegatingMethodAccessorImpl.invoke%28DelegatingMethodAccessorImpl.java%3A43%29%0D%0A%09at+java.lang.reflect.Method.invoke%28Method.java%3A498%29%0D%0A%09at+org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced%28Launcher.java%3A282%29%0D%0A%09at+org.codehaus.plexus.classworlds.launcher.Launcher.launch%28Launcher.java%3A225%29%0D%0A%09at+org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode%28Launcher.java%3A406%29%0D%0A%09at+org.codehaus.plexus.classworlds.launcher.Launcher.main%28Launcher.java%3A347%29%0D%0A%09at+org.codehaus.classworlds.Launcher.main%28Launcher.java%3A47%29%0D%0A%3C%2Fpre%3E
    Please be as precise as possible when giving us
    information on how to reproduce the problem. Thanks!

```

So is my operation wrong?

**Comment by buriedpot** [comment]
The jimpleDir shown in the figure has a concrete name C:\buriedpot\....\jimpleBuf. This is not the point.
