### ISSUE TITLE
java.lang.RuntimeException when ...

### ISSUE THREAD

**Issue by hunie-son** [soot-oss/soot#1794]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: <pre>trunk</pre>

Command line:
<pre>soot.Main -cp . -w -android-jars /usr/lib/android-sdk/ -src-prec apk -f jimple -process-multiple-dex Twitter_v9.11.0-release.00_apkpure.com.apk</pre>

Max Memory:
<pre>496MB</pre>

Stack trace:
<pre>java.lang.RuntimeException: None of the basic classes could be loaded! Check your Soot class path!
	at soot.Scene.loadBasicClasses(Scene.java:1755)
	at soot.Scene.loadNecessaryClasses(Scene.java:1845)
	at soot.Main.run(Main.java:241)
	at soot.Main.main(Main.java:141)
</pre>

**Comment by jpstotz** [comment]
Your `android-jars` parameter is wrong. Soot can not make use of Android SDK, instead it expects a directory like the `platforms`  folder within Android-SDK:

```
android-jars-path/
    android--1/
       android.jar <- this one is the default jar used if the target API can not be determined
    ...
    android-28/
        android.jar
    android-29/
        android.jar
    android-30/
        android.jar
    ...
```

Once there was a github project which contained all the necessary andorid.jar files for all API versions, but now I can not find it anymore.
