### ISSUE TITLE
Verifier error from Soot generated code

### ISSUE THREAD

**Issue by bdemsky** [soot-oss/soot#1810]
We're instrumenting code in Soot v 4.1.0 and the generated bytecode doesn't pass the verifier.  It looks to be a subtle difference in the way the verifier analyzes exception control flow vs how the Soot LocalPacker pass analyzes control flow.  It looks like to me that  LocalPacker realizes that a certain path through the CFG is unrealizable and reuses the slot for two different types.  The java verifier is less precise, and believes there is a path that has a type violation.

The error we get is:
Exception in thread "main" java.lang.VerifyError: (class: test/Example, method: abort signature: (Lcommon/SyncBlockKey;)V) Register 2 contains wrong type
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:650)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:632)

I'm attaching a simplified version of the original java source for the bug revealingd program, the transformed jimple code, a run of the ASM verifier on the byte code, and the byte code from javap for the transformed program.
[Example.ASM_VERIFIER.txt](https://github.com/soot-oss/soot/files/7672328/Example.ASM_VERIFIER.txt)
[Example.bytecode.txt](https://github.com/soot-oss/soot/files/7672329/Example.bytecode.txt)
[Example.java.txt](https://github.com/soot-oss/soot/files/7672330/Example.java.txt)
[test.Example.jimple.txt](https://github.com/soot-oss/soot/files/7672332/test.Example.jimple.txt)

**Comment by bdemsky** [comment]
So I debugged this.  The issue is that ExceptionalUnitGraph does not consider the same set of exceptional flow edges that the JDK verifier does.  The JDK verifier considers that any byte code instruction in the range of the exception handler can go to the exception handler.  If there is a nested exception handler inside an outer exception handler that can handle an exception, the ExceptionalUnitGraph is more precise and does not consider that there is an exceptional edge from the bye code instruction to the outer handler.  This difference means that LocalPacker can occasionally pack locals in a way that does not pass the verifier.

**Comment by MarcMil** [comment]
I cannot reproduce this in the current version. That being said, I cannot reproduce it on 4.1.0 version either. I've tried compiling the Java file using openjdk8 and eclipse compiler and both times I could run soot's generated class files.
I think we should close this issue for now; if you encounter it again, please submit the original class file. It's nice to hav the output of javap and the asm verifier, but we could easier reproduce it using the class file, making sure we operate on the same input.

@StevenArzt  can you close this?
