### ISSUE TITLE
[java.util.ConcurrentModificationException]Caused by Collections.synchronizedList in SootClass

### ISSUE THREAD

**Issue by Zongyin-Hao** [soot-oss/soot#1811]
&ensp; &ensp; When I used soot to analyze andorid classes, I encountered a concurrency bug:
```
[Thread-13] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: Failed to apply jb to <com.ichi2.utils.JSONObject: java.lang.Object get(java.lang.String)>
java.lang.RuntimeException: Failed to apply jb to <com.ichi2.utils.JSONObject: java.lang.Object get(java.lang.String)>
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:2282)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:446)
	at soot.PackManager.lambda$retrieveAllBodies$2(PackManager.java:1252)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
	at soot.FastHierarchy.getSignaturePolymorphicMethod(FastHierarchy.java:932)
```
&ensp; &ensp; I tried debugging and found that it may be caused by `` List<SootMethod> methodList `` in ``soot.SootClass``.
&ensp; &ensp; According to ``soot.SootClass:679`` and ``soot.SootClass:700``(both are ``this.methodList = Collections.synchronizedList(new ArrayList<>());``), we can know that ``methodList`` is a `synchronizedList`.
&ensp; &ensp; However, ``synchronizedList`` can only guarantee the safety of ``reading`` and ``writing``, but not the safety of ``iteration``. 
&ensp; &ensp; This is the description of iterator in the ``synchronizedList``'s source code: 
```
public ListIterator<E> listIterator() {
    return list.listIterator(); // Must be manually synched by user
}

public ListIterator<E> listIterator(int index) {
    return list.listIterator(index); // Must be manually synched by user
}
```
&ensp; &ensp; So I replaced  ``synchronizedList`` with ``ConcurrentLinkedQueue``. After the modification, the concurrency bug is fixed.

**Comment by Zongyin-Hao** [comment]
I submitted a PR, I'd appreciate it if you can help check whether the modification is correct

**Comment by Zongyin-Hao** [comment]
I submitted a PR #1814 , I'd appreciate it if you can help check whether the modification is correct

**Comment by XYHyouKa** [comment]
I met this problem recently as well. And I also found that methodList is a synchronizedList.
The source code of ArrayList.java indicates that ConcurrentModificationException occurs if List is modified (e.g. add or remove operation) while iteration.
However, my codes have nothing to do with methodList itself. I just traverse the list, get or set members of some methods, but never modify the methodList. It confuses me a lot.

**Comment by MarcMil** [comment]
I was unable to recreate this issue with the current nightly.
