### ISSUE TITLE
java.lang.RuntimeException when ...

### ISSUE THREAD

**Issue by xuangestallone** [soot-oss/soot#1816]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: <pre>trunk</pre>

Command line:
<pre>soot.Main Employee</pre>

Max Memory:
<pre>976MB</pre>

Stack trace:
<pre>java.lang.RuntimeException: Error: cannot find rt.jar.
	at soot.Scene.defaultJavaClassPath(Scene.java:635)
	at soot.Scene.defaultClassPath(Scene.java:527)
	at soot.Scene.getSootClassPath(Scene.java:283)
	at soot.SourceLocator.getClassSource(SourceLocator.java:168)
	at soot.Scene.tryLoadClass(Scene.java:812)
	at soot.Scene.loadBasicClasses(Scene.java:1496)
	at soot.Scene.loadNecessaryClasses(Scene.java:1579)
	at soot.Main.run(Main.java:250)
	at soot.Main.main(Main.java:147)
</pre>

**Comment by SnoopyTlion** [comment]
Read this first, you need set your sootClassPath correctly. https://github.com/soot-oss/soot/wiki/Introduction:-Soot-as-a-command-line-tool#soots-classpath
