### ISSUE TITLE
java.lang.IllegalArgumentException when ...

### ISSUE THREAD

**Issue by rkaushik2001** [soot-oss/soot#1836]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: <pre>trunk</pre>

Command line:
<pre>-cp . -pp -f J Test</pre>

Max Memory:
<pre>2048MB</pre>

Stack trace:
<pre>java.lang.IllegalArgumentException: Unsupported class file major version 60
	at org.objectweb.asm.ClassReader.&#60;init&#62;(ClassReader.java:196)
	at org.objectweb.asm.ClassReader.&#60;init&#62;(ClassReader.java:177)
	at org.objectweb.asm.ClassReader.&#60;init&#62;(ClassReader.java:163)
	at org.objectweb.asm.ClassReader.&#60;init&#62;(ClassReader.java:284)
	at soot.asm.AsmClassSource.resolve(AsmClassSource.java:62)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:253)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:221)
	at soot.SootResolver.bringToSignatures(SootResolver.java:292)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:179)
	at soot.SootResolver.resolveClass(SootResolver.java:141)
	at soot.Scene.loadClass(Scene.java:1069)
	at soot.Scene.loadClassAndSupport(Scene.java:1054)
	at soot.Scene.loadNecessaryClass(Scene.java:1836)
	at soot.Scene.loadNecessaryClasses(Scene.java:1848)
	at soot.Main.run(Main.java:241)
	at soot.Main.main(Main.java:141)
</pre>

**Comment by caohch-1** [comment]
This is my first time to use Soot and I also meet this problem by running the command:
 `java -cp sootclasses-trunk-jar-with-dependencies.jar soot.Main -cp . -pp HelloWorld`
and then get the stack trace:
`java.lang.IllegalArgumentException: Unsupported class file major version 59...`

I use Soot in WSL of Win10 and my java version is as follows:
`openjdk version "11.0.10" 2021-01-19`
`OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)`
`OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)`

I solved this by compiling with an older **Project bytecode version** (i.e., 11).

I'm using IDEA and this option can be found in **File->Settings->Build, Execution, Deployment->Compiler->Java Compiler**.

I tested some different versions and found that Soot works well when **Project bytecode version<=13**.

**Comment by StevenArzt** [comment]
Soot uses third-party libraries that are compiled for recent Java versions. Consequently, Soot also requires these newer Java versions. File version 60 is Java 16. You can resolve the problem by installing a recent JDK version.
