### ISSUE TITLE
NullPointerException occurred when using soot command-line tool.

### ISSUE THREAD

**Issue by fade03** [soot-oss/soot#1848]
Hi, I have trouble when using soot 2.5.0 command-line tool to get `Jimple` from Java source file.

My Configuration and command line:
```
alias soot='java -jar ~/Public/Tools/soot-2.5.0.jar'
---------------------------------------------------
~/Desktop/WorkSpace/coding/Java/JavaStuff/src/main/java/framework/soot/guide/sample/
❯ soot -cp . -f J Foo

Exception in thread "main" java.lang.NullPointerException
        at soot.JastAddInitialResolver.resolveFromJavaFile(JastAddInitialResolver.java:103)
        at soot.JavaClassSource.resolve(JavaClassSource.java:57)
        at soot.SootResolver.bringToHierarchy(SootResolver.java:215)
        at soot.SootResolver.bringToSignatures(SootResolver.java:239)
        at soot.SootResolver.processResolveWorklist(SootResolver.java:154)
        at soot.SootResolver.resolveClass(SootResolver.java:124)
        at soot.Scene.loadClass(Scene.java:448)
        at soot.Scene.loadClassAndSupport(Scene.java:433)
        at soot.Scene.loadNecessaryClass(Scene.java:1053)
        at soot.Scene.loadNecessaryClasses(Scene.java:1067)
        at soot.Main.run(Main.java:167)
        at soot.Main.main(Main.java:141)

```

Foo.java:
```java
package framework.soot.guide.sample;

public class Foo {
    public static void main(String[] args) {
        Foo f = new Foo();
        int a = 7;
        int b = 14;
        int x = (f.bar(21) + a) * b;
    }

    public int bar(int n) {
        return n + 42;
    }
}
```

My platform are JDK8u302 and MacOS 12.3 arm64, tks.

**Comment by fade03** [comment]
I have solved this problem by building release Soot on my own machine.

```
alias soot='java -jar your-soot-path/target/sootclasses-trunk-jar-with-dependencies.jar'
```

It works now:

![0BB2EAA1A506107544668F215D6595E2](https://user-images.githubusercontent.com/66620626/159735821-20006c7c-74cf-4f1c-9c3f-a8335d5f3e79.jpg)

**Comment by jpstotz** [comment]
@F4ded For other people who have the same problem it may be good to mention which version/commit/branch/tag you have checked out for building.

**Comment by fade03** [comment]
> @F4ded For other people who have the same problem it may be good to mention which version/commit/branch/tag you have checked out for building.

Thank you for your reminder, I build the Soot with [Tag 4.2.1](https://github.com/soot-oss/soot/releases/tag/4.2.1)
