### ISSUE TITLE
JBCO primitive boxing error

### ISSUE THREAD

**Issue by nakhli** [soot-oss/soot#185]
Hello - I had a crash running JBCO on the followint example:

``` java
package bug;

public class Test {
    public static void main(final String[] args) throws Exception {
    }

    @Override
    public boolean equals(Object arg) {
        try {
            return super.equals(arg);
        } catch (Exception e) {
            return false;
        }
    }
}
```

command:

```
java -cp /path-to-soot-nightly/soot.jar soot.jbco.Main -cp ".:/path-to-jdk7/jre/lib/rt.jar:/path-to-jdk7/jre/lib/jce.jar" -t:9:wjtp.j
o_cr -t:9:wjtp.jbco_mr -t:9:wjtp.jbco_fr -t:9:wjtp.jbco_bapibm -t:9:wjtp.jbco_blbc -t:9:jtp.jbco_gia -t:9:jtp.jbco_adss -t:9:jtp.jbco_cae2bo -t:9:bb.jbco_cb2
 -t:9:bb.jbco_dcc -t:9:bb.jbco_rds -t:9:bb.jbco_riitcb -t:9:bb.jbco_iii -t:9:bb.jbco_plvb -t:9:bb.jbco_rlaii -t:9:bb.jbco_ctbcb -t:9:bb.jbco_ecvf -t:9:bb.jbc
ptss -debug -main-class bug.Test -app bug.Test
```

I get the following exception:

```
Whole Program Jimple Transformations:
        wjtp.mhp  default
        wjtp.tn  default
        wjtp.jbco_fr  JBCO
        wjtp.jbco_cc  JBCO
        wjtp.jbco_cr  JBCO
        wjtp.jbco_mr  JBCO
        wjtp.jbco_bapibm  JBCO
        wjtp.jbco_blbc  JBCO
Jimple Method Body Transformations:
        jtp.jbco_gia  JBCO
        jtp.jbco_adss  JBCO
        jtp.jbco_cae2bo  JBCO
        jtp.jbco_jl  JBCO
Baf Method Body Transformations:
        bb.jbco_j2bl  JBCO
        bb.jbco_cb2ji  JBCO
        bb.jbco_dcc  JBCO
        bb.jbco_rds  JBCO
        bb.jbco_riitcb  JBCO
        bb.jbco_iii  JBCO
        bb.jbco_plvb  JBCO
        bb.jbco_rlaii  JBCO
        bb.jbco_ctbcb  JBCO
        bb.jbco_ecvf  JBCO
        bb.jbco_ptss  JBCO
        bb.jbco_ful  JBCO
        bb.lso  default
        bb.pho  default
        bb.ule  default
        bb.lp  default
        bb.jbco_rrps  JBCO

Soot started on Thu Feb 27 12:20:14 CET 2014
[Call Graph] For information on where the call graph may be incomplete, use the verbose option to the cg phase.
Exception in thread "main" java.lang.RuntimeException: Box ImmediateBox(null) cannot contain value: (boolean) 0(class soot.jimple.internal.JCastExpr)
        at soot.AbstractValueBox.setValue(AbstractValueBox.java:42)
        at soot.jimple.internal.ImmediateBox.<init>(ImmediateBox.java:40)
        at soot.jimple.Jimple.newImmediateBox(Jimple.java:862)
        at soot.jimple.internal.JReturnStmt.<init>(JReturnStmt.java:47)
        at soot.jimple.Jimple.newReturnStmt(Jimple.java:672)
        at soot.jbco.jimpleTransformations.BuildIntermediateAppClasses.internalTransform(BuildIntermediateAppClasses.java:171)
        at soot.SceneTransformer.transform(SceneTransformer.java:39)
        at soot.Transform.apply(Transform.java:90)
        at soot.ScenePack.internalApply(ScenePack.java:43)
        at soot.Pack.apply(Pack.java:116)
        at soot.PackManager.runWholeProgramPacks(PackManager.java:540)
        at soot.PackManager.runPacksNormally(PackManager.java:443)
        at soot.PackManager.runPacks(PackManager.java:388)
        at soot.Main.run(Main.java:203)
        at soot.Main.main(Main.java:146)
        at soot.jbco.Main.main(Main.java:271)
```

**Comment by pavanupb** [comment]
Closed due to inactivity. Please re-open if still relevant.
