### ISSUE TITLE
soot.SootResolver$SootClassNotFoundException when ...

### ISSUE THREAD

**Issue by lvyahui8** [soot-oss/soot#1859]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: <pre>trunk</pre>

Command line:
<pre>-w -cp D:\work\http-proxy\test-server\lib -pp -process-dir D:\work\http-proxy\test-server\lib -process-jar-dir D:\work\http-proxy\test-server\lib -main-class org.lyh.http.proxy.client.TestClientApp org.lyh.http.proxy.client.TestClientApp</pre>

Max Memory:
<pre>3499MB</pre>

Stack trace:
<pre>soot.SootResolver$SootClassNotFoundException: couldn&#39;t find class: org.lyh.http.proxy.client.TestClientApp (is your soot-class-path set properly?)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:264)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:240)
	at soot.SootResolver.bringToSignatures(SootResolver.java:310)
	at soot.SootResolver.bringToBodies(SootResolver.java:350)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:187)
	at soot.SootResolver.resolveClass(SootResolver.java:152)
	at soot.Scene.loadClass(Scene.java:1004)
	at soot.Scene.loadClassAndSupport(Scene.java:991)
	at soot.Scene.loadNecessaryClass(Scene.java:1796)
	at soot.Scene.loadNecessaryClasses(Scene.java:1808)
	at soot.Main.run(Main.java:254)
	at soot.Main.main(Main.java:142)
	at io.github.lvyahui8.owlet.SootCallGraphTest.main(SootCallGraphTest.java:51)
</pre>

![image](https://user-images.githubusercontent.com/9465195/164873041-6afb9b17-760f-478c-89fc-465a03f0ecad.png)

**Comment by jpstotz** [comment]
Your screen shot shows hat `TestClientApp` is a Java source code but your class path only contains the `test-server\lib` folder. 

Class files of compiled Java source code usually is saved in the `target/classes` (Maven) or `build/classes/java` (Gradle) directory. If you don't add the directory where the compiled class files are located Soot can not find it.
