### ISSUE TITLE
JBCO  Error @this-assignment statement should precede all other statements

### ISSUE THREAD

**Issue by nakhli** [soot-oss/soot#186]
Hello

I get an exception with the following example:

``` java
public class Test extends ClassLoader {

    public static void main(final String[] args) { }

    @Override
    public Class loadClass(String name) throws ClassNotFoundException {
        return null;
    }
}
```

command:

java -cp /path-to-soot-nightly/soot.jar soot.jbco.Main -cp ".:/path-to-jdk7/jre/lib/rt.jar:/path-to-jdk7/jre/lib/jce.jar" -t:9:wjtp.j
o_cr -t:9:wjtp.jbco_mr -t:9:wjtp.jbco_fr -t:9:wjtp.jbco_bapibm -t:9:wjtp.jbco_blbc -t:9:jtp.jbco_gia -t:9:jtp.jbco_adss -t:9:jtp.jbco_cae2bo -t:9:bb.jbco_cb2
 -t:9:bb.jbco_dcc -t:9:bb.jbco_rds -t:9:bb.jbco_riitcb -t:9:bb.jbco_iii -t:9:bb.jbco_plvb -t:9:bb.jbco_rlaii -t:9:bb.jbco_ctbcb -t:9:bb.jbco_ecvf -t:9:bb.jbc
ptss -debug -main-class bug.Test -app bug.Test

output:

```
Whole Program Jimple Transformations:
        wjtp.mhp  default
        wjtp.tn  default
        wjtp.jbco_fr  JBCO
        wjtp.jbco_cc  JBCO
        wjtp.jbco_cr  JBCO
        wjtp.jbco_mr  JBCO
        wjtp.jbco_bapibm  JBCO
        wjtp.jbco_blbc  JBCO
Jimple Method Body Transformations:
        jtp.jbco_gia  JBCO
        jtp.jbco_adss  JBCO
        jtp.jbco_cae2bo  JBCO
        jtp.jbco_jl  JBCO
Baf Method Body Transformations:
        bb.jbco_j2bl  JBCO
        bb.jbco_cb2ji  JBCO
        bb.jbco_dcc  JBCO
        bb.jbco_rds  JBCO
        bb.jbco_riitcb  JBCO
        bb.jbco_iii  JBCO
        bb.jbco_plvb  JBCO
        bb.jbco_rlaii  JBCO
        bb.jbco_ctbcb  JBCO
        bb.jbco_ecvf  JBCO
        bb.jbco_ptss  JBCO
        bb.jbco_ful  JBCO
        bb.lso  default
        bb.pho  default
        bb.ule  default
        bb.lp  default
        bb.jbco_rrps  JBCO

Soot started on Thu Feb 27 16:04:48 CET 2014
[Call Graph] For information on where the call graph may be incomplete, use the verbose option to the cg phase.
Transforming bug.Test...
Transforming bug.ll1Il...
Exception in thread "main" java.lang.RuntimeException: @this-assignment statement should precede all other statements
 method: <bug.ll1Il: java.lang.Class $$$5$(java.lang.String)>
 body:
    public java.lang.Class $$$5$(java.lang.String) throws java.lang.ClassNotFoundException
    {
        java.lang.String l0;
        bug.ll1Il ths;

        l0 := @parameter0: java.lang.String;
        ths := @this: bug.ll1Il;
        return null;
    }

        at soot.jimple.JimpleBody.validateIdentityStatements(JimpleBody.java:157)
        at soot.jimple.JimpleBody.validate(JimpleBody.java:73)
        at soot.baf.BafBody.<init>(BafBody.java:66)
        at soot.baf.Baf.newBody(Baf.java:560)
        at soot.PackManager.convertJimpleBodyToBaf(PackManager.java:956)
        at soot.PackManager.runBodyPacks(PackManager.java:916)
        at soot.PackManager.runBodyPacks(PackManager.java:584)
        at soot.PackManager.runBodyPacks(PackManager.java:487)
        at soot.PackManager.runPacksNormally(PackManager.java:464)
        at soot.PackManager.runPacks(PackManager.java:388)
        at soot.Main.run(Main.java:203)
        at soot.Main.main(Main.java:146)
        at soot.jbco.Main.main(Main.java:271)
```

**Comment by stiv-yakovenko** [comment]
So, is jbco deprecated or working? May be if it is not working, you can tell date in the past, when it was working?
