### ISSUE TITLE
java.lang.RuntimeException when ...

### ISSUE THREAD

**Issue by ervikas** [soot-oss/soot#1866]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: <pre>trunk</pre>

Command line:
<pre>-force-android-jar /Users/vikasm/Library/Android/sdk/platforms/android-22/android.jar -process-dir /Users/vikasm/Desktop/benign_sg/sg.gov.app.mol_v1.7.8_apkpure.com.apk -ire -pp -keep-line-number -allow-phantom-refs -src-prec apk -w -d output_files/ic3_output/testspace/sg.gov.app.mol_v1.7.8_apkpure.com.apk</pre>

Max Memory:
<pre>7282MB</pre>

Stack trace:
<pre>java.lang.RuntimeException: Invalid argument type for div
	at soot.baf.JasminClass$1$12.defaultCase(JasminClass.java:1482)
	at soot.TypeSwitch.caseRefType(TypeSwitch.java:76)
	at soot.RefType.apply(RefType.java:156)
	at soot.baf.JasminClass$1.emitOpTypeInst(JasminClass.java:1435)
	at soot.baf.JasminClass$1.caseAndInst(JasminClass.java:1520)
	at soot.baf.internal.BAndInst.apply(BAndInst.java:74)
	at soot.baf.JasminClass.emitInst(JasminClass.java:317)
	at soot.baf.JasminClass.emitMethodBody(JasminClass.java:251)
	at soot.AbstractJasminClass.emitMethod(AbstractJasminClass.java:769)
	at soot.AbstractJasminClass.&#60;init&#62;(AbstractJasminClass.java:648)
	at soot.baf.JasminClass.&#60;init&#62;(JasminClass.java:78)
	at soot.PackManager.writeClass(PackManager.java:1126)
	at soot.PackManager.access$100(PackManager.java:139)
	at soot.PackManager$2.run(PackManager.java:678)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
</pre>

**Comment by MarcMil** [comment]
Jasmin is no longer used, please retry on the newest nightly version of Soot. It should work much better now.
