### ISSUE TITLE
java.lang.NullPointerException when ...

### ISSUE THREAD

**Issue by NiguXNick** [soot-oss/soot#1873]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: <pre>trunk</pre>

Command line:
<pre>-process-dir /home/nicolas/Downloads/SimiDroid-master/artefacts/apps/686bbfc5d0bf9708f113bbb5d378363a9f43db4ec172dd0cc7a496f287581799.apk -android-jars /home/nicolas/Documentos/android-platforms -ire -pp -allow-phantom-refs -w -p cg enabled:false</pre>

Max Memory:
<pre>7962MB</pre>

Stack trace:
<pre>java.lang.NullPointerException
	at soot.JastAddJ.Program.initPaths(Program.java:350)
	at soot.SootResolver.&#60;init&#62;(SootResolver.java:88)
	at soot.Singletons.soot_SootResolver(Singletons.java:1857)
	at soot.SootResolver.v(SootResolver.java:93)
	at soot.Scene.tryLoadClass(Scene.java:773)
	at soot.Scene.loadBasicClasses(Scene.java:1434)
	at soot.Scene.loadNecessaryClasses(Scene.java:1513)
	at soot.Main.run(Main.java:243)
	at soot.Main.main(Main.java:147)
	at lu.uni.snt.simidroid.plugin.method.MethodFeatureExtraction.extract(MethodFeatureExtraction.java:38)
	at lu.uni.snt.simidroid.TestApps.SimiDroidClient4PW.compare(SimiDroidClient4PW.java:62)
	at lu.uni.snt.simidroid.TestApps.SimiDroidClient4PW.start(SimiDroidClient4PW.java:37)
	at lu.uni.snt.simidroid.TestApps.SimiDroidClient.main(SimiDroidClient.java:48)
</pre>

**Comment by MarcMil** [comment]
JastAddJ is now being unmaintained. Use the bytecode backend in the future instead.
