### ISSUE TITLE
Java new versions suppots

### ISSUE THREAD

**Issue by darioamorosodaragona-tuni** [soot-oss/soot#1878]
Is soot still maintained? Are there any plans to add support for the new versions of Java? I use soot on my project, but I need to upgrade my project from Java 9 to the new version, so I would like to understand if there is some idea about upgrading soot or not.

**Comment by StevenArzt** [comment]
Soot supports newer Java versions. What are your concrete issues with newer Java versions?

**Comment by darioamorosodaragona-tuni** [comment]
Does Soot support Java 18? On readme is specified Java 9.

**Comment by StevenArzt** [comment]
Soot should be able to run on Java 18, and it should be able to process Java classes compiled for Java 9. Concerning the README file, note that there was a major change between Java 8 and 9, so this should be 9+ to indicate the support for the class filesystem and modules introduced with Java 9.

**Comment by darioamorosodaragona-tuni** [comment]
Ok, this is the key point: could soot analyze classes compiled for the new Java version (Java 17-18)?

**Comment by StevenArzt** [comment]
Yes.

**Comment by darioamorosodaragona-tuni** [comment]
Trying to analyze Java 18 projects I got this error: `Provider "jrt" not installed. `

On a mac my soot classpath is set as follows: 

`VIRTUAL_FS_FOR_JDK:/Library/Java/JavaVirtualMachines/jdk-18.0.1.1.jdk/Contents/Home/lib/jrt-fs.jar:/Users/ncdaam/IdeaProjects/demo1/lib:`

Also if I set it as follows i got the same error: 

`VIRTUAL_FS_FOR_JDK:/Library/Java/JavaVirtualMachines/jdk-18.0.1.1.jdk/Contents/Home/lib/jrt-fs.jar` 

Where I'm wrong?

The project analyzed does not contain modules.

**Comment by StevenArzt** [comment]
Do you run Soot on Java 18 as well?

**Comment by darioamorosodaragona-tuni** [comment]
No. I'm running Soot on Java 1.8.

**Comment by StevenArzt** [comment]
That doesn't work. If you want to analyze newer Java code, you need to run Soot on a newer Java version as well.

**Comment by darioamorosodaragona-tuni** [comment]
Ok, thanks.

**Comment by darioamorosodaragona-tuni** [comment]
Now I run soot on Java 18 and I analyze Java 18 project getting this error:

```
Exception in thread "main" java.lang.IllegalArgumentException: Unsupported class file major version 62
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:284)
	at soot.asm.AsmClassSource.resolve(AsmClassSource.java:62)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:253)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:221)
	at soot.SootResolver.bringToSignatures(SootResolver.java:292)
	at soot.SootResolver.bringToBodies(SootResolver.java:332)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:171)
	at soot.SootResolver.resolveClass(SootResolver.java:141)
	at soot.Scene.tryLoadClass(Scene.java:1042)
	at soot.Scene.loadBasicClasses(Scene.java:1744)
	at soot.Scene.loadNecessaryClasses(Scene.java:1845)
	at CATTO.project.Project.<init>(Project.java:76)
	at CATTO.project.PreviousProject.<init>(PreviousProject.java:13)
	at CATTO.main.Main.main(Main.java:55)
```

I'm using Java 18.0.1.

**Comment by StevenArzt** [comment]
I'm not quite sure which Soot version you are using. The current ``develop`` branch compiles against ASM 9.2, which has the following check:

```
if (checkClassVersion && readShort(classFileOffset + 6) > Opcodes.V18) {
  throw new IllegalArgumentException(
     "Unsupported class file major version " + readShort(classFileOffset + 6));
}
```

V18 means 62, so you should be fine. Maybe you can set a breakpoint inside ASM to figure out what's going on.

**Comment by natasha-jeppu** [comment]
@darioamorosodaragona-tuni I am getting the same error. Did you manage to resolve this?
Java version: 18.0.1
Soot version: soot-4.3.0
System: Mac M1

**Comment by MarcMil** [comment]
@natasha-jeppu  @darioamorosodaragona-tuni 
If you encounter this problem, use ```-verbose:class``` in the JVM launch configuration to get further information on what version of ASM you are **actually** using. As Steven said, it's likely not Soot's fault.
