### ISSUE TITLE
OOM errors with soot 4.3.0

### ISSUE THREAD

**Issue by magg** [soot-oss/soot#1885]
I recently upgraded to soot 4.3.0 and I am hitting these OOM errors, any idea how too debug them

```
[Step 1/1] Caused by: com.protectoria.pss.routine.service.dex.exceptions.ObfuscationException: Soot obfuscation process exited with code 1. And message: 
[Step 1/1] Exception in thread "main" java.lang.RuntimeException: Failed to apply jb to <android.view.accessibility.AccessibilityRecord: void setSource(android.view.View)>
[Step 1/1] 	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:2282)
[Step 1/1] 	at soot.SootMethod.retrieveActiveBody(SootMethod.java:446)
[Step 1/1] 	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processNewMethod(OnFlyCallGraphBuilder.java:791)
[Step 1/1] 	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processReachables(OnFlyCallGraphBuilder.java:287)
[Step 1/1] 	at soot.jimple.toolkits.callgraph.CallGraphBuilder.build(CallGraphBuilder.java:108)
[Step 1/1] 	at soot.jimple.toolkits.callgraph.CHATransformer.internalTransform(CHATransformer.java:54)
[Step 1/1] 	at soot.SceneTransformer.transform(SceneTransformer.java:36)
[Step 1/1] 	at soot.Transform.apply(Transform.java:105)
[Step 1/1] 	at soot.RadioScenePack.internalApply(RadioScenePack.java:64)
[Step 1/1] 	at soot.jimple.toolkits.callgraph.CallGraphPack.internalApply(CallGraphPack.java:61)
[Step 1/1] 	at soot.Pack.apply(Pack.java:118)
[Step 1/1] 	at soot.PackManager.runWholeProgramPacks(PackManager.java:619)
[Step 1/1] 	at soot.PackManager.runPacksNormally(PackManager.java:500)
[Step 1/1] 	at soot.PackManager.runPacks(PackManager.java:425)
[Step 1/1] 	at com.protectoria.pss.routine.service.dex.codegen.obfuscation.soot.SootProcess.main(SootProcess.java:144)
[Step 1/1] Caused by: java.lang.OutOfMemoryError: Java heap space
[Step 1/1] 	at soot.toolkits.scalar.FlowAnalysis$Orderer.visitEntry(FlowAnalysis.java:237)
[Step 1/1] 	at soot.toolkits.scalar.FlowAnalysis$Orderer.newUniverse(FlowAnalysis.java:185)
[Step 1/1] 	at soot.toolkits.scalar.FlowAnalysis.doAnalysis(FlowAnalysis.java:531)
[Step 1/1] 	at soot.toolkits.scalar.ForwardFlowAnalysis.doAnalysis(ForwardFlowAnalysis.java:46)
[Step 1/1] 	at soot.toolkits.scalar.SimpleLocalDefs$FlowAssignment.<init>(SimpleLocalDefs.java:169)
[Step 1/1] 	at soot.toolkits.scalar.SimpleLocalDefs.init(SimpleLocalDefs.java:410)
[Step 1/1] 	at soot.toolkits.scalar.SimpleLocalDefs.<init>(SimpleLocalDefs.java:342)
[Step 1/1] 	at soot.toolkits.scalar.SimpleLocalDefs.<init>(SimpleLocalDefs.java:326)
[Step 1/1] 	at soot.toolkits.scalar.SimpleLocalDefs.<init>(SimpleLocalDefs.java:322)
[Step 1/1] 	at soot.toolkits.scalar.LocalDefsFactory.newLocalDefs(LocalDefsFactory.java:103)
[Step 1/1] 	at soot.toolkits.scalar.LocalSplitter.internalTransform(LocalSplitter.java:112)
[Step 1/1] 	at soot.BodyTransformer.transform(BodyTransformer.java:47)
[Step 1/1] 	at soot.Transform.apply(Transform.java:126)
[Step 1/1] 	at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:65)
[Step 1/1] 	at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:112)
[Step 1/1] 	at soot.Pack.apply(Pack.java:126)
[Step 1/1] 	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:2280)
[Step 1
```

**Comment by jpstotz** [comment]
So you have only upgraded soot (and it's dependencies) but Java and the other libraries are unchanged as well as the launch-config? Also is the app/program you analyze the same? Different apps of same code size can have totally different memory requirements for CHA call graph.

You can try to monitor memory usage over time of soot while running e.g. using [VisualVM](https://visualvm.github.io/) or Java MissionControl (jmc, usually included in OpenJDK installation).
Compare one run using the old soot version and one with the new soot version analyzing the same program/app.
