### ISSUE TITLE
java.lang.RuntimeException when try to generate a jimple file

### ISSUE THREAD

**Issue by Squirre17** [soot-oss/soot#1913]
Steps to reproduce:
1.) write a Test.java
```java
public class Test {
    public String foo(String s1, String s2){
        return s1 + " " + s2;
    }
    public static void main(String[] args) {
        Test t = new Test();
        System.out.println(t.foo("Hello","World"));
    }
}
```
and compile it, then run `java -cp sootclasses-trunk-jar-with-dependencies.jar soot.Main -cp . -pp Test -f jimple -d ./sootOutput`

Java version: <pre> ` java --version java 11.0.16 2022-07-19 LTS` </pre>

Soot version: <pre>trunk</pre>

Command line:
<pre>-cp . -pp Test -f jimple -d ./sootOutput</pre>

Max Memory:
<pre>3984MB</pre>

Stack trace:
<pre>java.lang.RuntimeException: Failed to convert &#60;Test: java.lang.String foo(java.lang.String,java.lang.String)&#62;
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:2163)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:402)
	at soot.PackManager$1.run(PackManager.java:1279)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: java.lang.invoke.StringConcatFactory was not found on classpath.
	at soot.asm.AsmMethodSource.getClassFromScene(AsmMethodSource.java:374)
	at soot.asm.AsmMethodSource.toSootMethodRef(AsmMethodSource.java:1571)
	at soot.asm.AsmMethodSource.convertInvokeDynamicInsn(AsmMethodSource.java:1459)
	at soot.asm.AsmMethodSource.convert(AsmMethodSource.java:1909)
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:2161)
	... 5 more
</pre>

**Comment by MarcMil** [comment]
Cannot reproduce the bug with the current nightly and Java 11.
