### ISSUE TITLE
java.lang.RuntimeException when ...

### ISSUE THREAD

**Issue by HFA22SCM36R** [soot-oss/soot#1914]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: <pre>trunk</pre>

Command line:
<pre>-w -allow-phantom-refs -android-jars /mnt/c/Users/harsh/Desktop/andriod-platforms/ -src-prec apk -process-multiple-dex -process-dir /home/labss /mnt/c/Users/harsh/Desktop/demo.apk -output-dir /mnt/c/Users/harsh/Desktop/test -output-format d -dump-cfg ALL</pre>

Max Memory:
<pre>1783MB</pre>

Stack trace:
<pre>java.lang.RuntimeException: no apk file given
	at soot.Scene.defaultAndroidClassPath(Scene.java:646)
	at soot.Scene.defaultClassPath(Scene.java:585)
	at soot.Scene.getSootClassPath(Scene.java:310)
	at soot.SourceLocator.getClassSource(SourceLocator.java:179)
	at soot.Scene.tryLoadClass(Scene.java:967)
	at soot.Scene.loadBasicClasses(Scene.java:1708)
	at soot.Scene.loadNecessaryClasses(Scene.java:1807)
	at soot.Main.run(Main.java:241)
	at soot.Main.main(Main.java:141)
</pre>

**Comment by cshezhang** [comment]
Seems an incorrect -process-dir arguemnt
