### ISSUE TITLE
soot.SootResolver$SootClassNotFoundException when ...

### ISSUE THREAD

**Issue by hktalent** [soot-oss/soot#1925]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: <pre>trunk</pre>

Command line:
<pre>-cp .:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/rt.jar -pp -f J -process-dir ./ -d ../out</pre>

Max Memory:
<pre>7282MB</pre>

Stack trace:
<pre>soot.SootResolver$SootClassNotFoundException: couldn&#39;t find class: com.sun.jdi.VirtualMachine (is your soot-class-path set properly?)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:245)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:221)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:182)
	at soot.SootResolver.resolveClass(SootResolver.java:141)
	at soot.Scene.loadClass(Scene.java:1069)
	at soot.Scene.loadClassAndSupport(Scene.java:1054)
	at soot.Scene.loadNecessaryClasses(Scene.java:1861)
	at soot.Main.run(Main.java:241)
	at soot.Main.main(Main.java:141)
</pre>

**Comment by jpstotz** [comment]
`com.sun.jdi.VirtualMachine` is a proprietary class that is not part of the standard Java runtime. It is included in `tools.jar` which you have not included in your class-path. I assume this is the main reason for your problem.

**Comment by hktalent** [comment]
ok, thanks
