### ISSUE TITLE
Can Soot analyze multi-threaded application, if so, can you please refer me to a related resource?

### ISSUE THREAD

**Issue by omarjarkas1997** [soot-oss/soot#1934]
Hello,

I developed a small CHA Soot tool that plots the Call Graph. The tools work fine on single-threaded applications. Yet, when I introduce a multi-thread application to be plotted, I get the below error. 

`
Exception in thread "main" java.lang.RuntimeException: Could not load classfile: 
	at soot.coffi.Util.resolveFromClassFile(Util.java:75)
	at soot.CoffiClassSource.resolve(CoffiClassSource.java:39)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:215)
	at soot.SootResolver.bringToSignatures(SootResolver.java:239)
	at soot.SootResolver.bringToBodies(SootResolver.java:280)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:150)
	at soot.SootResolver.resolveClass(SootResolver.java:124)
	at soot.Scene.loadClass(Scene.java:448)
	at soot.Scene.loadClassAndSupport(Scene.java:433)
	at soot.Scene.loadNecessaryClass(Scene.java:1053)
	at soot.Scene.loadNecessaryClasses(Scene.java:1067)
	at soot.Main.run(Main.java:167)
	at soot.Main.main(Main.java:141)
	at Main.main(Main.java:219)
`

I know it is a multi-threading error since the same application works when I extract the concurrency from it. Can Soot be used to analyze multi-threaded applications, if so, can someone please refer me to related articles since I'm assuming it doesn't out-of-the-box?

Thank you

**Comment by MarcMil** [comment]
Coffi isn't used anymore, we use ASM now. Please try again with a current soot version if you are still interested.
Whether the application being analyzed is multi threaded or not does not impact the loading of classes itself. So yes, Soot can be used to analyze multithreaded applications.
Note that with multi threaded applications, the call graph may be potentially imprecise, but this is not your problem. Rather this seems to be a problem with the old loading code of soot.
