### ISSUE TITLE
soot.toDex.DexPrinterException when ...

### ISSUE THREAD

**Issue by wufenglincheng** [soot-oss/soot#1945]
Soot version: <pre>trunk</pre>

Command line:
<pre>-w -allow-phantom-refs -android-jars /Users/darker/Library/Android/sdk/platforms -process-multiple-dex -process-dir /Users/darker/Desktop/hookapk/app-debug-1.apk</pre>

Max Memory:
<pre>18432MB</pre>

Stack trace:
<pre>soot.toDex.DexPrinterException: Error while processing method &#60;com.example.myapplication.TestView: void LJII(java.lang.String)&#62;
	at soot.toDex.DexPrinter.toMethods(DexPrinter.java:1078)
	at soot.toDex.DexPrinter.addAsClassDefItem(DexPrinter.java:660)
	at soot.toDex.DexPrinter.add(DexPrinter.java:1685)
	at soot.PackManager.writeClass(PackManager.java:1073)
	at soot.PackManager.lambda$writeOutput$1(PackManager.java:706)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: not found: [0..1]
	at soot.toDex.PrimitiveType.getByName(PrimitiveType.java:46)
	at soot.toDex.ExprVisitor.castPrimitive(ExprVisitor.java:668)
	at soot.toDex.ExprVisitor.caseCastExpr(ExprVisitor.java:636)
	at soot.jimple.internal.AbstractCastExpr.apply(AbstractCastExpr.java:136)
	at soot.toDex.StmtVisitor.caseAssignStmt(StmtVisitor.java:491)
	at soot.jimple.internal.JAssignStmt.apply(JAssignStmt.java:217)
	at soot.toDex.DexPrinter.toInstructions(DexPrinter.java:1559)
	at soot.toDex.DexPrinter.toMethodImplementation(DexPrinter.java:1191)
	at soot.toDex.DexPrinter.toMethods(DexPrinter.java:1076)
	... 7 more
</pre>

**Comment by MarcMil** [comment]
There is no way we can reproduce the error without the APK file in question.
