### ISSUE TITLE
java.lang.RuntimeException when ...

### ISSUE THREAD

**Issue by gaojie3781** [soot-oss/soot#1957]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: <pre>trunk</pre>

Command line:
<pre>-pp -cp . -f J Circle</pre>

Max Memory:
<pre>4096MB</pre>

Stack trace:
<pre>java.lang.RuntimeException: None of the basic classes could be loaded! Check your Soot class path!
	at soot.Scene.loadBasicClasses(Scene.java:1718)
	at soot.Scene.loadNecessaryClasses(Scene.java:1807)
	at soot.Main.run(Main.java:241)
	at soot.Main.main(Main.java:141)
</pre>

**Comment by jpstotz** [comment]
Possible duplicate of #1407
