### ISSUE TITLE
java.lang.RuntimeException when soot call `retrieveActiveBody`

### ISSUE THREAD

**Issue by Mech0n** [soot-oss/soot#1960]
Error when I instrument some app, I just want to know how to ignore this error when soot call `retrieveActiveBody`.

Soot version: <pre>trunk</pre>

Command line:
<pre>-w -process-dir com.tencent.fit.ccm_267.apk -d sootOutput_boosted_apps -ire -pp -keep-line-number -allow-phantom-refs -p cg enabled:true</pre>

Max Memory:
<pre>3641MB</pre>

Stack trace:
<pre>java.lang.RuntimeException: no superclass for org.apache.http.entity.HttpEntityWrapper
	at soot.SootClass.getSuperclass(SootClass.java:893)
	at soot.jimple.toolkits.typing.fast.BytecodeHierarchy.buildAncestryTree(BytecodeHierarchy.java:76)
	at soot.jimple.toolkits.typing.fast.BytecodeHierarchy.lcas_(BytecodeHierarchy.java:170)
	at soot.jimple.toolkits.typing.fast.BytecodeHierarchy.lcas(BytecodeHierarchy.java:288)
	at soot.jimple.toolkits.typing.fast.TypeResolver.applyAssignmentConstraints(TypeResolver.java:516)
	at soot.jimple.toolkits.typing.fast.TypeResolver.inferTypes(TypeResolver.java:148)
	at soot.jimple.toolkits.typing.TypeAssigner.internalTransform(TypeAssigner.java:121)
	at soot.BodyTransformer.transform(BodyTransformer.java:55)
	at soot.BodyTransformer.transform(BodyTransformer.java:59)
	at soot.dexpler.DexBody.jimplify(DexBody.java:769)
	at soot.dexpler.DexMethod$1.getBody(DexMethod.java:120)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:402)
	at soot.PackManager$1.run(PackManager.java:1279)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
</pre>

**Comment by MarcMil** [comment]
Using tencent from https://apkpure.net/cheng-che-ma/com.tencent.fit.ccm/download
```
-w -process-dir "乘车码_3.0.2.267_APKPure.apk" -d /tmp/a -ire -pp -keep-line-number -allow-phantom-refs -p cg enabled:true -src-prec apk --android-jars ANDROID-SDK-DIR/platforms
```
Works for me.
Note that you need to specify ```-src-prec apk``` and ```--android-jars```

**Comment by StevenArzt** [comment]
I close this issue. If the problem persists, please open a new issue.
