### ISSUE TITLE
java.lang.NullPointerException when ...

### ISSUE THREAD

**Issue by ibrahim630** [soot-oss/soot#1970]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: <pre>trunk</pre>

Command line:
<pre>-soot-class-path /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/jce.jar:/Users/avci/Downloads/AUSERA-main/ausera-mainengine-configuration//libs/android-support-v4.jar:/Users/avci/Downloads/AUSERA-main/ausera-main/engine-configuration/libs/android-platforms//android-22/android.jar -android-jars /Users/avci/Downloads/AUSERA-main/ausera-main/engine-configuration/libs/android-platforms/ -x android.support. -w -allow-phantom-refs -process-dir /Users/avci/Downloads/AUSERA-main/ausera-mainapks/a2bc18935b023b6b0e6417a4f3cac18aed538d753a78ac8742ef115dff3c1fbd.apk -d /Users/avci/Downloads/AUSERA-main/ausera-mainengine-result/sootoutput/a2bc18935b023b6b0e6417a4f3cac18aed538d753a78ac8742ef115dff3c1fbd</pre>

Max Memory:
<pre>4096MB</pre>

Stack trace:
<pre>java.lang.NullPointerException
	at soot.jimple.toolkits.typing.fast.UseChecker.caseAssignStmt(UseChecker.java:362)
	at soot.jimple.internal.JAssignStmt.apply(JAssignStmt.java:238)
	at soot.jimple.toolkits.typing.fast.UseChecker.check(UseChecker.java:125)
	at soot.jimple.toolkits.typing.fast.TypeResolver.insertCasts(TypeResolver.java:411)
	at soot.jimple.toolkits.typing.fast.TypeResolver.minCasts(TypeResolver.java:422)
	at soot.jimple.toolkits.typing.fast.TypeResolver.inferTypes(TypeResolver.java:158)
	at soot.jimple.toolkits.typing.TypeAssigner.internalTransform(TypeAssigner.java:125)
	at soot.BodyTransformer.transform(BodyTransformer.java:59)
	at soot.BodyTransformer.transform(BodyTransformer.java:64)
	at soot.dexpler.DexBody.jimplify(DexBody.java:657)
	at soot.dexpler.DexMethod$1.getBody(DexMethod.java:148)
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:116)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:355)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processNewMethod(OnFlyCallGraphBuilder.java:1066)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processReachables(OnFlyCallGraphBuilder.java:535)
	at soot.jimple.toolkits.callgraph.CallGraphBuilder.build(CallGraphBuilder.java:104)
	at soot.jimple.toolkits.callgraph.CHATransformer.internalTransform(CHATransformer.java:46)
	at soot.SceneTransformer.transform(SceneTransformer.java:39)
	at soot.Transform.apply(Transform.java:90)
	at soot.RadioScenePack.internalApply(RadioScenePack.java:57)
	at soot.jimple.toolkits.callgraph.CallGraphPack.internalApply(CallGraphPack.java:49)
	at soot.Pack.apply(Pack.java:118)
	at soot.PackManager.runWholeProgramPacks(PackManager.java:593)
	at soot.PackManager.runPacksNormally(PackManager.java:480)
	at soot.PackManager.runPacks(PackManager.java:409)
	at soot.Main.run(Main.java:278)
	at soot.Main.main(Main.java:147)
	at edu.ntu.apk.engine.soot.SootStaticAnalyzer.run(SootStaticAnalyzer.java:25)
	at edu.ntu.apk.engine.main.APKEngine.start_analyze(APKEngine.java:185)
	at edu.ntu.apk.engine.main.APKEngine.start(APKEngine.java:98)
	at edu.ntu.apk.engine.main.APKEngine.main(APKEngine.java:82)
</pre>

**Comment by ibrahim630** [comment]
i had this exception during checking my APK File.

**Comment by MarcMil** [comment]
I assumed that ```a2bc18935b023b6b0e6417a4f3cac18aed538d753a78ac8742ef115dff3c1fbd``` is the SHA256 sum of the app you analyzed. I fixed another bug in Soot related to that app; with these changes, the mentioned app works now for me.
