### ISSUE TITLE
Array Index Out of Bounds during Instrumentation

### ISSUE THREAD

**Issue by adityavardhanpadala** [soot-oss/soot#1996]
I am trying to instrument [io.fireboard.android.zip](https://github.com/soot-oss/soot/files/12317757/io.fireboard.android.zip) using the following transform to sanitize the variables associated in a loop exit. 
```java
        PackManager.v().getPack("jtp").add(new Transform("jtp.loopFinder", new BodyTransformer() {
            @Override
            protected void internalTransform(Body b, String phaseName, Map<String, String> options) {
                String m_name = b.getMethod().getName();
                String c_name = b.getMethod().getDeclaringClass().getName();

                LoopFinder loopFinder = new LoopFinder();
                loopFinder.transform(b);
                Chain<Unit> units = b.getUnits();
                int c = 0;
                for (Loop loop : loopFinder.getLoops(b)) {
                    Collection<Stmt> exits = loop.getLoopExits();
                    for (Stmt exit: exits) {
                            if(exit instanceof IfStmt) {
                                IfStmt ifStmt = (IfStmt) exit;
                                ConditionExpr condition = (ConditionExpr) ifStmt.getCondition();

                                Value leftOp = condition.getOp1();
                                Value rightOp = condition.getOp2();

                                Type ltype = leftOp.getType();
                                Type rtype = rightOp.getType();

                                Local nl = Jimple.v().newLocal("isl"+String.format("%d", c), ltype);
                                Local nr = Jimple.v().newLocal("isr"+String.format("%d", c), rtype);

                                AssignStmt asl, asr;
                                if (isPrimitiveType(ltype)) {
                                    asl = Jimple.v().newAssignStmt(nl, Jimple.v().newStaticInvokeExpr(primSinks.get(ltype).makeRef(), leftOp));
                                }
                                else {
                                    asl = Jimple.v().newAssignStmt(nl, Jimple.v().newStaticInvokeExpr(ObjSinkMet.makeRef(), leftOp));
                                }
                                if(isPrimitiveType(rtype)) {
                                    asr = Jimple.v().newAssignStmt(nr, Jimple.v().newStaticInvokeExpr(primSinks.get(rtype).makeRef(), rightOp));
                                }
                                else {
                                    asr = Jimple.v().newAssignStmt(nr, Jimple.v().newStaticInvokeExpr(ObjSinkMet.makeRef(), rightOp));

                                }
                                units.insertBefore(asl, loop.getHead());
                                units.insertBefore(asr, asl);

                            }
                    }
                }
                b.validate();
            }
        }));
```
and I am getting the following error. Any idea on what I might be doing wrong here?
```
[Thread-20] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: Index 1969673 out of bounds for length 8
java.lang.ArrayIndexOutOfBoundsException: Index 1969673 out of bounds for length 8
	at soot.toolkits.scalar.SimpleLocalDefs.init(SimpleLocalDefs.java:386)
	at soot.toolkits.scalar.SimpleLocalDefs.<init>(SimpleLocalDefs.java:342)
	at soot.toolkits.scalar.SimpleLocalDefs.<init>(SimpleLocalDefs.java:326)
	at soot.toolkits.scalar.SimpleLocalDefs.<init>(SimpleLocalDefs.java:322)
	at soot.toolkits.scalar.LocalDefsFactory.newLocalDefs(LocalDefsFactory.java:103)
	at soot.validation.UsesValidator.validate(UsesValidator.java:79)
	at soot.Body.validate(Body.java:298)
	at soot.jimple.JimpleBody.validate(JimpleBody.java:128)
	at soot.jimple.JimpleBody.validate(JimpleBody.java:114)
	at org.example.Main$2.internalTransform(Main.java:329)
	at soot.BodyTransformer.transform(BodyTransformer.java:47)
	at soot.Transform.apply(Transform.java:126)
	at soot.BodyPack.internalApply(BodyPack.java:49)
	at soot.Pack.apply(Pack.java:126)
	at soot.PackManager.runBodyPacks(PackManager.java:992)
	at soot.PackManager.lambda$runBodyPacks$0(PackManager.java:667)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by AlphaDora** [comment]
Hello? Have you ever solved this issue? I had a similar instrumentation issue like this, but my error message is Index 1 out of bounds for length 1:
[Thread-44] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: Index 1 out of bounds for length 1
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.objectweb.asm.MethodWriter.visitParameterAnnotation(MethodWriter.java:703)
	at soot.AbstractASMBackend.generateMethods(AbstractASMBackend.java:347)
	at soot.AbstractASMBackend.generateByteCode(AbstractASMBackend.java:277)
	at soot.AbstractASMBackend.generateClassFile(AbstractASMBackend.java:226)
	at soot.PackManager.writeClass(PackManager.java:1124)
	at soot.PackManager.lambda$writeOutput$1(PackManager.java:705)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by adityavardhanpadala** [comment]
Not sure if this is what would fix your issue but I switched to using an InvokeStmt instead of AssignStmt.

**Comment by MarcMil** [comment]
You haven't given an implementation of isPrimitiveType, so I've implemented my own variant:
```
private static boolean isPrimitiveType(Type t) {
	return t instanceof PrimType;
}
```
Several issues:
First, you forgot to add the locals to the body, which is likely the culprit for your initial problem:
```
b.getLocals().add(nr);
b.getLocals().add(nl);
```

Furthermore, the ```leftOp``` and ```rightOp``` can be ```null``` constants, thus having ```null``` types (which would be invalid types for local variables). I skipped the statements in these cases and performed no changes.

In some cases, the loop header is a ```$x := @caughtexception``` statement, where you would insert a statement before, invalidating the semantics of the caught exception handler:
```
     label3:
        isr0 = staticinvoke insertedCall ...(0);

        isl0 = staticinvoke insertedCall ...($i0);

        $r5 := @caughtexception;
...
        catch android.database.sqlite.SQLiteDatabaseLockedException from label1 to label2 with label3;
```
Similarly, I skipped the statements in these cases and performed no changes.
```
if (loop.getHead() instanceof IdentityStmt)
	continue;
```

It works for me with these changes.
