### ISSUE TITLE
java.lang.RuntimeException when ...

### ISSUE THREAD

**Issue by FpAuth** [soot-oss/soot#2003]
Steps to reproduce:1.) ...Files used to reproduce: ...Soot version: <pre>trunk</pre>Command line:<pre>-pp -android-jars /home/zzz/BioAuth/static_analysis/android_sdk/ -process-dir /mnt/iscsi/zzz/huawei_202210/com.microsoft.office.outlook.apk</pre>Max Memory:<pre>29127MB</pre>Stack trace:<pre>java.lang.RuntimeException: error: expected 1 element for annotation Deprecated. Got 1 instead.at soot.dexpler.DexAnnotation.addAnnotation(DexAnnotation.java:653)at soot.dexpler.DexAnnotation.handleAnnotation(DexAnnotation.java:447)at soot.dexpler.DexAnnotation.handleFieldAnnotation(DexAnnotation.java:305)at soot.dexpler.DexClassLoader.loadField(DexClassLoader.java:251)at soot.dexpler.DexClassLoader.makeSootClass(DexClassLoader.java:118)at soot.dexpler.DexlibWrapper.makeSootClass(DexlibWrapper.java:168)at soot.dexpler.DexResolver.resolveFromFile(DexResolver.java:63)at soot.DexClassSource.resolve(DexClassSource.java:63)at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:253)at soot.SootResolver.bringToHierarchy(SootResolver.java:221)at soot.SootResolver.bringToSignatures(SootResolver.java:292)at soot.SootResolver.bringToBodies(SootResolver.java:332)at soot.SootResolver.processResolveWorklist(SootResolver.java:171)at soot.SootResolver.resolveClass(SootResolver.java:141)at soot.dexpler.DexlibWrapper.initialize(DexlibWrapper.java:155)at soot.dexpler.DexResolver.initializeDexFile(DexResolver.java:81)at soot.dexpler.DexResolver.resolveFromFile(DexResolver.java:62)at soot.DexClassSource.resolve(DexClassSource.java:63)at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:253)at soot.SootResolver.bringToHierarchy(SootResolver.java:221)at soot.SootResolver.bringToSignatures(SootResolver.java:292)at soot.SootResolver.bringToBodies(SootResolver.java:332)at soot.SootResolver.processResolveWorklist(SootResolver.java:171)at soot.SootResolver.resolveClass(SootResolver.java:141)at soot.Scene.loadClass(Scene.java:1069)at soot.Scene.loadClassAndSupport(Scene.java:1054)at soot.Scene.loadNecessaryClasses(Scene.java:1861)at soot.Main.run(Main.java:241)at soot.Main.main(Main.java:141)at comm.SootConfig.init(SootConfig.java:46)at Analysis.SecurityAnalysis.main(SecurityAnalysis.java:53)</pre>

**Comment by soyo114** [comment]
Hi @FpAuthen,
I am also interested in the issue. If possible, could you please share the specific file or code snippet that triggers the problem?

**Comment by MarcMil** [comment]
Without the specific APK file, there is nothing to be done here. I've tried using a current Outlook app version I could get easily (com.microsoft.office.outlook-5-2548-3-android60.apk), but that worked fine for me.
Please retry with the current nightly version of Soot, and if it is still an issue, supply the APK file.
