### ISSUE TITLE
soot.SootResolver$SootClassNotFoundException when ...

### ISSUE THREAD

**Issue by TaizhengWang** [soot-oss/soot#2005]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: <pre>trunk</pre>

Command line:
<pre>-cp . -pp -process-dir /Users/wangtaizheng/soot-tool/activemq-all-5.16.6.jar</pre>

Max Memory:
<pre>3641MB</pre>

Stack trace:
<pre>soot.SootResolver$SootClassNotFoundException: couldn&#39;t find class: javax.annotation.Nullable (is your soot-class-path set properly?)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:245)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:221)
	at soot.SootResolver.bringToSignatures(SootResolver.java:292)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:179)
	at soot.SootResolver.resolveClass(SootResolver.java:141)
	at soot.Scene.loadClass(Scene.java:1009)
	at soot.Scene.loadClassAndSupport(Scene.java:996)
	at soot.Scene.loadNecessaryClasses(Scene.java:1822)
	at soot.Main.run(Main.java:241)
	at soot.Main.main(Main.java:141)
</pre>

**Comment by MarcMil** [comment]
You'll want to either use ```--allow-phantom-refs``` or add the JAR which contains ```javax.annotation.Nullable``` to the soot classpath.
