### ISSUE TITLE
java.lang.NullPointerException when ...

### ISSUE THREAD

**Issue by zhongJunPeng123** [soot-oss/soot#2007]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: <pre>trunk</pre>

Command line:
<pre>-cp . -pp -process-dir D:\Java\postgraduateLearning\SootDome\src\main\java -d sootOutput -f J</pre>

Max Memory:
<pre>4030MB</pre>

Stack trace:
<pre>java.lang.NullPointerException
	at soot.JastAddJ.Program.initPaths(Program.java:336)
	at soot.SootResolver.initializeProgram(SootResolver.java:91)
	at soot.SootResolver.getProgram(SootResolver.java:386)
	at soot.JastAddInitialResolver.formAst(JastAddInitialResolver.java:62)
	at soot.JavaClassSource.resolve(JavaClassSource.java:66)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:253)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:221)
	at soot.SootResolver.bringToSignatures(SootResolver.java:292)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:179)
	at soot.SootResolver.resolveClass(SootResolver.java:141)
	at soot.Scene.loadClass(Scene.java:1009)
	at soot.Scene.loadClassAndSupport(Scene.java:994)
	at soot.Scene.loadNecessaryClasses(Scene.java:1822)
	at soot.Main.run(Main.java:241)
	at soot.Main.main(Main.java:141)
	at SootTransformer.main(SootTransformer.java:3)
</pre>

**Comment by StevenArzt** [comment]
Soot does not support parsing Java source code anymore. Please use the bytecode frontend.
