### ISSUE TITLE
JLookupSwitchStmt.toString java.lang.StackOverflowError

### ISSUE THREAD

**Issue by PengHu01** [soot-oss/soot#2010]
JLookupSwitchStmt contains endless loop, therefore it triggered SOE.

[com.androidesk_317.zip](https://github.com/soot-oss/soot/files/13036160/com.androidesk_317.zip)

gradle:
```
implementation 'org.soot-oss:soot:4.4.1'
implementation 'de.upb.cs.swt:heros:1.1.0'
implementation 'org.slf4j:slf4j-simple:2.0.7'
implementation 'org.slf4j:slf4j-api:2.0.7'
```
java code:
```
        G.reset();
        Options.v().set_prepend_classpath(true);
        Options.v().set_allow_phantom_refs(true);
        Options.v().set_output_format(Options.output_format_jimple);
        Options.v().set_process_dir(Collections.singletonList("com.androidesk_317.apk"));
        Options.v().set_whole_program(true);
        Options.v().set_src_prec(Options.src_prec_apk);
        Options.v().set_app(true);
        Options.v().set_process_multiple_dex(true);
        Options.v().set_android_jars("F:\\android-platforms-master\\platforms");

        Scene.v().loadNecessaryClasses();

        List<SootMethod> entryPoints = new ArrayList<>();

        for (SootClass sc : Scene.v().getApplicationClasses()) {
            entryPoints.addAll(sc.getMethods());
        }
        Scene.v().setEntryPoints(entryPoints);

        PackManager.v().runPacks();

        SootMethod sootMethod = Scene.v().getMethod("<com.bytedance.msdk.adapter.ks.KsDrawAdapter: void loadAd(android.content.Context,java.util.Map)>");
        for (Unit unit: sootMethod.retrieveActiveBody().getUnits()){
            unit.toString();
        }
```
debug information:
```
Exception in thread "main" java.lang.StackOverflowError
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:179)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:91)
	at java.base/java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:112)
	at java.base/java.lang.StringBuilder.<init>(StringBuilder.java:131)
	at soot.jimple.internal.JLookupSwitchStmt.toString(JLookupSwitchStmt.java:81)
	at java.base/java.lang.String.valueOf(String.java:4218)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
	at soot.jimple.internal.JLookupSwitchStmt.toString(JLookupSwitchStmt.java:90)
	at java.base/java.lang.String.valueOf(String.java:4218)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
	at soot.jimple.internal.JLookupSwitchStmt.toString(JLookupSwitchStmt.java:90)
	at java.base/java.lang.String.valueOf(String.java:4218)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
	at soot.jimple.internal.JLookupSwitchStmt.toString(JLookupSwitchStmt.java:90)
	at java.base/java.lang.String.valueOf(String.java:4218)
......
```
unitChain:
![image](https://github.com/soot-oss/soot/assets/72391458/2af34ac6-a888-4345-8a98-3247b8aa1fdb)
endless loop:
![image](https://github.com/soot-oss/soot/assets/72391458/f332415a-7564-42a4-aaaf-0dbdbf6b9006)

I found that the SOE was triggered when a case of JLookupSwitchStmt is goto another JLookupSwitchStmt. Therefore, I added an if statement, when the unit that a case goto is instanceof JLookupSwitchStmt, I decided the key value of JLookupSwitchStmt as the String value.

modified code in soot.jimple.internal.JLookupSwitchStmt.toString
```
@Override
    public String toString() {
        final char endOfLine = ' ';
        StringBuilder buf = new StringBuilder(Jimple.LOOKUPSWITCH + "(");

        buf.append(keyBox.getValue().toString()).append(')').append(endOfLine);
        buf.append('{').append(endOfLine);

        for (ListIterator<IntConstant> it = lookupValues.listIterator(); it.hasNext(); ) {

            IntConstant c = it.next();
            buf.append("    " + Jimple.CASE + " ").append(c).append(": " + Jimple.GOTO + " ");
            Unit target = getTarget(it.previousIndex());
            if (target instanceof JLookupSwitchStmt) {
                // modification from here ******************************************************************
                StringBuilder targetStringBuilder = new StringBuilder();
                targetStringBuilder.append(Jimple.LOOKUPSWITCH + "(").append(((JLookupSwitchStmt) target).getKeyBox().getValue().toString()).append(')').append(endOfLine);
                buf.append(target == this ? "self" : targetStringBuilder.toString()).append(';').append(endOfLine);
            }else {
                buf.append(target == this ? "self" : target).append(';').append(endOfLine);
            }
                // modification to here ******************************************************************
        }
        {
            buf.append("    " + Jimple.DEFAULT + ": " + Jimple.GOTO + " ");
            Unit target = getDefaultTarget();
            buf.append(target == this ? "self" : target).append(';').append(endOfLine);
        }
        buf.append('}');

        return buf.toString();
    }
```
After modification:
![image](https://github.com/soot-oss/soot/assets/72391458/ca587ad8-0bf1-4c83-8d84-afcd2cc6ad84)

**Comment by StevenArzt** [comment]
Has been fixed. Please reopen the issue if you still experience problems.
