### ISSUE TITLE
Skip analysis for erroring functions 

### ISSUE THREAD

**Issue by adityavardhanpadala** [soot-oss/soot#2013]
Is there a way to make soot ignore the analysis and continue with next method when it encounters an error while lifting a specific method. 

For instance I get this error when I am trying to analyse a program with a ``BodyTransformer`` in the ``jtp`` phase 
```
[Thread-19] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: Warning: Bad use of class type at $r4[$i2] = $r3 in <com.huawei.hms.scankit.aiscan.common.D: com.huawei.hms.scankit.aiscan.common.z[] a(com.huawei.hms.scankit.aiscan.common.z[],int,int,double[])>
Warning: Bad use of class type at $r4[$i2] = $r3 in <com.huawei.hms.scankit.aiscan.common.D: com.huawei.hms.scankit.aiscan.common.z[] a(com.huawei.hms.scankit.aiscan.common.z[],int,int,double[])>
	at soot.validation.CheckTypesValidator.checkCopy(CheckTypesValidator.java:211)
	at soot.validation.CheckTypesValidator.validate(CheckTypesValidator.java:69)
	at soot.Body.validate(Body.java:298)
	at soot.jimple.JimpleBody.validate(JimpleBody.java:128)
	at soot.jimple.JimpleBody.validate(JimpleBody.java:114)
	at soot.PackManager.runBodyPacks(PackManager.java:995)
	at soot.PackManager.lambda$runBodyPacks$0(PackManager.java:667)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Exception in thread "main" Warning: Bad use of class type at $r4[$i2] = $r3 in <com.huawei.hms.scankit.aiscan.common.D: com.huawei.hms.scankit.aiscan.common.z[] a(com.huawei.hms.scankit.aiscan.common.z[],int,int,double[])>
	at soot.validation.CheckTypesValidator.checkCopy(CheckTypesValidator.java:211)
	at soot.validation.CheckTypesValidator.validate(CheckTypesValidator.java:69)
	at soot.Body.validate(Body.java:298)
	at soot.jimple.JimpleBody.validate(JimpleBody.java:128)
	at soot.jimple.JimpleBody.validate(JimpleBody.java:114)
	at soot.PackManager.runBodyPacks(PackManager.java:995)
	at soot.PackManager.lambda$runBodyPacks$0(PackManager.java:667)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Exception in thread "Thread-19" Warning: Bad use of class type at $r4[$i2] = $r3 in <com.huawei.hms.scankit.aiscan.common.D: com.huawei.hms.scankit.aiscan.common.z[] a(com.huawei.hms.scankit.aiscan.common.z[],int,int,double[])>
	at soot.validation.CheckTypesValidator.checkCopy(CheckTypesValidator.java:211)
	at soot.validation.CheckTypesValidator.validate(CheckTypesValidator.java:69)
	at soot.Body.validate(Body.java:298)
	at soot.jimple.JimpleBody.validate(JimpleBody.java:128)
	at soot.jimple.JimpleBody.validate(JimpleBody.java:114)
	at soot.PackManager.runBodyPacks(PackManager.java:995)
	at soot.PackManager.lambda$runBodyPacks$0(PackManager.java:667)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by MarcMil** [comment]
You can achieve something similar by loading all Bodys manually
```
		for (SootClass i : Scene.v().getApplicationClasses()) {
			for (SootMethod m : i.getMethods()) {
				if (m.isConcrete()) {
					try {
						m.retrieveActiveBody();
					} catch (Exception e) {
						//error handling
					}
				}
			}
		}
```

It would be even better to be able to resolve the underlying problem. For this, it would good to get the APK/input file you're trying to analyze.

**Comment by jpstotz** [comment]
@MarcMil But that only works if you do not use a call graph. When building the call graph the methods where Soot fails to retrieve the method body will screw the call graph building process.

**Comment by MarcMil** [comment]
True, it depends on what you want to achieve. In this particular case, setting ```Options.v().set_validate(false)``` would be sufficient.
Nonetheless, this does not solve the underlying bug.
