### ISSUE TITLE
java.lang.NullPointerException when ...

### ISSUE THREAD

**Issue by braxidas** [soot-oss/soot#2079]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: <pre>trunk</pre>

Command line:
<pre>-cp . -pp -d out -process-dir C:\\Users\\li_sh\\Desktop\\msexample\\alibabacloud-microservice-demo\\microservice-doc-demo\\spring-cloud-simplest-demo\\nacos-service-consumer\\src\\main\\java\\com\\aliware\\edas</pre>

Max Memory:
<pre>4028MB</pre>

Stack trace:
<pre>java.lang.NullPointerException
	at soot.JastAddJ.Program.initPaths(Program.java:336)
	at soot.SootResolver.initializeProgram(SootResolver.java:91)
	at soot.SootResolver.getProgram(SootResolver.java:386)
	at soot.JastAddInitialResolver.formAst(JastAddInitialResolver.java:62)
	at soot.JavaClassSource.resolve(JavaClassSource.java:66)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:253)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:221)
	at soot.SootResolver.bringToSignatures(SootResolver.java:292)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:179)
	at soot.SootResolver.resolveClass(SootResolver.java:141)
	at soot.Scene.loadClass(Scene.java:1009)
	at soot.Scene.loadClassAndSupport(Scene.java:994)
	at soot.Scene.loadNecessaryClasses(Scene.java:1822)
	at soot.Main.run(Main.java:241)
	at soot.Main.main(Main.java:141)
</pre>

**Comment by StevenArzt** [comment]
What is your input file format? Soot's support for Java source files is pretty outdated / bad, while the bytecode frontend is very stable and used in many productive applications.
