### ISSUE TITLE
ClassCastException in analysis of Java Class Library (version 7) using ASM

### ISSUE THREAD

**Issue by johanneslerch** [soot-oss/soot#224]
I am unable to perform an analysis that works with -coffi using the new ASM default. By looking at the stack trace attached below, I think it already crashes before anything of my analysis even kicks in, so it should be possible to reproduce the failure.

Soot arguments: -w -keep-line-number -allow-phantom-refs -p cg all-reachable:true -f none -include-all -cp /Users/joe/JavaRuntimes/jre1.7.0/lib/jce.jar:/Users/joe/JavaRuntimes/jre1.7.0/lib/jsse.jar -process-dir /Users/joe/JavaRuntimes/jre1.7.0/lib/rt.jar

Exception in thread "main" java.lang.RuntimeException: Failed to convert <java.util.concurrent.ForkJoinWorkerThread: void helpQuiescePool()>
    at soot.asm.JimpleSource.getBody(JimpleSource.java:1644)
    at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
    at soot.SootMethod.retrieveActiveBody(SootMethod.java:324)
    at soot.jimple.toolkits.annotation.LineNumberAdder.internalTransform(LineNumberAdder.java:44)
    at soot.PackManager.runPacksNormally(PackManager.java:437)
    at soot.PackManager.runPacks(PackManager.java:387)
    at soot.Main.run(Main.java:204)
    at soot.Main.main(Main.java:147)
    at flow.twist.AbstractAnalysis.execute(AbstractAnalysis.java:27)
    at flow.twist.mains.GenericCallerSensitiveBiDi.main(GenericCallerSensitiveBiDi.java:28)
Caused by: java.lang.ClassCastException: soot.asm.UnitContainer cannot be cast to soot.jimple.AssignStmt
    at soot.asm.StackFrame.mergeIn(StackFrame.java:159)
    at soot.asm.JimpleSource.convertJumpInsn(JimpleSource.java:1037)
    at soot.asm.JimpleSource.convert(JimpleSource.java:1469)
    at soot.asm.JimpleSource.getBody(JimpleSource.java:1642)
    ... 9 more

**Comment by Waldo1637** [comment]
Commit 5d7a106 did not fully resolve the issue. Lines 149 and 171 assume the value in `units[0]` will be an `AssignStmt` (or `DefinitionStmt` after commit 87e9844). However, `units[0]` may actually be another `UnitContainer` causing the exception mentioned above to reappear at either of those lines. Commit 59966b4 continues to go deeper into instances of `UnitContainer` until a `Unit` is found that is not an instance of `UnitContainer`.
