### ISSUE TITLE
Soot couldn't find class

### ISSUE THREAD

**Issue by davidyoung8906** [soot-oss/soot#230]
It's related to this issue: https://github.com/Sable/soot/issues/108
I ran AndroidInstrument.java(http://www.bodden.de/wordpress/wp-content/uploads/2013/01/AndroidInstrument.java_.txt) using this apk: https://dl.dropboxusercontent.com/u/37908210/26dd1126da55fd0754a0b96d877ac0f36f248e99.apk/assets/sqlite.db.apk
Here's the output:
    Soot started on Tue Aug 05 14:15:47 PDT 2014
    Using '/home/wyang/workspace/CommandLine/android-platforms-forSoot//android-4/android.jar' as     android.jar
    Exception in thread "main" soot.SootResolver$SootClassNotFoundException: couldn't find class:     org.xmlpull.v1.XmlPullParserException (is your soot-class-path set properly?)
        at soot.SootResolver.bringToHierarchy(SootResolver.java:219)
        at soot.SootResolver.processResolveWorklist(SootResolver.java:169)
        at soot.SootResolver.resolveClass(SootResolver.java:129)
        at soot.Scene.loadClass(Scene.java:670)
        at soot.Scene.loadClassAndSupport(Scene.java:655)
        at soot.Scene.loadNecessaryClasses(Scene.java:1306)
        at soot.Main.run(Main.java:173)
        at soot.Main.main(Main.java:146)
        at flowtry.AndroidInstrument.main(AndroidInstrument.java:83)

**Comment by jyotigajrani** [comment]
I am using following commands to run the same:

**1. javac -cp "soot-trunk.jar" AndroidInstrument.java

2. java -cp soot-trunk.jar soot.Main -android-jars /home/jyoti/Android/adt-bundle-linux-x86_64-20140702/sdk/platforms -cp . -pp AndroidInstrument -process-dir Onlytelephony.apk
**
But I get following exception:

soot.SootResolver$SootClassNotFoundException: couldn't find class: soot.Local (is your soot-class-path set properly?)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:228)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:173)
	at soot.SootResolver.resolveClass(SootResolver.java:131)
	at soot.Scene.loadClass(Scene.java:725)
	at soot.Scene.loadClassAndSupport(Scene.java:710)
	at soot.Scene.loadNecessaryClass(Scene.java:1425)
	at soot.Scene.loadNecessaryClasses(Scene.java:1436)
	at soot.Main.run(Main.java:243)
	at soot.Main.main(Main.java:147)

my CLASSPATH is set in .bashrc as:

export CLASSPATH=$CLASPATH:/usr/lib/jvm/java-7-oracle:/usr/lib/jvm/java-7-openjdk-amd64/:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-8-oracle/jre/lib/deploy.jar:/usr/lib/jvm/java-8-oracle/jre/lib/javawas.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar:/home/jyoti/Android/adt-bundle-linux-x86_64-20140702/sdk/platforms:/home/jyoti/PHD/IccTA/soot-infoflow-android-iccta-master/libs/

So as far as I think, I have added all jars in classpath and using -pp option in second command. I think my commands are missing something or have some mistake.

May you please help by telling what should be exact commands. I will be very helpful to you. I am struggling for this from 2-3 days.

**Comment by gazzaz86** [comment]
Have you solved the problem? If yes, would you please explain how you fixed it?

**Comment by jyotigajrani** [comment]
I solved the problem and using below commands:

javac -cp "soot-trunk.jar" AndroidInstrumentfjyoti.java
 
java -cp .:soot-trunk.jar AndroidInstrumentfjyoti -pp -d <resultant directory path> -android-jars <path to platforms folder of sdk> -w -allow-phantom-refs -ire -process-dir <apk path to be analyzed> -output-format dex -src-prec apk

Note: also check to use correct version of soot-trunk.jar

**Comment by xuehenIT** [comment]
Exception in thread "main" soot.SootResolver$SootClassNotFoundException: couldn't find class: org.apache.http.HttpResponse (is your soot-class-path set properly?)
I had maked java-path ,also maked httpcore-4.4.1.jar into my program , why this error ? how can i resolve it ?? please...
