### ISSUE TITLE
Exception during parsing

### ISSUE THREAD

**Issue by martinschaef** [soot-oss/soot#253]
I get an exception when I try to parse the following file:
https://github.com/martinschaef/jar2bpl/tree/master/jar2bpl_test/regression/false_positives/fp05

The command is:
java -jar ../jar2bpl/lib/soot-trunk.jar  -keep-line-number -pp -output-format none -allow-phantom-refs -cp /Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre/lib/jce.jar::regression/false_positives/fp05/ -src-prec class -process-path regression/false_positives/fp05/

And the exception is:
Unexpected error of kind java.lang.NullPointerException
Exception in thread "main" java.lang.Error: /Users/schaef/git/jar2bpl/jar2bpl_test/regression/false_positives/fp05/FalsePositives05.java: null
    at soot.JastAddJ.PathPart.getCompilationUnit(PathPart.java:149)
    at soot.JastAddJ.FileNamesPart.addSourceFile(FileNamesPart.java:82)
    at soot.JastAddJ.Program.addSourceFile(Program.java:201)
    at soot.JastAddJ.Program.getCachedOrLoadCompilationUnit(Program.java:628)
    at soot.JastAddInitialResolver.formAst(JastAddInitialResolver.java:54)
    at soot.JavaClassSource.resolve(JavaClassSource.java:54)
    at soot.SootResolver.bringToHierarchy(SootResolver.java:230)
    at soot.SootResolver.bringToSignatures(SootResolver.java:255)
    at soot.SootResolver.processResolveWorklist(SootResolver.java:168)
    at soot.SootResolver.resolveClass(SootResolver.java:129)
    at soot.Scene.loadClass(Scene.java:670)
    at soot.Scene.loadClassAndSupport(Scene.java:655)
    at soot.Scene.loadNecessaryClasses(Scene.java:1306)
    at soot.Main.run(Main.java:173)
    at soot.Main.main(Main.java:146)
Caused by: java.lang.NullPointerException
    at beaver.Parser$TokenStream.remove(Parser.java:240)
    at beaver.Parser.recoverFromError(Parser.java:667)
    at beaver.Parser.parse(Parser.java:468)
    at beaver.Parser.parse(Parser.java:409)
    at soot.JastAddJ.JastAddJavaParser.parse(JastAddJavaParser.java:759)
    at soot.SootResolver$1.parse(SootResolver.java:74)
    at soot.JastAddJ.PathPart.getCompilationUnit(PathPart.java:136)

However, it works just fine when I use the class file instead of the java file.

**Comment by StevenArzt** [comment]
We don't support JastAdd anymore. Please use the bytecode frontend instead.
