### ISSUE TITLE
Upgrade JastAddJ-Frontend

### ISSUE THREAD

**Issue by StevenArzt** [soot-oss/soot#300]
Soot uses a rather outdated version of JastAddJ that is no longer supported to parse Java source files. The old version only supports parts of Java 7 (there are examples for which it fails), and there is no support for Java 8. Furthermore, the integration with various weaved-in aspects and custom JastAdd scripts is a nightmare to maintain. It even makes Soot have dependencies on the JastAddJ source code.

Therefore, we should take the new JastAddJ version (that even has work on Java 8 going on) as an incentive to do a major overhaul. As I see it, their new version neatly compiles into a single JAR file, so I have hopes to get to a clear-cut interface here.

**Comment by edwardmp** [comment]
I'm looking into this as I need Java 8 support. What current version of JastAddJ is used? Any pointers on what changes would be necessary?

**Comment by StevenArzt** [comment]
The JastAddJ-frontend uses JastAdd 1 which is no longer supported. JastAdd 2 is not compatible, so the front-end needs to be re-implemented pretty much from scratch. A student team at TU Darmstadt started with a new implementation based on the javac compiler. The code exists, but I do not have the time at the moment to properly test and integrate it. You can have a look here: https://github.com/HairBears/Soot. If you want to take on this task, let us coordinate to avoid duplicate effort.

**Comment by edwardmp** [comment]
@StevenArzt 
It depends, too be honest I don't have much time, not more than 2 days max and I'm not sure if that would be enough, let me check the code you referred to first.

**Comment by edwardmp** [comment]
@StevenArzt 

Unfortunately, the students' version doesn't appear to work:
java.lang.NullPointerException
	at soot.Scene.getSootClassUnsafe(Scene.java:831)
	at soot.Scene.getSootClass(Scene.java:845)
	at soot.java.JavaClassSource.resolve(JavaClassSource.java:131)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:239)
	at soot.SootResolver.bringToSignatures(SootResolver.java:266)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:170)
	at soot.SootResolver.resolveClass(SootResolver.java:131)
	at soot.Scene.loadClass(Scene.java:725)
	at soot.Scene.loadClassAndSupport(Scene.java:711)
	at soot.Scene.loadNecessaryClasses(Scene.java:1448)
	at soot.Main.run(Main.java:243)
	at soot.Main.main(Main.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by StevenArzt** [comment]
It works on some examples, but I know that it still needs work before it is really able to read in arbitrary source code projects. There's only so much you can expect from a student project with a limited course period. If we maintainers then have to take it from there, the feature or component may be delayed quite a bit. Outside collaborators are always welcome to help.

**Comment by edwardmp** [comment]
@StevenArzt 
OK. Realistically how much time would you expect it would need to upgrade to ExtendJ? More than two days? Just checking if this is viable for me

**Comment by StevenArzt** [comment]
You need to generate Jimple code from whatever ExtendJ gives you. In any case, I would be very surprised if this would be less than a week or two of thorough work. Most likely, it will be more until you got all the cases covered. Keep in mind that when reading in Java source code, you need to do parts of transformations that the Java compiler normally performs, i.e., references from inner to outer classes, virtual dispatch resolution, etc.

**Comment by edwardmp** [comment]
Thanks. Unfortunately at this point this project would be out of scope for me.

**Comment by StevenArzt** [comment]
We don't support JastAdd anymore. Please use the bytecode frontend instead.
