### ISSUE TITLE
No enum constant org.jf.dexlib2.Opcode.SUB_ANDROID.VIEW.DISPLAY_2ADDR

### ISSUE THREAD

**Issue by 0-14N** [soot-oss/soot#440]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: trunk

Command line:
-android-jars /home/chenxiong/Android/Sdk/platforms -process-dir /data/android-apps-crawler/repo/apps/anzhi/mobi.appplus.calculator.plus-32.apk -d /home/chenxiong/tmp/sootOutput/mobi.appplus.calculator.plus-32.apk -force-android-jar /home/chenxiong/Android/Sdk/platforms/android-22/android.jar

Max Memory:
14341MB

Stack trace:
java.lang.IllegalArgumentException: No enum constant org.jf.dexlib2.Opcode.SUB_ANDROID.VIEW.DISPLAY_2ADDR
    at java.lang.Enum.valueOf(Enum.java:236)
    at org.jf.dexlib2.Opcode.valueOf(Opcode.java:34)
    at soot.toDex.ExprVisitor.build2AddrBinaryInsn(ExprVisitor.java:308)
    at soot.toDex.ExprVisitor.buildCalculatingBinaryInsn(ExprVisitor.java:292)
    at soot.toDex.ExprVisitor.caseSubExpr(ExprVisitor.java:336)
    at soot.jimple.internal.JSubExpr.apply(JSubExpr.java:42)
    at soot.toDex.StmtVisitor.caseAssignStmt(StmtVisitor.java:371)
    at soot.jimple.internal.JAssignStmt.apply(JAssignStmt.java:238)
    at soot.toDex.DexPrinter.toInstructions(DexPrinter.java:1152)
    at soot.toDex.DexPrinter.toMethodImplementation(DexPrinter.java:1035)
    at soot.toDex.DexPrinter.toMethods(DexPrinter.java:932)
    at soot.toDex.DexPrinter.addAsClassDefItem(DexPrinter.java:496)
    at soot.toDex.DexPrinter.add(DexPrinter.java:1281)
    at soot.PackManager.writeClass(PackManager.java:999)
    at soot.PackManager.writeOutput(PackManager.java:620)
    at soot.PackManager.writeOutput(PackManager.java:526)
    at soot.Main.run(Main.java:250)
    at soot.Main.main(Main.java:152)
    at edu.gatech.gtisc.legoandroid.instrumentation.LegoInstrumentEngine.instrument(LegoInstrumentEngine.java:229)
    at edu.gatech.gtisc.legoandroid.LegoAndroid.main(LegoAndroid.java:259)
    at edu.gatech.gtisc.legoandroid.test.TestMain.main(TestMain.java:108)

**Comment by StevenArzt** [comment]
I added some error checking inside Soot. From the stack trace, I assume that the Jimple code contains a subtraction operation which is not carried out on primitives, but on an enum or a reference type. This is now explicitly checked for. For further investigation, please send me your APK file via e-mail to Steven.Arzt@cased.de or upload it somewhere for me.

**Comment by pavanupb** [comment]
Closed due to inactivity. Please re-open if still relevant.
