### ISSUE TITLE
java.util.ConcurrentModificationException when decompiling to Java

### ISSUE THREAD

**Issue by dannote** [soot-oss/soot#517]
Keep getting this for different classes.

Soot version: <pre>trunk</pre>

Command line:

<pre>-d gamepack-soot -cp /usr/lib/jvm/java-7-openjdk-i386/jre/lib/rt.jar:/usr/lib/jvm/java-7-openjdk-i386/jre/lib/jce.jar:/usr/share/icedtea-web/plugin.jar:/usr/share/icedtea-web/netx.jar:/usr/lib/jvm/java-8-openjdk-i386/jre/lib/jsse.jar:gamepack.jar -f d client</pre>

Max Memory:

<pre>456MB</pre>

Stack trace:

<pre>java.util.ConcurrentModificationException
    at soot.util.HashChain$LinkIterator.hasNext(HashChain.java:485)
    at soot.dava.toolkits.base.finders.ExceptionFinder.preprocess(ExceptionFinder.java:90)
    at soot.dava.DavaBody.&#60;init&#62;(DavaBody.java:321)
    at soot.dava.Dava.newBody(Dava.java:84)
    at soot.PackManager.runBodyPacks(PackManager.java:1009)
    at soot.PackManager.access$000(PackManager.java:137)
    at soot.PackManager$1.run(PackManager.java:625)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
</pre>

**Comment by dannote** [comment]
[client.class.zip](https://github.com/Sable/soot/files/74596/client.class.zip)

**Comment by pavanupb** [comment]
@dannote Please re-open the issue if this is still relevant.
