### ISSUE TITLE
java.lang.NoClassDefFoundError: soot/Transformer

### ISSUE THREAD

**Issue by njupt-moon** [soot-oss/soot#528]
When I was trying the example form "Instrumenting Android Apps with Soot", this error occurred. How can i solve it?

**Comment by StevenArzt** [comment]
Where did you obtain Soot from? This error looks as if your Soot build is incomplete or your Java VM cannot find important Soot classes for some other reason.

**Comment by 2048li** [comment]
I had the same problem.
The command I used is :" java -cp soot-trunk.jar:soot-infoflow.jar:soot-infoflow-android.jar:slf4j-api-1.7.5.jar:slf4j-simple-1.7.5.jar:AXMLPrinter2.jar soot.jimple.infoflow.android.TestApps.Test "/Users/shentanli/Documents/githubfile/vipshop.apk" /User/shentanli/Downloads/android-sdk-macosx/platforms"
And I don't think it caused by the incomplete of soot build or java vm, because if I run this command : "
java -cp soot-trunk.jar:soot-infoflow.jar:soot-infoflow-android.jar:slf4j-api-1.7.5.jar:slf4j-simple-1.7.5.jar:AXMLPrinter2.jar soot.jimple.infoflow.android.TestApps.Test --help", it works well:
this is the result:
"LF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/shentanli/Documents/githubfile/soot/soot-trunk.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/shentanli/Documents/githubfile/soot/slf4j-simple-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
FlowDroid (c) Secure Software Engineering Group @ EC SPRIDE

Incorrect arguments: [0] = apk-file, [1] = android-jar-directory
Optional further parameters:
	--TIMEOUT n Time out after n seconds
	--SYSTIMEOUT n Hard time out (kill process) after n seconds, Unix only
	--SINGLEFLOW Stop after finding first leak
"
——————————————————————————————————————————
(This is the exception result:
Exception in thread "main" java.lang.NoClassDefFoundError: pxb/android/axml/NodeVisitor
	at soot.jimple.infoflow.android.manifest.ProcessManifest.handle(ProcessManifest.java:113)
	at soot.jimple.infoflow.android.manifest.ProcessManifest.<init>(ProcessManifest.java:86)
	at soot.jimple.infoflow.android.manifest.ProcessManifest.<init>(ProcessManifest.java:70)
	at soot.jimple.infoflow.android.SetupApplication.calculateSourcesSinksEntrypoints(SetupApplication.java:382)
	at soot.jimple.infoflow.android.SetupApplication.calculateSourcesSinksEntrypoints(SetupApplication.java:359)
	at soot.jimple.infoflow.android.TestApps.Test.runAnalysis(Test.java:594)
	at soot.jimple.infoflow.android.TestApps.Test.main(Test.java:239)
Caused by: java.lang.ClassNotFoundException: pxb.android.axml.NodeVisitor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more)

**Comment by StevenArzt** [comment]
FlowDroid does not need to load the Transformer class for reporting the help message, but it needs to load it for running the actual data flow analysis. Which operating system are you using? The delimiter between the classpath entries is a colon on Linux and Mac, but a semicolon on Windows.

**Comment by 2048li** [comment]
Oh, The command I used is not relevant with Transformer, the --help message is just used for proving the front command is right, and then in this circumstance , the "NoclassDefFoundError" exception happens again. I run this command in Mac OS.

**Comment by StevenArzt** [comment]
Can you please try to re-order the classpath to "soot-infoflow-android.jar:soot-infoflow.jar:soot-trunk.jar:slf4j-api-1.7.5.jar:slf4j-simple-1.7.5.jar:AXMLPrinter2.jar" and see if that works?

**Comment by 2048li** [comment]
Thanks first, but it seems doesn’t work, when I re-order the class path, it throws the same exception.

**Comment by AbdulAli** [comment]
I believe the problem still persist? Because I am facing the same issue while trying to implement the "Instrumenting Android Apps with Soot" at windows.
----------------------------------------------------------------------------------------------------------------
To compile:-
javac -classpath "%home%soot-infoflow-android-trunk.jar;%home%soot-infoflow.jar;%home%sootclasses-trunk.jar;%home%slf4j-api-1.7.25.jar;%home%slf4j-simple-1.7.25.jar;%home%AXMLPrinter2.jar;" Driver.java

It compiles safely producing:- Driver$1$1.class, Driver$1.class, Driver.class

To Execute:-
java -cp . Driver -android-jars C:\Users\AbdulAli\git\android-platforms -process-dir C:\Users\AbdulAli\Desktop\ProgramAnalysis\Pijaret-APK\1.7.apk

----------------------------------------------------------------------------------------------------------------

And i get the following exception:-

Exception in thread "main" java.lang.NoClassDefFoundError: soot/Transformer
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2615)
        at java.lang.Class.getMethod0(Class.java:2856)
        at java.lang.Class.getMethod(Class.java:1668)
        at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)

Caused by: java.lang.ClassNotFoundException: soot.Transformer
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 6 more

**Comment by maliha1234** [comment]
Hi, I ran the sample code of AndroidInstrument.java and got this exception  in thread "main" java.lang.NoClassDefFoundError: pxb/android/axml/AxmlVisitor. IDE - IntelliJ and MAC OS X. How can I resolve it? I externally included the soot jar in my project.

**Comment by peey** [comment]
Getting the same error for soot j9's nightly builds obtained from [here](https://soot-build.cs.upb.de/public/origin/java9/soot/soot-j9/build/) on openjdk 1.10. Didn't have this issue with non j9 version of soot on openjdk 1.8

**Comment by Sevennn** [comment]
Hey, i have the same problem before, and i solved this problem by adding path/to/soot.jar to CLASSPATH. It really works in Ubuntu. I think this problem it's caused by the diffenrence between the classpath of runtime and compiler time.

**Comment by pavanupb** [comment]
@njupt-moon Please re-open if this is still relevant.
