### ISSUE TITLE
Semantic Error: duplicate type while processing android source

### ISSUE THREAD

**Issue by bulburDE** [soot-oss/soot#536]
I obtained the android sources for Android 4.2.2 (API 17) using the Android SDK manager. While processing them using the command line arguments `-v -cp /opt/android-sdk/sources/android-17 java.lang.NoClassDefFoundError` the following error occurs:

```
resolving [from .java]: java.lang.NoClassDefFoundError
resolving [from .java]: java.lang.LinkageError
/opt/android-sdk/sources/android-17/java/lang/LinkageError.java:27:
  Semantic Error: duplicate type LinkageError in package java.lang
soot.CompilationDeathException: there were errors during parsing and/or type checking (JastAdd frontend)
    at soot.JastAddInitialResolver.formAst(JastAddInitialResolver.java:63)
    at soot.JavaClassSource.resolve(JavaClassSource.java:54)
    at soot.SootResolver.bringToHierarchy(SootResolver.java:237)
    at soot.SootResolver.bringToSignatures(SootResolver.java:264)
    at soot.SootResolver.processResolveWorklist(SootResolver.java:168)
    at soot.SootResolver.resolveClass(SootResolver.java:129)
    at soot.Scene.tryLoadClass(Scene.java:675)
    at soot.Scene.loadBasicClasses(Scene.java:1272)
    at soot.Scene.loadNecessaryClasses(Scene.java:1351)
    at soot.Main.run(Main.java:243)
    at soot.Main.main(Main.java:147)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by pavanupb** [comment]
@bulburDE Please re-open the issue if this is still relevant.
