### ISSUE TITLE
[Call Graph] For information on where the call graph may be incomplete, use the verbose option to the cg phase.

### ISSUE THREAD

**Issue by XiaZhang0414** [soot-oss/soot#549]
Hi,
I was converting apk file to jimple files and then converting then back to the .dex file.

Soot version:
soot-trunk.jar

Command line:
java -Xmx2g -jar ./soot-trunk.jar soot.Main   -android-jars /usr/local/android-sdk-linux/platforms -w  -allow-phantom-refs -src-prec jimple -output-format dex  -process-dir ./sootOutput

Stack trace:
Warning: android.content.OperationApplicationException is a phantom class!
Warning: android.database.MatrixCursor$RowBuilder is a phantom class!
Warning: android.content.ContentProviderResult is a phantom class!
[Call Graph] For information on where the call graph may be incomplete, use the verbose option to the cg phase.
[Thread-1] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: null
[Thread-8] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: null
[Thread-7] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: null
java.lang.NullPointerException
    at soot.toolkits.graph.UnitGraph.<init>(UnitGraph.java:76)
    at soot.toolkits.graph.ExceptionalUnitGraph.<init>(ExceptionalUnitGraph.java:158)
    at soot.jimple.toolkits.scalar.UnreachableCodeEliminator.internalTransform(UnreachableCodeEliminator.java:79)
    at soot.BodyTransformer.transform(BodyTransformer.java:51)
    at soot.Transform.apply(Transform.java:105)
    at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:61)
    at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:95)
    at soot.Pack.apply(Pack.java:125)
    at soot.jimple.JimpleMethodSource.getBody(JimpleMethodSource.java:49)
    at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
    at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
    at soot.PackManager$3.run(PackManager.java:1223)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
[Thread-6] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: null
java.lang.NullPointerException
    at soot.toolkits.graph.UnitGraph.<init>(UnitGraph.java:76)
    at soot.toolkits.graph.ExceptionalUnitGraph.<init>(ExceptionalUnitGraph.java:158)
    at soot.jimple.toolkits.scalar.UnreachableCodeEliminator.internalTransform(UnreachableCodeEliminator.java:79)
    at soot.BodyTransformer.transform(BodyTransformer.java:51)
    at soot.Transform.apply(Transform.java:105)
    at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:61)
    at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:95)
    at soot.Pack.apply(Pack.java:125)
    at soot.jimple.JimpleMethodSource.getBody(JimpleMethodSource.java:49)
    at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
    at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
    at soot.PackManager$3.run(PackManager.java:1223)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
[Thread-4] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: null
java.lang.NullPointerException
    at soot.toolkits.graph.UnitGraph.<init>(UnitGraph.java:76)
    at soot.toolkits.graph.ExceptionalUnitGraph.<init>(ExceptionalUnitGraph.java:158)
    at soot.jimple.toolkits.scalar.UnreachableCodeEliminator.internalTransform(UnreachableCodeEliminator.java:79)
    at soot.BodyTransformer.transform(BodyTransformer.java:51)
    at soot.Transform.apply(Transform.java:105)
    at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:61)
    at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:95)
    at soot.Pack.apply(Pack.java:125)
    at soot.jimple.JimpleMethodSource.getBody(JimpleMethodSource.java:49)
    at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
    at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
    at soot.PackManager$3.run(PackManager.java:1223)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
    at soot.toolkits.graph.UnitGraph.<init>(UnitGraph.java:76)
    at soot.toolkits.graph.ExceptionalUnitGraph.<init>(ExceptionalUnitGraph.java:158)
    at soot.jimple.toolkits.scalar.UnreachableCodeEliminator.internalTransform(UnreachableCodeEliminator.java:79)
    at soot.BodyTransformer.transform(BodyTransformer.java:51)
    at soot.Transform.apply(Transform.java:105)
    at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:61)
    at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:95)
    at soot.Pack.apply(Pack.java:125)
    at soot.jimple.JimpleMethodSource.getBody(JimpleMethodSource.java:49)
    at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
    at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
    at soot.PackManager$3.run(PackManager.java:1223)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-1" java.lang.NullPointerException
    at soot.toolkits.graph.UnitGraph.<init>(UnitGraph.java:76)
    at soot.toolkits.graph.ExceptionalUnitGraph.<init>(ExceptionalUnitGraph.java:158)
    at soot.jimple.toolkits.scalar.UnreachableCodeEliminator.internalTransform(UnreachableCodeEliminator.java:79)
    at soot.BodyTransformer.transform(BodyTransformer.java:51)
    at soot.Transform.apply(Transform.java:105)
    at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:61)
    at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:95)
    at soot.Pack.apply(Pack.java:125)
    at soot.jimple.JimpleMethodSource.getBody(JimpleMethodSource.java:49)
    at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
    at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
    at soot.PackManager$3.run(PackManager.java:1223)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
java.util.concurrent.RejectedExecutionException: Task soot.PackManager$3@66a7b281 rejected from heros.solver.CountingThreadPoolExecutor@77a70b64[Shutting down, pool size = 4, active threads = 4, queued tasks = 0, completed tasks = 155]
    at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2048)
    at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:821)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1372)
    at heros.solver.CountingThreadPoolExecutor.execute(CountingThreadPoolExecutor.java:51)
    at soot.PackManager.retrieveAllBodies(PackManager.java:1219)
    at soot.PackManager.runPacksNormally(PackManager.java:463)
    at soot.PackManager.runPacks(PackManager.java:396)
    at soot.Main.run(Main.java:271)
    at soot.Main.main(Main.java:147)
Exception in thread "Thread-8" java.lang.NullPointerException
    at soot.toolkits.graph.UnitGraph.<init>(UnitGraph.java:76)
    at soot.toolkits.graph.ExceptionalUnitGraph.<init>(ExceptionalUnitGraph.java:158)
    at soot.jimple.toolkits.scalar.UnreachableCodeEliminator.internalTransform(UnreachableCodeEliminator.java:79)
    at soot.BodyTransformer.transform(BodyTransformer.java:51)
    at soot.Transform.apply(Transform.java:105)
    at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:61)
    at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:95)
    at soot.Pack.apply(Pack.java:125)
    at soot.jimple.JimpleMethodSource.getBody(JimpleMethodSource.java:49)
    at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
    at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
    at soot.PackManager$3.run(PackManager.java:1223)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
    at soot.toolkits.graph.UnitGraph.<init>(UnitGraph.java:76)
    at soot.toolkits.graph.ExceptionalUnitGraph.<init>(ExceptionalUnitGraph.java:158)
    at soot.jimple.toolkits.scalar.UnreachableCodeEliminator.internalTransform(UnreachableCodeEliminator.java:79)
    at soot.BodyTransformer.transform(BodyTransformer.java:51)
    at soot.Transform.apply(Transform.java:105)
    at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:61)
    at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:95)
    at soot.Pack.apply(Pack.java:125)
    at soot.jimple.JimpleMethodSource.getBody(JimpleMethodSource.java:49)
    at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
    at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
    at soot.PackManager$3.run(PackManager.java:1223)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-4" java.lang.NullPointerException
    at soot.toolkits.graph.UnitGraph.<init>(UnitGraph.java:76)
    at soot.toolkits.graph.ExceptionalUnitGraph.<init>(ExceptionalUnitGraph.java:158)
    at soot.jimple.toolkits.scalar.UnreachableCodeEliminator.internalTransform(UnreachableCodeEliminator.java:79)
    at soot.BodyTransformer.transform(BodyTransformer.java:51)
    at soot.Transform.apply(Transform.java:105)
    at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:61)
    at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:95)
    at soot.Pack.apply(Pack.java:125)
    at soot.jimple.JimpleMethodSource.getBody(JimpleMethodSource.java:49)
    at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
    at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
    at soot.PackManager$3.run(PackManager.java:1223)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-7" java.lang.NullPointerException
    at soot.toolkits.graph.UnitGraph.<init>(UnitGraph.java:76)
    at soot.toolkits.graph.ExceptionalUnitGraph.<init>(ExceptionalUnitGraph.java:158)
    at soot.jimple.toolkits.scalar.UnreachableCodeEliminator.internalTransform(UnreachableCodeEliminator.java:79)
    at soot.BodyTransformer.transform(BodyTransformer.java:51)
    at soot.Transform.apply(Transform.java:105)
    at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:61)
    at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:95)
    at soot.Pack.apply(Pack.java:125)
    at soot.jimple.JimpleMethodSource.getBody(JimpleMethodSource.java:49)
    at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
    at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
    at soot.PackManager$3.run(PackManager.java:1223)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-6" java.lang.NullPointerException
    at soot.toolkits.graph.UnitGraph.<init>(UnitGraph.java:76)
    at soot.toolkits.graph.ExceptionalUnitGraph.<init>(ExceptionalUnitGraph.java:158)
    at soot.jimple.toolkits.scalar.UnreachableCodeEliminator.internalTransform(UnreachableCodeEliminator.java:79)
    at soot.BodyTransformer.transform(BodyTransformer.java:51)
    at soot.Transform.apply(Transform.java:105)
    at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:61)
    at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:95)
    at soot.Pack.apply(Pack.java:125)
    at soot.jimple.JimpleMethodSource.getBody(JimpleMethodSource.java:49)
    at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
    at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
    at soot.PackManager$3.run(PackManager.java:1223)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

**Comment by XiaZhang0414** [comment]
soot-trunk version: the nightly build of Mar 7.

**Comment by pavanupb** [comment]
@XiaZhang0414 Please re-open if this is still relevant.
