### ISSUE TITLE
Semantic Error: duplicate type B in package artifacts

### ISSUE THREAD

**Issue by esherman77** [soot-oss/soot#568]
It looks like the issue stated at github.com/Sable/soot/issues/141 has re-appeared. When class A uses class B then soot gives the following error:

Semantic Error: duplicate type B in package artifacts
soot.CompilationDeathException: there were errors during parsing and/or type checking (JastAdd frontend)
    at soot.JastAddInitialResolver.formAst(JastAddInitialResolver.java:63)
    at soot.JavaClassSource.resolve(JavaClassSource.java:54)
    at soot.SootResolver.bringToHierarchy(SootResolver.java:239)
    at soot.SootResolver.bringToSignatures(SootResolver.java:266)
    at soot.SootResolver.processResolveWorklist(SootResolver.java:170)
    at soot.SootResolver.resolveClass(SootResolver.java:131)
    at soot.Scene.loadClass(Scene.java:725)
    at soot.Scene.loadClassAndSupport(Scene.java:711)
    at soot.Scene.loadNecessaryClass(Scene.java:1425)
    at soot.Scene.loadNecessaryClasses(Scene.java:1436)
    at soot.Main.run(Main.java:243)
    at soot.Main.main(Main.java:147)
    at encapsulation.MainEcapsulate.main(MainEcapsulate.java:25)

**Comment by StevenArzt** [comment]
Are you loading source code or bytecode into Soot? This looks like the JastAdd frontend for Java source is active. Is this intentional? Please give your complete Soot command line. Do you happen to have source code and bytecode for the same class in your Soot classpath?

**Comment by esherman77** [comment]
The source code is loading into Soot, not classfiles. Only the path to the source files is added to Soot classpath. The intention is to work with source files.  Here is the code that invokes Soot's main method:
```
String[] sootArgs = {"-f", "J","artifacts.A"};
String pwd = System.getProperty("user.dir");
Scene.v().setSootClassPath(Scene.v().getSootClassPath() + System.getProperty("path.separator")+
				System.getProperty("sun.boot.class.path")+ System.getProperty("path.separator")+
 pwd+"/sourcecode/transformer");
Main.main(sootArgs);
```
And here are the classes:
```
package artifacts;
public class A {
	
	int m;
	int n;
	
	public A(){
		m = 0;
		n = -1;
	}

	public void calc(){
		B b = new B();
		m = b.i + n;
	}
	
	public static void main(String[] args){
		
		A a = new A();
		a.calc();
		
	}
}
```
And B class
```
package artifacts;

public class B {
	
	int i;
	int j;
	
	public B(){
		i = 0;
		j = -1;
	}

}
```

**Comment by pavanupb** [comment]
@esherman77 Please re-open the issue if this is still relevant.
