### ISSUE TITLE
IllegalArgumentException concerning Opcode {SHL_INT_LIT16, INVOKE_SUPER_QUICK @ 0x15,IGET_QUICK @ 0x5e} 

### ISSUE THREAD

**Issue by jpeisenbarth** [soot-oss/soot#578]
Hello,

I got exceptions when running soot with some Android APK (4 different APK).

They all concern Opcode :

<pre>java.lang.IllegalArgumentException: No enum constant org.jf.dexlib2.Opcode.SHL_INT_LIT16
    at java.lang.Enum.valueOf(Enum.java:236)
    at org.jf.dexlib2.Opcode.valueOf(Opcode.java:42)
    at soot.toDex.ExprVisitor.buildLit16BinaryInsn(ExprVisitor.java:327)
        ...
</pre>

<pre>java.lang.IllegalArgumentException: Opcode: INVOKE_SUPER_QUICK @ 0x15
    at soot.dexpler.instructions.InstructionFactory.fromOpcode(InstructionFactory.java:370)
    at soot.dexpler.instructions.InstructionFactory.fromInstruction(InstructionFactory.java:44)
    at soot.dexpler.DexBody.<init>(DexBody.java:188)
        ...
</pre>

<pre>Caused by: java.lang.IllegalArgumentException: Opcode: IGET_QUICK @ 0x5e
    at soot.dexpler.instructions.InstructionFactory.fromOpcode(InstructionFactory.java:370)
    at soot.dexpler.instructions.InstructionFactory.fromInstruction(InstructionFactory.java:44)
    at soot.dexpler.DexBody.<init>(DexBody.java:188)
</pre>

I didn't found any discussion about these exceptions concerning these Opcode.

Tell me if you need more information.

Thank you in advance.

**Comment by pavanupb** [comment]
@jpeisenbarth Please re-open the issue if this is still relevant.
