### ISSUE TITLE
ERROR heros.solver.CountingThreadPoolExecutor - when converting jimple to class.

### ISSUE THREAD

**Issue by ZhengqiaoLi** [soot-oss/soot#593]
Hi,all
I want to convert jimple to class,but met some errors.
Error message:
`
[Thread-4] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: null
java.lang.NullPointerException
    at soot.toolkits.graph.UnitGraph.<init>(UnitGraph.java:76)
    at soot.toolkits.graph.ExceptionalUnitGraph.<init>(ExceptionalUnitGraph.java:158)
    at soot.jimple.toolkits.scalar.UnreachableCodeEliminator.internalTransform(UnreachableCodeEliminator.java:79)
    at soot.BodyTransformer.transform(BodyTransformer.java:51)
    at soot.Transform.apply(Transform.java:105)
    at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:61)
    at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:95)
    at soot.Pack.apply(Pack.java:125)
    at soot.jimple.JimpleMethodSource.getBody(JimpleMethodSource.java:49)
    at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
    at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
    at soot.PackManager$3.run(PackManager.java:1223)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
......
`
My eclipse program arguments:
`
-w
-process-dir G:\\eclipse_Java\\Java_MulClass\\sootOutput
-android-jars G:\\Soot\\sdk\\platforms\\
`
Some Options:
`
Options.v().set_src_prec(Options.src_prec_jimple);
Options.v().set_output_format(Options.output_format_class);
Options.v().set_soot_classpath(......)
`
Can you help me?

**Comment by pavanupb** [comment]
@ZhengqiaoLi Please re-open the issue if this is still relevant.
