### ISSUE TITLE
Soot does not report calls to library method

### ISSUE THREAD

**Issue by edwardmp** [soot-oss/soot#602]
Hi,

I'm trying to create a call graph. Due to an earlier issue with Java 8 on Mac OS X (#581) I know use rt.jar and jce.jar from the Java 7 runtime.

Here's my code:

```
 List<String> argsList = new ArrayList<>(Arrays.asList(args));
        argsList.addAll(Arrays.asList(new String[]{
                "-soot-classpath",
                "/private/tmp/dependencies/aevastestapp/netty-3.9.1.1.Final.jar:/Users/Edward/Dropbox/Desktop SIG/legacy/sig/aevastestapp/aevastestapp-1/target/aevastestapp-1.0-SNAPSHOT.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/jre/lib/jce.jar",
                "-p",
                "cg",
                "library:disabled",
                "-p",
                "cg",
                "verbose:true",
                "-w",
                "eu.sig.aevastestapp.DiscardServerHandler"
        }));


        PackManager.v().getPack("wjtp").add(new Transform("wjtp.myTrans", new SceneTransformer() {

            @Override
            protected void internalTransform(String phaseName, Map options) {
                CHATransformer.v().transform();


                for (SootClass sootClass : Scene.v().getClasses()) {
                    // System.out.println(sootClass.getName());
                    if (!sootClass.getName().equals("eu.sig.aevastestapp.DiscardServerHandler"))
                        continue;

                    for (SootMethod method : sootClass.getMethods()) {

                        System.out.println(method.getName());
                        if (method.getName().equals("main")) {
                            SootMethod src = sootClass.getMethodByName("main");

                            CallGraph cg = Scene.v().getCallGraph();


                            Iterator<MethodOrMethodContext> targets = new TransitiveTargets(cg).iterator(src);
                            while (targets.hasNext()) {
                                SootMethod tgt = (SootMethod) targets.next();
                                System.out.println(src + " may call " + tgt);
                            }

                        }
                    }
                }

            }

        }));

        args = argsList.toArray(new String[0]);

        soot.Main.main(args);
```

My main calls a library method, which in turn calls another method of the Netty library, which calls another method in the same class, which calls the method in the same class I'm interested of knowing if its called from main. However, Soot does not report any 'may calls' for this method.

By the way, does soot support Java 8 systems? Because https://sable.github.io/soot/ says it supports code up to Java 7.

**Comment by edwardmp** [comment]
I may have used the wrong method, this seems to do what I want:
```
 Iterator<MethodOrMethodContext> targets = new Targets(cg.edgesOutOf(src));

                            ReachableMethods reachableMethods = new ReachableMethods(cg, targets);
                            QueueReader<MethodOrMethodContext> transitiveMethods = reachableMethods.listener();
                            reachableMethods.update();
                            System.out.println("Num transitive methods " + reachableMethods.size());
                            while (transitiveMethods.hasNext()) {
                                System.out.println(src + " may reach " + ((SootMethod) transitiveMethods.next()).getName());

                            }
```
But when I try using source files as input opposed to a JAR it leads to an exception, maybe because source is Java 8?

```
java.lang.ClassCastException: soot.JastAddJ.CONSTANT_Utf8_Info cannot be cast to soot.JastAddJ.CONSTANT_Class_Info
	at soot.JastAddJ.BytecodeParser.parseThisClass(BytecodeParser.java:437)
	at soot.JastAddJ.BytecodeParser.parseTypeDecl(BytecodeParser.java:404)
	at soot.JastAddJ.BytecodeParser.parse(BytecodeParser.java:331)
	at soot.JastAddJ.BytecodeParser.parse(BytecodeParser.java:301)
	at soot.JastAddJ.Attributes$TypeAttributes.innerClasses(Attributes.java:412)
	at soot.JastAddJ.Attributes$TypeAttributes.processAttribute(Attributes.java:316)
	at soot.JastAddJ.Attributes.attributes(Attributes.java:61)
	at soot.JastAddJ.Attributes$TypeAttributes.<init>(Attributes.java:307)
	at soot.JastAddJ.BytecodeParser.parse(BytecodeParser.java:337)
	at soot.JastAddJ.BytecodeParser.read(BytecodeParser.java:27)
	at soot.JastAddJ.PathPart.getCompilationUnit(PathPart.java:115)
	at soot.JastAddJ.Program.getCompilationUnit(Program.java:858)
	at soot.JastAddJ.Program.getLibCompilationUnit_compute(Program.java:1531)
	at soot.JastAddJ.Program.getLibCompilationUnit(Program.java:1514)
	at soot.JastAddJ.Program.lookupLibType_compute(Program.java:1479)
	at soot.JastAddJ.Program.lookupLibType(Program.java:1447)
	at soot.JastAddJ.Program.lookupType_compute(Program.java:1426)
	at soot.JastAddJ.Program.lookupType(Program.java:1407)
	at soot.JastAddJ.Program.Define_TypeDecl_lookupType(Program.java:1995)
	at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
	at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
	at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
	at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
	at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
	at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
	at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
	at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
	at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
	at soot.JastAddJ.Expr.lookupType(Expr.java:1186)
	at soot.JastAddJ.TypeAccess.decls_compute(TypeAccess.java:425)
	at soot.JastAddJ.TypeAccess.decls(TypeAccess.java:414)
	at soot.JastAddJ.TypeAccess.refined_TypeScopePropagation_TypeAccess_decl(TypeAccess.java:387)
	at soot.JastAddJ.TypeAccess.decl_compute(TypeAccess.java:460)
	at soot.JastAddJ.TypeAccess.decl(TypeAccess.java:452)
	at soot.JastAddJ.TypeAccess.type_compute(TypeAccess.java:590)
	at soot.JastAddJ.TypeAccess.type(TypeAccess.java:583)
	at soot.JastAddJ.ParTypeAccess.genericDecl(ParTypeAccess.java:402)
	at soot.JastAddJ.ParTypeAccess.type_compute(ParTypeAccess.java:382)
	at soot.JastAddJ.ParTypeAccess.type(ParTypeAccess.java:374)
	at soot.JastAddJ.ParameterDeclaration.type_compute(ParameterDeclaration.java:479)
	at soot.JastAddJ.ParameterDeclaration.type(ParameterDeclaration.java:472)
	at soot.JastAddJ.MethodDecl.signature_compute(MethodDecl.java:1355)
	at soot.JastAddJ.MethodDecl.signature(MethodDecl.java:1343)
	at soot.JastAddJ.TypeDecl.localMethodsSignatureMap_compute(TypeDecl.java:2527)
	at soot.JastAddJ.TypeDecl.localMethodsSignatureMap(TypeDecl.java:2515)
	at soot.JastAddJ.ClassDecl.methodsSignatureMap_compute(ClassDecl.java:1102)
	at soot.JastAddJ.ClassDecl.methodsSignatureMap(ClassDecl.java:1094)
	at soot.JastAddJ.TypeDecl$2.<init>(TypeDecl.java:468)
	at soot.JastAddJ.TypeDecl.methodsIterator(TypeDecl.java:467)
	at soot.JastAddJ.ClassDecl.methodsSignatureMap_compute(ClassDecl.java:1104)
	at soot.JastAddJ.ClassDecl.methodsSignatureMap(ClassDecl.java:1094)
	at soot.JastAddJ.TypeDecl$2.<init>(TypeDecl.java:468)
	at soot.JastAddJ.TypeDecl.methodsIterator(TypeDecl.java:467)
	at soot.JastAddJ.TypeDecl.methodsNameMap_compute(TypeDecl.java:2468)
	at soot.JastAddJ.TypeDecl.methodsNameMap(TypeDecl.java:2459)
	at soot.JastAddJ.TypeDecl.memberMethods(TypeDecl.java:2431)
	at soot.JastAddJ.AbstractDot.Define_Collection_lookupMethod(AbstractDot.java:766)
	at soot.JastAddJ.Expr.lookupMethod(Expr.java:1032)
	at soot.JastAddJ.MethodAccess.decls_compute(MethodAccess.java:1094)
	at soot.JastAddJ.MethodAccess.decls(MethodAccess.java:1086)
	at soot.JastAddJ.MethodAccess.decl_compute(MethodAccess.java:1128)
	at soot.JastAddJ.MethodAccess.decl(MethodAccess.java:1120)
	at soot.JastAddJ.MethodAccess.nameCheck(MethodAccess.java:206)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1283)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.CompilationUnit.errorCheck(CompilationUnit.java:178)
	at soot.JastAddInitialResolver.formAst(JastAddInitialResolver.java:58)
	at soot.JavaClassSource.resolve(JavaClassSource.java:54)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:242)
	at soot.SootResolver.bringToSignatures(SootResolver.java:269)
	at soot.SootResolver.bringToBodies(SootResolver.java:307)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:166)
	at soot.SootResolver.resolveClass(SootResolver.java:134)
	at soot.Scene.loadClass(Scene.java:745)
	at soot.Scene.loadClassAndSupport(Scene.java:730)
	at soot.Scene.loadNecessaryClasses(Scene.java:1468)
	at soot.Main.run(Main.java:243)
	at soot.Main.main(Main.java:147)
	at eu.sig.aevas.Wala.main(Wala.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by pavanupb** [comment]
@edwardmp Please re-open the issue if this is still relevant.
