### ISSUE TITLE
Exceptions while running 'tradebeans' and 'tradesoap' on DaCapo 9.12

### ISSUE THREAD

**Issue by sridhargopinath** [soot-oss/soot#651]
Hi,

I am trying to analyze 'tradebeans' and 'tradesoap' programs from the dacapo-9.12-bach benchmark using Tamiflex 2.0.3, soot-trunk and java-8.

While executing using the play-out agent, I get the following exception:
`
Exception in thread "Thread-0" java.lang.IllegalStateException: ClassReader.accept() should be called with EXPAND_FRAMES flag
        at org.objectweb.asm.commons.LocalVariablesSorter.visitFrame(Unknown Source)
        at org.objectweb.asm.commons.RemappingMethodAdapter.visitFrame(Unknown Source)
        at org.objectweb.asm.MethodAdapter.visitFrame(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at de.bodden.tamiflex.normalizer.Hasher.generateHashNumber(Hasher.java:99)
        at de.bodden.tamiflex.playout.ClassDumper.writeClassesToDisk(ClassDumper.java:84)
        at de.bodden.tamiflex.playout.Agent$1.run(Agent.java:123)
`

I felt this might be because of the normalization of the class names done by Tamiflex. I switched it off and tried running the programs again.
The play-out agent finished successfully, but the soot analysis failed. I encountered the following exception:

`
java.lang.RuntimeException: Failed to convert <net.sf.cglib.proxy.Enhancer$EnhancerKey$$KeyFactoryByCGLIB$$7fb24d72: int hashCode()>
    at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:1773)
    at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
    at soot.SootMethod.retrieveActiveBody(SootMethod.java:326)
    at soot.jimple.toolkits.annotation.LineNumberAdder.internalTransform(LineNumberAdder.java:44)
    at soot.PackManager.runPacksNormally(PackManager.java:465)
    at soot.PackManager.runPacks(PackManager.java:398)
    at soot.Main.run(Main.java:271)
    at soot.Main.main(Main.java:147)
    at wpt.Main.main(Main.java:68)
Caused by: java.lang.AssertionError: Multiple un-equal stacks!
    at soot.asm.AsmMethodSource.addEdges(AsmMethodSource.java:1543)
    at soot.asm.AsmMethodSource.convert(AsmMethodSource.java:1595)
    at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:1771)
    ... 8 more
`

Can you please look into this and let me know how to fix this?

**Comment by pavanupb** [comment]
@sridhargopinath Please re-open the issue if this is still relevant.
