### ISSUE TITLE
Exception in HashChain when outputting the classes in a dex file to jimple

### ISSUE THREAD

**Issue by agorski3** [soot-oss/soot#653]
I received the following exception when trying to output the classes in a dex file to jimple. This is from android 6.0.1_r1 and the offending dex file can be found here [MediaProvider.zip](https://github.com/Sable/soot/files/524724/MediaProvider.zip).

[main] Dex2Soot: Failed to output jimple for class 'com.android.providers.media.MediaProvider' to file
'com\android\providers\media\MediaProvider.jimple' for dex file 'MediaProvider_classes.dex'

java.util.NoSuchElementException: HashChain.LinkIterator.next() reached end of chain without reaching specified tail unit
    at soot.util.HashChain$LinkIterator.next(HashChain.java:697)
    at soot.PatchingChain$PatchingIterator.next(PatchingChain.java:279)
    at soot.PatchingChain$PatchingIterator.next(PatchingChain.java:1)
    at soot.toolkits.graph.ExceptionalUnitGraph.buildExceptionDests(ExceptionalUnitGraph.java:344)
    at soot.toolkits.graph.ExceptionalUnitGraph.initialize(ExceptionalUnitGraph.java:272)
    at soot.toolkits.graph.ExceptionalUnitGraph.<init>(ExceptionalUnitGraph.java:159)
    at soot.dexpler.TrapMinimizer.internalTransform(TrapMinimizer.java:60)
    at soot.BodyTransformer.transform(BodyTransformer.java:59)
    at soot.BodyTransformer.transform(BodyTransformer.java:64)
    at soot.dexpler.DexBody.jimplify(DexBody.java:693)
    at soot.dexpler.DexMethod$1.getBody(DexMethod.java:150)
    at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
    at soot.SootMethod.retrieveActiveBody(SootMethod.java:326)
    at soot.Printer.printTo(Printer.java:207)
    at org.sag.sje.soot.Dex2Soot.main(Dex2Soot.java:63)

**Comment by pavanupb** [comment]
@agorski3 Please re-open the issue if this is still relevant.
