### ISSUE TITLE
JAS Error Badly formatted number: -Infinity.

### ISSUE THREAD

**Issue by winkar** [soot-oss/soot#674]
**VERSION**
Nightly build, trunk version

**CMD**
java -Xss50m -Xmx2500m soot.Main -d /home/winkar/apk/Classes -android-jars /home/winkar/Code/Explorer/apk-preprocess-tool/tools/android-platforms -allow-phantom-refs -src-prec apk -process-dir /home/winkar/apk/helo.apk

**LOG**
Writing to /home/winkar/apk/classes/android/support/v4/widget/SlidingPaneLayout$SimplePanelSlideListener.class
Writing to /home/winkar/apk/classes/android/support/v4/app/RemoteInput$ImplBase.class
Writing to /home/winkar/apk/classes/android/support/annotation/FloatRange.class
Jasmin:23: JAS Error Badly formatted number: -Infinity.

^
jas.jasError: Badly formatted number: -Infinity
        at jasmin.Scanner.tryParseAsNumber(Scanner.java:379)
        at jasmin.Scanner.next_token(Scanner.java:308)
        at jasmin.parser.scan(parser.java:121)
        at java_cup.runtime.lr_parser.parse(lr_parser.java:693)
        at jasmin.ClassFile.readJasmin(ClassFile.java:1268)
        at jasmin.Main.assemble(Main.java:31)
        at soot.util.JasminOutputStream.flush(JasminOutputStream.java:35)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at java.io.PrintWriter.flush(PrintWriter.java:320)
        at soot.PackManager.writeClass(PackManager.java:1159)
        at soot.PackManager.access$100(PackManager.java:138)
        at soot.PackManager$2.run(PackManager.java:675)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Jasmin: Found 1 errors
Writing to /home/winkar/apk/classes/android/support/v4/view/ScaleGestureDetectorCompat$ScaleGestureDetectorCompatKitKatImpl.class
Writing to /home/winkar/apk/classes/android/support/v4/media/MediaBrowserServiceCompat$ConnectionRecord.class
Writing to /home/winkar/apk/classes/android/support/v4/app/ActivityCompat.class
Writing to /home/winkar/apk/classes/android/support/v4/print/PrintHelperKitkat.class

**Comment by winkar** [comment]
apk sent to steven.arzt@cased.de

**Comment by ftc** [comment]
Just a note I am also having this issue, I can provide an APK if needed.

**Comment by ftc** [comment]
I created a version of jasmin which recognizes the "-Infinity" here:
https://github.com/ftc/jasmin
I am not sure if this is the right way to fix it or not but it got rid of this particular error for me.

**Comment by pavanupb** [comment]
@winkar Please re-open the issue if this is still relevant.
