### ISSUE TITLE
Issue in instrumentation

### ISSUE THREAD

**Issue by jyotigajrani** [soot-oss/soot#693]
I am trying to instrument a Log instruction which log current class name whenever some call to API lets say X.
I done the code like:

```
                                   Local tmpRef1;
					Local tmpRef2 = addTmpRef2(b,"java.lang.String");
/* I added this try catch as many times getThisLocal() was giving error while instrumenting. like java.lang.RuntimeException: couldn't find identityref! in <org.openintents.safe.PRNGFixes: void applyOpenSSLFix()> at soot.Body.getThisLocal(Body.java:307) 	at AndroidInstrumentthis$1$1.caseAssignStmt(AndroidInstrumentthis.java:106)
	at soot.jimple.internal.JAssignStmt.apply(JAssignStmt.java:238)
*/
					try{
					        tmpRef1 = b.getThisLocal();
					}
					catch(Exception e)
					{
				//adding local of class type in this as it's not given by above call.	 
                               tmpRef1 =addTmpRef1(b,b.getMethod().getDeclaringClass(););					
					}
                                        SootClass counterClass = Scene.v().loadClassAndSupport("java.lang.Object");
					SootMethod toCall1 = counterClass.getMethod("java.lang.String toString()");
					InvokeExpr expr= Jimple.v().newVirtualInvokeExpr(tmpRef1,     toCall1.makeRef());
					Stmt invokeStmt = Jimple.v().newAssignStmt(tmpRef2,expr);
					ArrayList<Value> argList = new ArrayList<Value>();
					ArrayList<Object> args = new ArrayList<Object>();
					Value logType=StringConstant.v("COMPLETECLASSNAME: ");
					args.add(logType);
					
					args.add((Value)tmpRef2);
							
					for (int i = 0; i < args.size(); i++)
					argList.add((Value) args.get(i));
					
					SootClass sootClass = Scene.v().loadClassAndSupport("android.util.Log");
					
					SootMethod valueOfMethod = sootClass.getMethod("int d(java.lang.String,java.lang.String)");
					
					StaticInvokeExpr stmt1 = Jimple.v().newStaticInvokeExpr(valueOfMethod.makeRef(),argList);
					Unit generated = Jimple.v().newInvokeStmt(stmt1);` 

```
After the try-catch instrumentation was successful without exception. But some times app won't run and Unfortunately stops. As far as I noticed when the catch block executes, it adds local of bottom_type type which is creating problem. 
Please help to solve the problem.
Thanks in advance
Jyoti

**Comment by pavanupb** [comment]
@jyotigajrani Closed due to inactivity. Please re-open if still relevant.
