### ISSUE TITLE
Wrong static-ness Exception  with some Android apks

### ISSUE THREAD

**Issue by antoniobianchi333** [soot-oss/soot#717]
When analyzing some apks I get the following error:
```
[Thread-8] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: Resolved <android.support.v4.content.a: java.io.File i(android.content.Context)> to <android.support.v4.content.a: java.io.File i(android.content.Context)> which has wrong static-ness
soot.ResolutionFailedException: Resolved <android.support.v4.content.a: java.io.File i(android.content.Context)> to <android.support.v4.content.a: java.io.File i(android.content.Context)> which has wrong static-ness
	at soot.SootMethodRefImpl.checkStatic(SootMethodRefImpl.java:123)
	at soot.SootMethodRefImpl.tryResolve(SootMethodRefImpl.java:138)
	at soot.SootMethodRefImpl.tryResolve(SootMethodRefImpl.java:118)
	at soot.toolkits.exceptions.UnitThrowAnalysis.mightThrow(UnitThrowAnalysis.java:301)
	at soot.toolkits.exceptions.UnitThrowAnalysis$ValueSwitch.caseInstanceInvokeExpr(UnitThrowAnalysis.java:1131)
	at soot.toolkits.exceptions.UnitThrowAnalysis$ValueSwitch.caseVirtualInvokeExpr(UnitThrowAnalysis.java:976)
	at soot.jimple.internal.AbstractVirtualInvokeExpr.apply(AbstractVirtualInvokeExpr.java:79)
...
```

This is the code I run:
```Java
Options.v().set_android_jars("/tmp/Android/Sdk/platforms");
Options.v().set_process_multiple_dex(true);
Options.v().set_src_prec(Options.src_prec_apk);
Options.v().set_output_format(Options.output_format_shimple);
Options.v().set_allow_phantom_refs(true);
Options.v().set_process_dir(Collections.singletonList("/tmp/com.vzw.hss.myverizon-12.7.9.apk"));
//available here: http://www.apkmirror.com/apk/verizon-vz/my-verizon-mobile/my-verizon-mobile-12-7-9-release/my-verizon-12-7-9-android-apk-download/download/

//I tried all these 3 options
//Options.v().set_wrong_staticness(Options.wrong_staticness_fix); //this is the default option 
Options.v().set_wrong_staticness(Options.wrong_staticness_ignore);
//Options.v().set_wrong_staticness(Options.wrong_staticness_fail);

Scene.v().loadNecessaryClasses();
PackManager.v().runPacks();
```

I am using the latest soot-trunk.jar.
I saw that the code handling this problem has been updated recently (eee5e8cd52927b91a9b521ee62e7998648d51a0a) but it still seems to fail in some cases.

Using the different `Options.v().set_wrong_staticnes` options does not seem to fix the issue.

**Comment by pavanupb** [comment]
@antoniobianchi333 Closed due to inactivity. Please re-open if still relevant.
