### ISSUE TITLE
Spark geomPTA NPE

### ISSUE THREAD

**Issue by Waldo1637** [soot-oss/soot#730]
Test case:
```
public static void main(String[] args) {
    System.out.println("hello " + args[0]);
}
```

Running Soot in whole-shimple mode with cg.spark enabled and geom-pta enabled, the following output+exception is given:

```
[Spark] Pointer Assignment Graph in 0.2 seconds.
[Spark] Type masks in 0.0 seconds.
[Spark] Pointer Graph simplified in 0.0 seconds.
[Spark] Propagation in 0.0 seconds.
[Spark] Solution found in 0.0 seconds.
[Call Graph] For information on where the call graph may be incomplete, use the verbose option to the cg phase.

[Spark] Time: 0.008 s
[Spark] Memory: 86.9 MB
[Geom] Start working on <NoName> with <Geom> encoding.

[Geom] Propagation Round 0 ==> 
Reachable Methods = 80, in which #Condensed Nodes = 80, #Full Context Nodes = 0 
Maximum SCC = 1 
The maximum context size = 5.000000e+00
java.lang.NullPointerException
	at soot.jimple.spark.geom.geomE.FullSensitiveNodeGenerator.initFlowGraph(FullSensitiveNodeGenerator.java:103)
	at soot.jimple.spark.geom.geomPA.GeomPointsTo.solve(GeomPointsTo.java:1324)
	at soot.jimple.spark.SparkTransformer.internalTransform(SparkTransformer.java:189)
	at soot.SceneTransformer.transform(SceneTransformer.java:39)
	at soot.Transform.apply(Transform.java:90)
	at soot.RadioScenePack.internalApply(RadioScenePack.java:57)
	at soot.jimple.toolkits.callgraph.CallGraphPack.internalApply(CallGraphPack.java:49)
	at soot.Pack.apply(Pack.java:118)
	at soot.PackManager.runWholeProgramPacks(PackManager.java:576)
	at soot.PackManager.runPacksNormally(PackManager.java:472)
	at soot.PackManager.runPacks(PackManager.java:401)
	at soot.Main.run(Main.java:278)
```

**Comment by pavanupb** [comment]
@Waldo1637 Closed due to inactivity. Please re-open if still relevant.
