### ISSUE TITLE
colons in .apk filename lead to RuntimeException

### ISSUE THREAD

**Issue by cmaeder** [soot-oss/soot#769]
I followed https://github.com/Sable/soot/wiki/Instrumenting-Android-Apps-with-Soot using https://github.com/Sable/soot/wiki/code/androidinstr/AndroidInstrument.java_.txt and https://soot-build.cs.uni-paderborn.de/nightly/soot/soot-trunk.jar from 09-Aug-2017 14:31 (13933707 bytes).

```
javac AndroidInstrument.java -cp soot-trunk.jar
java -cp soot-trunk.jar:. AndroidInstrument -android-jars platforms -process-dir test\:2.apk
```
resulted in the following crash, whereas renaming test\:2.apk to test.apk made it go through. I suspect that the -process-dir is (wrongly) treated like a part of the classpath and splitted at the colons. 

```
Soot started on Mon Aug 14 15:16:32 CEST 2017
Using 'platforms/android-23/android.jar' as android.jar
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.Exception: Error: The path '/tmp/soot-instrument-android/test' does not exist.
	at soot.SourceLocator.getClassSourceType(SourceLocator.java:228)
	at soot.SourceLocator.lookupInClassPath(SourceLocator.java:726)
	at soot.asm.AsmClassProvider.find(AsmClassProvider.java:34)
	at soot.SourceLocator.getClassSource(SourceLocator.java:82)
	at soot.Scene.tryLoadClass(Scene.java:814)
	at soot.Scene.loadBasicClasses(Scene.java:1497)
	at soot.Scene.loadNecessaryClasses(Scene.java:1580)
	at soot.Main.run(Main.java:250)
	at soot.Main.main(Main.java:147)
	at AndroidInstrument.main(AndroidInstrument.java:81)
Caused by: java.util.concurrent.ExecutionException: java.lang.Exception: Error: The path '/tmp/soot-instrument-android/test' does not exist.
	at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:137)
	at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2348)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2320)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at soot.SourceLocator.getClassSourceType(SourceLocator.java:226)
	... 9 more
Caused by: java.lang.Exception: Error: The path '/tmp/soot-instrument-android/test' does not exist.
	at soot.SourceLocator$2.load(SourceLocator.java:205)
	at soot.SourceLocator$2.load(SourceLocator.java:200)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	... 15 more


Ouuups... something went wrong! Sorry about that.
Follow these steps to fix the problem:
1.) Are you sure you used the right command line?
    Click here to double-check:
    https://ssebuild.cased.de/nightly/soot/doc/soot_options.htm

2.) Not sure whether it's a bug? Feel free to discuss
    the issue on the Soot mailing list:
    https://github.com/Sable/soot/wiki/Getting-help

3.) Sure it's a bug? Click this link to report it.
...
```

**Comment by cmaeder** [comment]
P.S. The links to https://ssebuild.cased.de/ (in the error message and the above wiki page) do not work.

**Comment by cmaeder** [comment]
In `Scene.getSootClassPath` `process_dir` arguments are appended to the class path. Maybe this should not be done (for .apk files).

**Comment by cmaeder** [comment]
in 3 of 4 cases the classpath is splitted back into a list anyway, so keeping a list directly makes more sense.

**Comment by mbenz89** [comment]
I adapted the classpath parsing to accept escaped colons and updated the error message.
Let me know if that worked.

Thanks for contributing!
Manuel

**Comment by cmaeder** [comment]
I don't think this will work, because the colons in my .apk file are not escaped. (I only had to escape the colon in the filename to be able to pass it as argument.)

**Comment by mbenz89** [comment]
As far as I know, colons are not allowed in file names. The only way a colon can be in a path is if it is escaped. Probably your filemanager is just not showing the escape symbol. 
What happens if you are locating the apk in the console? The colon should be escaped there.

Anyways, why don't you just remove/escape the colons before passing the files to Soot?

**Comment by cmaeder** [comment]
Colons are allowed in file names, but file or directory names can not occur in a colon separated list like (environment variables) PATH or CLASSPATH. (Therefore adding process-dirs to an unexploded classpath string is wrong.)

The colon can only be escaped in the shell of the console to _address_ the file:

```
$ ls test\:2.apk
test:2.apk
```

The colon in the actual file name is unescaped.

Surely I can rename all my .apk files with a colon in their name, but initially I did not want to change the original file names . Unfortunately 

```
$ ls -1 test*
test:2.apk
test\:2.apk
test%3A2.apk
```

are all different file names. Maybe `test\:2.apk` works with your changes (if passed on the shell by `test\\\:2.apk`).

**Comment by mbenz89** [comment]
I'll investigate this when I have some time left. Thx for the explanation.
If you have an appropriate fix in mind, you are definitely welcome to set up a merge request for that.

Best,
Manuel

**Comment by cmaeder** [comment]
The `Scene.sootClassPath` should be kept as `List<String>`, but this has implications. In `SootResolver.initializeProgram` also a colon separated string is passed as classpath value.

**Comment by luckydonald** [comment]
Additional note, under macOS, a `:` in a filename is displayed as `/` in the Finder.

**Comment by pavanupb** [comment]
@cmaeder Please re-open if this issue is still relevant.

**Comment by luckydonald** [comment]
Funfact, if you use the colon `:` on Mac OS, it get's displayed as `/` in the Finder.


That is can be quite useful:
<img width="483" alt="image" src="https://user-images.githubusercontent.com/2737108/88594924-68180b00-d062-11ea-8a16-4e2754421671.png">
