### ISSUE TITLE
These two apks are crashing after a simple unpack/repack with Soot

### ISSUE THREAD

**Issue by LouisonGitzinger** [soot-oss/soot#999]
Hi there, 
I'm trying to instrument APKs in order to hook some of their methods.
For the two following APKs, I'm able to unpack-repack-align-sign them successfully but when I'm starting to run them on an Emulator, they both crash for the same reason : 
- le_monde.apk : 
```java
07-24 13:46:28.512 22875 22875 E AndroidRuntime: java.lang.ExceptionInInitializerError
07-24 13:46:28.512 22875 22875 E AndroidRuntime: 	at com.google.firebase.appindexing.internal.zzs.<init>(Unknown Source:0)
07-24 13:46:28.512 22875 22875 E AndroidRuntime: 	at com.google.firebase.appindexing.internal.zzq.<init>(Unknown Source:5)
07-24 13:46:28.512 22875 22875 E AndroidRuntime: 	at com.google.firebase.appindexing.FirebaseUserActions.a(Unknown Source:21)
07-24 13:46:28.512 22875 22875 E AndroidRuntime: 	at com.lemonde.androidapp.java.analytic.GoogleElementIndexer.a(Unknown Source:299)
07-24 13:46:28.512 22875 22875 E AndroidRuntime: 	at com.lemonde.androidapp.java.manager.ElementTrackingManager.a(Unknown Source:120)
07-24 13:46:28.512 22875 22875 E AndroidRuntime: 	at com.lemonde.androidapp.java.manager.ElementTrackingManager.onElementAvailableEvent(Unknown Source:47)
07-24 13:46:28.512 22875 22875 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-24 13:46:28.512 22875 22875 E AndroidRuntime: 	at com.squareup.otto.EventHandler.a(Unknown Source:43)
07-24 13:46:28.512 22875 22875 E AndroidRuntime: 	at com.squareup.otto.Bus.b(Unknown Source:0)
07-24 13:46:28.512 22875 22875 E AndroidRuntime: 	at com.squareup.otto.Bus.a(Unknown Source:70)
07-24 13:46:28.512 22875 22875 E AndroidRuntime: 	at com.squareup.otto.Bus.c(Unknown Source:92)
07-24 13:46:28.512 22875 22875 E AndroidRuntime: 	at com.lemonde.androidapp.java.fragment.AbstractElementFragment$ElementResponseListener.a(Unknown Source:47)
07-24 13:46:28.512 22875 22875 E AndroidRuntime: 	at com.lemonde.androidapp.java.manager.element.ElementManager$ResponseRunnable.run(Unknown Source:4)
07-24 13:46:28.512 22875 22875 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
07-24 13:46:28.512 22875 22875 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-24 13:46:28.512 22875 22875 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
07-24 13:46:28.512 22875 22875 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
07-24 13:46:28.512 22875 22875 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-24 13:46:28.512 22875 22875 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
07-24 13:46:28.512 22875 22875 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
07-24 13:46:28.512 22875 22875 E AndroidRuntime: Caused by: java.lang.ClassCastException: com.google.android.gms.internal.zzatp cannot be cast to com.google.android.gms.internal.zzath
07-24 13:46:28.512 22875 22875 E AndroidRuntime: 	at com.google.android.gms.internal.zzasn.<clinit>(Unknown Source:33)
07-24 13:46:28.512 22875 22875 E AndroidRuntime: 	... 20 more
```

- leboncoin.apk : 
```java
07-24 13:56:40.207 24047 24047 E AndroidRuntime: java.lang.ExceptionInInitializerError
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at com.google.android.gms.appindexing.AppIndex.<clinit>(Unknown Source:0)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at fr.leboncoin.manager.GoogleApiClientManager.<init>(Unknown Source:42)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at fr.leboncoin.dagger.module.UtilsModule.provideGoogleApiClientManager(Unknown Source:7)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at fr.leboncoin.dagger.module.UtilsModule_ProvideGoogleApiClientManagerFactory.get(Unknown Source:12)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at fr.leboncoin.dagger.module.UtilsModule_ProvideGoogleApiClientManagerFactory.get(Unknown Source:0)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at dagger.internal.DoubleCheck.get(Unknown Source:15)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at fr.leboncoin.feature.home.HomeFragment_MembersInjector.injectMembers(Unknown Source:98)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at fr.leboncoin.feature.home.HomeFragment_MembersInjector.injectMembers(Unknown Source:4)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at fr.leboncoin.dagger.component.DaggerAppComponent$HomeComponentImpl.resolveDependencies(Unknown Source:2)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at fr.leboncoin.feature.home.HomeFragment.onCreate(Unknown Source:15)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at android.support.v4.app.Fragment.performCreate(Unknown Source:15)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source:760)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at android.support.v4.app.FragmentTransition.addToFirstInLastOut(Unknown Source:255)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at android.support.v4.app.FragmentTransition.calculateFragments(Unknown Source:20)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at android.support.v4.app.FragmentTransition.startTransitions(Unknown Source:53)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(Unknown Source:148)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(Unknown Source:97)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(Unknown Source:22)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(Unknown Source:0)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at fr.leboncoin.ui.navigation.AbstractNavigationController.setFragment(Unknown Source:92)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at fr.leboncoin.ui.navigation.AbstractNavigationController.onNavigate(Unknown Source:1003)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at fr.leboncoin.ui.activities.MainActivity.onCreate(Unknown Source:310)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7009)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7000)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: Caused by: java.lang.ClassCastException: com.google.android.gms.internal.zzauz cannot be cast to com.google.android.gms.internal.zzaur
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	at com.google.android.gms.internal.zzatv.<clinit>(Unknown Source:33)
07-24 13:56:40.207 24047 24047 E AndroidRuntime: 	... 35 more
```

I order to debug that, I did not instrumented the applications and only unpacked and repackaged them.
I also tried to do the same with `apktool` and it appears that it works fine with it. (No crash for both of the apps).

Does someone know how soot handles the repackaging of an apk after loading it ?

Here are the two apks : 
• le_monde.apk: https://transfer.sh/XbUq9/le_monde.apk
• leboncoin.apk: https://transfer.sh/VRcW6/leboncoin.apk

In order to reproduce the bug you must : 
1. Init soot with the following options : 
```java
Options.v().set_allow_phantom_refs(true);
Options.v().set_validate(true);
Options.v().set_src_prec(Options.src_prec_apk);
Options.v().set_android_jars(PATH_TO_ANDROID_JARS);
Options.v().set_process_dir(Collections.singletonList(apk.getAbsolutePath()));
Options.v().set_process_multiple_dex(true);
Options.v().set_whole_program(true);
Options.v().set_output_dir(outputDirectory);
Options.v().set_output_format(Options.output_format_dex);
Options.v().set_force_overwrite(true);
Scene.v().loadNecessaryClasses();
```
2. Repackage the application using : 
```java
PackManager.v().writeOutput();
```
3. `zipalign`and `sign` the output apk
4. Install and run the apk in an emulator.
	- For `le_monde.apk` the app will not crash until you try to navigate on an article (it's a newspaper app)
	- For `leboncoin.apk`the app will crash as soon as it will try to load the Main activity.

Thank you in advance for your help, 
Best, 

Louison

**Comment by mbenz89** [comment]
I'm witnessing the same issue with another app:

```
04-10 13:08:36.888  5508  5578 E AndroidRuntime: FATAL EXCEPTION: pool-10-thread-1
04-10 13:08:36.888  5508  5578 E AndroidRuntime: Process: com.mal.saul.coinmarketcap, PID: 5508
04-10 13:08:36.888  5508  5578 E AndroidRuntime: java.lang.ExceptionInInitializerError
04-10 13:08:36.888  5508  5578 E AndroidRuntime: 	at com.google.android.gms.d.b.a(dalvik_source_com.mal.saul.coinmarketcap-51.apk)
04-10 13:08:36.888  5508  5578 E AndroidRuntime: 	at com.google.android.gms.internal.b.gr.<clinit>(dalvik_source_com.mal.saul.coinmarketcap-51.apk)
04-10 13:08:36.888  5508  5578 E AndroidRuntime: 	at com.google.android.gms.b.a.a(dalvik_source_com.mal.saul.coinmarketcap-51.apk)
04-10 13:08:36.888  5508  5578 E AndroidRuntime: 	at com.google.android.gms.internal.d.fd.b(dalvik_source_com.mal.saul.coinmarketcap-51.apk)
04-10 13:08:36.888  5508  5578 E AndroidRuntime: 	at com.google.android.gms.internal.d.fd.a(dalvik_source_com.mal.saul.coinmarketcap-51.apk)
04-10 13:08:36.888  5508  5578 E AndroidRuntime: 	at com.google.android.gms.internal.d.fe.run(dalvik_source_com.mal.saul.coinmarketcap-51.apk)
04-10 13:08:36.888  5508  5578 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
04-10 13:08:36.888  5508  5578 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
04-10 13:08:36.888  5508  5578 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
04-10 13:08:36.888  5508  5578 E AndroidRuntime: Caused by: java.lang.ClassCastException: com.google.android.gms.internal.j.d cannot be cast to com.google.android.gms.d.i
04-10 13:08:36.888  5508  5578 E AndroidRuntime: 	at com.google.android.gms.d.b.<clinit>(dalvik_source_com.mal.saul.coinmarketcap-51.apk)
04-10 13:08:36.888  5508  5578 E AndroidRuntime: 	... 9 more
````

App: [`com.mal.saul.coinmarketcap-51.apk`]( https://play.google.com/store/apps/details?id=com.mal.saul.coinmarketcap)
